### ISSUE TITLE
Depress warnings

### ISSUE THREAD

**Issue by CodeEagle** [mac-cain13/R.swift#100]
warning: [R.swift] Skipping 2 resource files because symbol 'localizableStrings' would be generated for all of these files: Localizable.strings, Localizable.strings
warning: [R.swift] Skipping 2 resource files because symbol 'infoPlistStrings' would be generated for all of these files: InfoPlist.strings, InfoPlist.strings

**Comment by mac-cain13** [comment]
Thanks for reporting this! Will look into and fix it!

**Comment by mac-cain13** [comment]
This will be fixed in the 1.0.0 beta 2. We now don't allow strings file to be accessed through R.file.* 

This doesn't solve the case where you put your own files in language folders. But it will solve this particular issue.

**Comment by GlaucoNeves** [comment]
I'm getting the same warning with some localized file I have. Is there a way to suppress or disable this warning in my project?

warning: [R.swift] Skipping 3 resource files because symbol '**' would be generated for all of these files: **, **, **

**Comment by mac-cain13** [comment]
@GlaucoNeves Thanks for reporting this, looks like you're running into issue #155. Think I shoul really take a look at that.

**Comment by GlaucoNeves** [comment]
@mac-cain13 Yes, that issue would fix my problem. At first I was just looking for a way to disable resource reference generation or suppress the warning. Thanks!

**Comment by romk1n** [comment]
How did you guys solve this problem ? i started to have 66 warnings like this since updating from version 2.1.0 ? Thanks.

**Comment by mac-cain13** [comment]
Localized strings files shouldn't trigger warnings, I think other files still do at the moment. We'll need to fix #155 to solve this problem and have proper support voor localized files.
