### ISSUE TITLE
Segue with customClass must be of kind custom

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#103]
If this is not the case iOS 8 can crash, this segue crashed our app on iOS 8 build with Xcode 7.1 / iOS 9 SDK:

`<segue destination="sbB-dE-7hR" kind="show" identifier="sendCatalogueControllerSegue" customClass="NavigationPushNotAnimatedSegue" customModule="PostNL" customModuleProvider="target" id="jE1-Sb-CMz"/>`

R.swift could generate a warning, would be nice.

**Comment by tomasharkema** [comment]
plz fix yo

**Comment by tomasharkema** [comment]
and merge my pr
