### ISSUE TITLE
Error: Not all mandatory option given

### ISSUE THREAD

**Issue by mats-claassen** [mac-cain13/R.swift#116]
Hi I have created a project and added the run script just like the documentation says but when I build the project it keeps saying "[R.swift] Not all mandatory option given."
I did add this script: "$PODS_ROOT/R.swift/rswift" "$SRCROOT"

**Comment by mac-cain13** [comment]
Hey @mats-claassen!

Thanks for trying R.swift. That error doesn't sound right indeed.

R.swift uses some environment variables Xcode publishes when you build, so it seems that it's missing one or more of these options. I think I should improve R.swift to tell you what it is that is missing, that would be useful, created an issue for that here: #117

Maybe you could check this out:
- What version of Xcode do you use? Is it the latest version?
- Could you paste the full output including environment variables here so I can check what environment variable is missing? 

You can find this in the `Report navigator` (⌘+8) then select a build, look for the shellscript step that triggers R.swift and expand it by clicking the three horizontal stripes, the complete log for the R.swift step will now expand.

**Comment by mats-claassen** [comment]
Thanks @mac-cain13 . I just checked the exported variables against those listed in R.swift/input.swift. Seems the PRODUCT_BUNDLE_IDENTIFIER is not present. I will check if I can resolve this.

**Comment by mac-cain13** [comment]
Glad to hear it's fixed!

Just wondering: What did you need to do to make `PRODUCT_BUNDLE_IDENTIFIER` present?

**Comment by mats-claassen** [comment]
After creating the project there was a warning in Xcode saying "Update to recommended settings". One of those settings was the PRODUCT_BUNDLE_IDENTIFIER.
