### ISSUE TITLE
Build failing due to incorrect initialViewController type generated in main struct of storyboard struct in generated swift file

### ISSUE THREAD

**Issue by gauravmnit07** [mac-cain13/R.swift#118]
the initialViewController's type returned is ProjectName.MyViewController instead of MyViewController.

Main.Storyboard view controller's markup snipplet:
viewController id="BYZ-38-t0r" customClass="MyViewController" customModule="ProjectName"

**Comment by mac-cain13** [comment]
Thanks for reporting this @gauravmnit07!

R.swift should detect if a module is the module of the product you're working on. It does this based on the environment variable `PRODUCT_MODULE_NAME`. Could you check if the variable is set to the same name as you see in `customModule`?

You can find this in the Report navigator (⌘+8) then select a build, look for the shellscript step that triggers R.swift and expand it by clicking the three horizontal stripes, the complete log for the R.swift step will now expand. Scroll down to where you find the `PRODUCT_MODULE_NAME` variable.

Would be useful to know if:
- `customModule` name is the same as `PRODUCT_MODULE_NAME`
- `PRODUCT_MODULE_NAME` is indeed the name of the module/app binary you're building
- `customModule` name is indeed the name of the module/app binary you're building

**Comment by gauravmnit07** [comment]
@mac-cain13 Above issue was happening due to mismatch of customModule and PRODUCT_MODULE_NAME. I'm maintaining different product names based on schemes and thus product module name too. I have not specified any custom module for ViewController in storyboard so I thought it will pick the correct one automatically which is not happening. So I have explicitly removed the customModule in snippet mentioned in above comment which sets customModule as none which is fine for me otherwise I have to explicitly change the customModule manually based on scheme which I don't want to do.
Thanks for quick response.

**Comment by mac-cain13** [comment]
Sorry for the delay in my reply.

I don't totally get why the `PRODUCT_MODULE_NAME` is not equal to the target you are compiling/running R.swift for. This should be equal and thus using the correct type reference.

Would you be able to create a small testproject demonstrating the issue? Maybe you can put it on github or upload it in a zip here. That would help me understand the issue and help you fix it.

**Comment by gauravmnit07** [comment]
PRODUCT_MODULE_NAME is same as the target name. I was saying that customModule attribute in storyboard's ViewController markup (viewController id="BYZ-38-t0r" customClass="MyViewController" customModule="ProjectName") is not correctly picked by Xcode. Like I said I'm maintaining different product names based on schemes for e.g 'TestProjectDebug' for debug scheme and 'TestProject' for release scheme and hence the product module name too. And I have set customModule attribute field as blank in storyboard so that it can pick the correct customModule based on my target i.e 'TestProjectDebug' for debug scheme and 'TestProject' for release scheme which is not occurring. So I have to explicitly change the customModule manually in storyboard based on scheme which I don't want to do. 
Attaching the TestProject demonstrating the same so that you can checkout by yourself.
Thanks again.
[TestProject.zip](https://github.com/mac-cain13/R.swift/files/59140/TestProject.zip)

**Comment by mac-cain13** [comment]
Thanks for the demo project. Very helpful, I've created a fix for this specific problem. If the storyboard tells that the custom module provider is the target we won't name the module but assume it's available without importing it. 

This will be fixed in 1.0.0 beta 2.

**Comment by gauravmnit07** [comment]
Great!!
