### ISSUE TITLE
Skipping duplicate reuseIdentifiers?

### ISSUE THREAD

**Issue by AndrewSB** [mac-cain13/R.swift#119]
I have two UITableView's, both with the same resuseIdentifier. I'm being told that it's skipping the reuseIdentifier?

<img width="828" alt="screen shot 2015-12-02 at 12 03 51 pm" src="https://cloud.githubusercontent.com/assets/3814772/11542607/02d19628-98ed-11e5-8ab7-f688c451dfbb.png">

**Comment by mac-cain13** [comment]
Thanks for using R.swift! That's correct, this is how R.swift works at the moment.

You can read more about this in issue https://github.com/mac-cain13/R.swift/issues/34 where it was introduced and in https://github.com/mac-cain13/R.swift/issues/99 where @kylejm asks basically the same question as you.

If you have any ideas or +1s on that issue please comment on that issue!

**Comment by AndrewSB** [comment]
responded in #34
