### ISSUE TITLE
Move R.swift types to library

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#122]
R.swift currently has some types that are used in the generated code in `R.generated.swift`.

For example: `ReuseIdentifier`, `NibResource`, and the recently introduced `TypedStoryboardSegueInfo`.

It would be nice if these are moved to a R.swift library, instead of being in the generated file. That way other libraries can extend R.swift by using these types and creating extensions.

**Comment by mac-cain13** [comment]
If you want to discuss this one please feel free to do so in #123.
