### ISSUE TITLE
Support for Localizable

### ISSUE THREAD

**Issue by amarcadet** [mac-cain13/R.swift#126]
Hi,

Do you plan to add support for Localizable files?
Something like `R.i18n.key`, like SwiftGen do?

Thanks

**Comment by mac-cain13** [comment]
Yes, absolutely! It's in issue #41, but thanks for the +1!

It's on the list.

**Comment by amarcadet** [comment]
My bad, thanks for the quick reply!

**Comment by mac-cain13** [comment]
No problem! Thanks for letting me know that you use R.swift and took the time to create an issue. :)
