### ISSUE TITLE
Type UITabBarController and UINavigationController with a helper like segues have

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#127]
See also PR #110.

I think we should take similar approach as with segues in PR https://github.com/mac-cain13/R.swift/pull/80, here you now do: 
```
func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject) {
  if let segue = R.segue.myViewController.someSegue.typeSegue(segue) {
    let typedDestinationVC = segue.destinationViewController
  }
}
```

We could do this for the tabbar, we create a `R.storyboard.main.mainTabBarController.typeTabBar(tabBarController: UITabBarcontroller)` method. You call that to get a `TypedTabBarController` type back that contains typed properties such as `firstTabController` (up to `fifthTabController`) and possibly other controllers.

I think this is:
- More in line with how segues now do it, creating a more uniform character
- The method would fail if one tab can't be converted, gives more assurance everything is okay at once
- It feels clearer to me than the currently proposed solution.

**Comment by tomlokhorst** [comment]
I don't think R.swift should invent identifiers on its own.

If there are no user supplied identifiers, for which you need to write a string in Apples APIs, I don't see a need for R.swift.

**Comment by mac-cain13** [comment]
Let's close this one in favor of #260 since there are more concrete solutions discussed.
