### ISSUE TITLE
Add support for unwind segues

### ISSUE THREAD

**Issue by jl322137** [mac-cain13/R.swift#128]

**Comment by mac-cain13** [comment]
Good one! Should be nice to have support for unwinds indeed. :)

**Comment by sxua** [comment]
Unwind segues detects successfully in 0.10+, but not in 1.0.
It shows warning now:
`[R.swift] Destination view controller with id WPG-tj-XTu for segue PrimaryCodeChosen in PrimaryCodeSelectionViewController not found in storyboard MainStoryboard. Is this storyboard corrupt?`

**Comment by mac-cain13** [comment]
I think the 0.13 release broke this, it was more luck than a real feature that they worked before. :)

But thanks for using R.swift and letting me know you want this feature. It's on the list and I'll see if I can implement it anytime soon!

**Comment by sxua** [comment]
Yeah, just checked - latest working version is 0.12. Would be nice to see it again in 1.0 :-) Thank you!

**Comment by laurivers** [comment]
Does version 1.1.1 already support unwind segue? I use 1.1.1, and still have a lot warnings like:
`[R.swift] Destination view controller with id WPG-tj-XTu for segue PrimaryCodeChosen in PrimaryCodeSelectionViewController not found in storyboard MainStoryboard. Is this storyboard corrupt?`

**Comment by mac-cain13** [comment]
Not yet! 1.2 will contain unwind segue support. I'll release that version this week!

**Comment by mac-cain13** [comment]
This is in the now released 1.2.0!

**Comment by laurivers** [comment]
Thanks!
