### ISSUE TITLE
Load images with `UIImage(contentsOfFile:)` using R.swift

### ISSUE THREAD

**Issue by kenyth** [mac-cain13/R.swift#132]
I have some images that would be used for only once, so I don't want to use UIImage(named:), thus not put them in system cache, but to use UIImage(contentsOfFile:). But R.swift uses UIImage(named:) to preload all images into system cache. Is there any way to let R.swift ignore these files.

Currently, I use a workaround that change file names of those images into that starting with numbers, so R.swift would ignore them and report warning.

**Comment by mac-cain13** [comment]
First of; As long as you don't use `R.image.myOnceUsedImage` nothing happens with the image. So you van just name the image as you'd like and still load it with `UIImage(contentsOfFile:)`.

I think ignoring images is not the way to go. We want to include all resources, but we maybe we could think of something that you can use in combination with `UIImage(contentsOfFile:)` so you're not forces to use `UIImage(named:)`.

Any proposals?

**Comment by kenyth** [comment]
Thanks for response.

You're right. I looked into documentation (I'm not experienced in Swift and iOS development.) and found out static members of structs and enums are all lazily initialized. So, unlike what I thought, it won't affect anything, if I don't access them via R.swift.

But I still prefer warnings (I changed your code to suppress all warnings so I can gradually adopt R.swift, and I suggest there should be an official option for this.) over not-access-them-via-R.swift, which seems safer to me.

Thanks again.

**Comment by kenyth** [comment]
And about what you asked below, it'd be surely a better design.
```
we could think of something that you can use in combination with UIImage(contentsOfFile:) so you're not forces to use UIImage(named:).
```

**Comment by mac-cain13** [comment]
I surely could make a `--nowarn` option for example to suppress warnings, but then again you would miss important warnings. Maybe there should be an option to not warn about more specific things. I'll think a bit about it.

More on topic; I think indeed a way to make loading images with `UIImage(contentsOfFile:)` would be nice. Not sure how it should fit into the current image loading, but I'll put it on the list!

**Comment by mac-cain13** [comment]
Update:

I've made the first steps for this on the 1.0.0 branch. Images will change to the following syntax in R.swift 1.0:

```swift
// R.swift 1.0: Using UIImage(named:)
let image = R.image.settingsIcon()

// R.swift 1.1: Load with UIImage(contentsOfFile:)
// Concept code, subject to change etc etc
let image = UIImage(contentsOfFile: R.image.settingsIcon.path)
```

So I've made the first changes to support this, in the future more "meta" info will be available for resources so you can use it in a more flexible way. :)

**Comment by mac-cain13** [comment]
At this moment it is possible to load images from a file this way:
```swift
let image = UIImage(contentsOfFile: R.file.settingsIconPng())
```

Since it is not possible to load images in an asset folder using `contentsOfFile` I think this is sufficient for now. Please let me know if you think it isn't. If there is a good use case I'd love to revisit this decision again, but I think this will work out just fine.
