### ISSUE TITLE
R.segue and inheritance 

### ISSUE THREAD

**Issue by ntnmrndn** [mac-cain13/R.swift#133]
Hi,
I really like the addition of the classname to access a segues, it's really helpful in most cases.

However I ran into an issue migrating my code to the new R.swift (appart from a bunch of lines of codes to update);

I used inheritance heavily in my view controllers. A simplified version would be:

A view controller A, with inherited implementations B, and C.
A handle the segue transition to the next screen (D, or E)
However, since B and C actually perform the segue to C, they each have a segue to the next screens, sharing the same identifier.

Since the new update, I need to access the identifier in A through either B or C, which is a bit inconvenient as would be duplicating the code in B or C.

Should we make R.swift evolve to support this use case ?

**Comment by mac-cain13** [comment]
Hmm, interesting and valid point there. I think it would be nice to support something like this, but I don't have a concrete idea how we should do it. Especially given the fact that we don't parse/inspect your Swift code. So we don't have knowledge about superclasses etc.

A workaround options for now that I can think of are:
- Duplicating code
- Create a ViewController A scene in your storyboard that is unreachable, but will create the segue in the R-file
- Use one of the segues, for example `R.segue.viewControllerB.segueToD`, but never use them to get typedInfo. Then you will be okay.

All of them are quite ugly. I don't have a clear idea how to solve this nicely, do you have any proposals to consider?

**Comment by ntnmrndn** [comment]
We could detect that identifiers are the same, and create an access either directly from R.segue.segueIdentifier or from R.segue.UIViewController.segueIdentifier ?

**Comment by mac-cain13** [comment]
I think there is no clean way for R.swift to support this. We never know if a segue in a storyboard is only for view controller B or should always be there for every subclass of A. That makes it hard, we could generate all segues always on `UIViewController` but that would be quite messy and also make the type of the source view controller quite useless. 

The possible workarounds for now are:
- Make a storyboard with view controller A in it to view controller D and E so you have the segues you want
- Create code that checks which subclass you are at the moment and then takes the correct segue
- Only use one of the segue identifiers to start the segue and don't use the types: `performSegue(R.segue.viewControllerB.toViewControllerD.identifier, sender: nil)`
