### ISSUE TITLE
Referenced types in other modules not working

### ISSUE THREAD

**Issue by Tvede-dk** [mac-cain13/R.swift#135]
When using types from another module (eg a custom view class) combined with an identifier (eg the cell identifier) , the resulting R file does not know about the type (since it does not include the external module), resulting in a undeclared type.  

the issue:
 struct reuseIdentifier {
    static var someCell: ReuseIdentifier<ExternalType> { return ReuseIdentifier(identifier: "SomeIdentifier") }
  }
Where the ExternalType is external / in another module. 

The solution would be to import the module (actually import all modules referenced from storyboard / xib files, that is not the current module ).

I will be happy to create a demo project for this case if needed be.

**Comment by mac-cain13** [comment]
Yeah, I can see that such a situation would not work. A sample project would be awesome, makes it much easier to see what is wrong and what would be the solution. If you have a moment to create one please do so!

If I understand you correctly the view with the reuse identifier is in another module, I think that module itself should have a R-file that is public. Then you could use that one directly from your project. Would that solve the problem?

**Comment by Tvede-dk** [comment]
Here you go :) 
[rswiftbug.zip](https://github.com/mac-cain13/R.swift/files/65017/rswiftbug.zip)
I hope you can use the sample :) 

not the reuse Identifier, the type of the reusable cell, and even if that module had a R.swift file, it would not resolve the type in the main projects R.swift file :) 
And my project uses cocoapods to create the lib, which is indeed very difficualt setting up with r.swift, due to the way things works (that is a whole other topic :) )

**Comment by mac-cain13** [comment]
Tnx, very useful. I'm on it! :)

**Comment by mac-cain13** [comment]
This one is fixed on the release/1.0.0 branch, will be in the next beta. :)
