### ISSUE TITLE
Type CoreData stuff

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#14]
We could generate full ManagedObjects in Swift (since Apple does that so poorly), but we also could make querying better by providing something like `R.managedObject.car.color == "color"` that you can use a `%K` value in a predicate.

**Comment by ntnmrndn** [comment]
I would actually recommend using moggenerator for that instead.

**Comment by mac-cain13** [comment]
Yeah, I'm in doubt if this should be implemented. [mogenerator](https://github.com/rentzsch/mogenerator) and projects like [QueryKit](https://github.com/QueryKit/QueryKit) pretty much provide this kind of functionality.

R.swift could make references to your model file so you van de something like: R.coreData.myModel, but that could also be available when all resource files are available...

**Comment by mac-cain13** [comment]
Will leave stuff like this to mogenerator for now. :)
