### ISSUE TITLE
Give `optionsOrNil` parameters in Nib related functionals a default value of `nil`

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#141]
@sdevos requested to give `optionsOrNil` parameters in Nib related functionals a default value of `nil`, sounds like a nice idea.

**Comment by tomlokhorst** [comment]
Somewhat related; `firstView` function should also have a named parameter for `ownerOrNil`.

`func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIView?`

I'm unsure if `instantiateWithOwner` should be renamed to: `func instantiate(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> [AnyObject]`

**Comment by mac-cain13** [comment]
Yeah, I think you're right. It either should be `func firstView(owner ownerOrNil: AnyObject?, ...` or `func firstViewWithOwner(ownerOrNil: AnyObject?,  ...`

**Comment by tomlokhorst** [comment]
Don't know if it's a good idea to also default that one to `nil`, depends on the use case I guess.

Either way, I like `firstView(owner:, options:)` over `firstViewWithOwner(options:)`.

**Comment by mac-cain13** [comment]
Discussed it with @sdevos, I think we can type the owner since you define it in the xib together with what kind of class it should be.

Must still be optional though, since you always can decide to give the nib no owner without indicating this in de xib file.

**Comment by mac-cain13** [comment]
Fixed in the 1.0 branch
