### ISSUE TITLE
Dequeue reusable cell of type

### ISSUE THREAD

**Issue by justinmakaila** [mac-cain13/R.swift#142]
I think it would be really awesome if some sort of interface was provided that dequeued a cell of a certain type. I used to handle it utilizing my `NibView` and `ReuseIdentifier` protocol like so:

[UICollectionView+NibView](https://gist.github.com/justinmakaila/18971b5aa3ce9d955d82)
[UITableView+NibView](https://gist.github.com/justinmakaila/83014b97e774596a1a58)

**Comment by mac-cain13** [comment]
Sounds interesting, but I don't think I get it entirely. Could you give a small usage example? How do you use it when writing a table view for example and what makes it better then the current situation?

**Comment by justinmakaila** [comment]
Well, I think the best advantage this offers is the fact that dequeued cells are now typed. The usage example in `Documentation/Examples.md` shows this:
```
  override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let textCell = tableView.dequeueReusableCellWithIdentifier(R.nib.textCell.reuseIdentifier, forIndexPath: indexPath)!
    textCell.mainLabel.text = "Hello World"
    return textCell
  }
```
Which is not 100% accurate, because `dequeueReusableCellWithIdentifier` returns a `UITableViewCell`, which means that `mainLabel` would not exist unless you were to cast it to your subclass, which would then look like:

```
  override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    if let textCell = tableView.dequeueReusableCellWithIdentifier(R.nib.textCell.reuseIdentifier, forIndexPath: indexPath) as? TextCell {
      textCell.mainLabel.text = "Hello World"
      return textCell
    }

    return UITableViewCell()
  }
```
The solution I provided above allows for typed access to the cells after dequeueing. Here's an example from a past project:
```
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    if let hunt = viewModel.huntForIndexPath(indexPath) {
        let huntCellViewModel = HuntCellViewModel(hunt: hunt)
        
        if let cell = tableView.dequeueNibView(HuntCell) {
            cell.viewModel = huntCellViewModel
            
            return cell
        }
    }
    
    return UITableViewCell()
}
```
Under this system, I created `UITableViewCell` subclasses which conformed to a protocol which provided the nib and identifier, and I passed the type to my `dequeueNibView` method, which is provided in a `UITableView` extension
```
extension UITableView {
    func dequeueNibView<T: UITableViewCell where T: CellNibView>(view: T.Type) -> T? {
        return dequeueReusableCellWithIdentifier(view.reuseIdentifier()) as? T
    }
    
    func registerNibView<T: UITableViewCell where T: CellNibView>(view: T.Type) {
        registerNibView(view, reuseIdentifier: view.reuseIdentifier())
    }
    
    func registerNibView<T: UITableViewCell where T: CellNibView>(view: T.Type, reuseIdentifier: String) {
        registerNib(view.nib(), forCellReuseIdentifier: reuseIdentifier)
    }
    
    func dequeueHeaderFooterNibView<T: UITableViewHeaderFooterView where T: CellNibView>(view: T.Type) -> T? {
        return dequeueReusableHeaderFooterViewWithIdentifier(view.reuseIdentifier()) as? T
    }
    
    func registerHeaderFooterNibView<T: UITableViewHeaderFooterView where T: CellNibView>(view: T.Type) {
        registerHeaderFooterNibView(view, reuseIdentifier: view.reuseIdentifier())
    }
    
    func registerHeaderFooterNibView<T: UITableViewHeaderFooterView where T: CellNibView>(view: T.Type, reuseIdentifier: String) {
        registerNib(view.nib(), forHeaderFooterViewReuseIdentifier: reuseIdentifier)
    }
}
```
I'm not sure if type information is out of the scope of R.swift, but running off of the idea that the purpose of the library is to provide typed access to your resources, I believe that this improvement would benefit the community as a whole, making it much easier to reason about the reusable views that are being instantiated from `nib`s.

**Comment by mac-cain13** [comment]
Thanks for your reply!

I think the example is correct, if you set the table view cell subclass to your custom subclass in the xib, then R.swift will do the cast for you when you dequeue and the example will work.

You can set a custom class if you select the `UITableViewCell` in the xib and in the top right of Xcode set a class in this field:
![schermafbeelding 2016-01-06 om 14 25 06](https://cloud.githubusercontent.com/assets/618233/12143496/66d57374-b481-11e5-84bb-84407a1e0314.png)

That should work, or are we talking about different things now?

**Comment by justinmakaila** [comment]
It's worth noting that I'm using the beta of R.swift.

I just updated my `.xib` file as you mentioned, and updated my table view code after realizing that i was using `dequeueReusableCellWithIdentifier(identifier: String)` provided by `UITableView` and not `dequeueReusableCellWithIdentifier(identifier: Identifier)`. 

That's a really slick way of handling dequeuing. Thanks for the help!

**Comment by justinmakaila** [comment]
@mac-cain13  Do you mean to set the File's Owner or the actual `UITableViewCell` view? I'm getting an error for key vale coding at nib initialization

**Comment by mac-cain13** [comment]
I did not mean the File's Owner, but the cell itself. Like this:
<img width="838" alt="schermafbeelding 2016-01-06 om 19 10 17" src="https://cloud.githubusercontent.com/assets/618233/12150287/41578cc2-b4a9-11e5-8903-120a68c48e7f.png">

Select the cell on the left, then set the custom class to your type of cell.

**Comment by justinmakaila** [comment]
:+1: thanks!
