### ISSUE TITLE
Use of undeclared type

### ISSUE THREAD

**Issue by kaphacius** [mac-cain13/R.swift#143]
I've installed the pod, pasted the script and generated the R file. But the some (not all of them) of the structs my project name as a type
```
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> <project name>.ConnectorPricingCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as?  <project name>.ConnectorPricingCell
      }
```

Which isn't defined anywhere, so the it doesn't compile. Interesting that it doesn't happen to all of them, just some. Is it something in my project causing this?

**Comment by mac-cain13** [comment]
Could you check the Xib file this `ConnectorPricingCell` is in and especially the "Custom Class" fields in the right side panel:

![schermafbeelding 2016-01-06 om 14 25 06](https://cloud.githubusercontent.com/assets/618233/12143496/66d57374-b481-11e5-84bb-84407a1e0314.png)

I think the module field is filled in incorrectly in your case. You could try emptying the field so it states `None`, that should work I think.

Let me know if that works out!

**Comment by kaphacius** [comment]
![this]
(https://i.gyazo.com/c25f982ed63ec79a8c521b49d08e97ac.png)
in fact all of the xib files have this module set, there is no option for none

**Comment by mac-cain13** [comment]
You're right, `None` is only available when no class is selected. Clearing it to make it say `Current` should be okay. Is that solving the problem?

Thinking of it, what version of R.swift are you using? The new 1.0 betas have fixes for this problem. So I think the 1.0 release will also fix this. Emptying the Module field could be a workaround for now.

**Comment by kaphacius** [comment]
I'm using the one from CocoaPods. Is it 1.0? 
By emptying you mean editing the generated source code?

**Comment by mac-cain13** [comment]
The current stable on Cocoapods is 0.13, so you're using that one unless you explicitly opt-in to the beta. 

By emptying I mean setting the `Module` field to `Current - The_New_Motion` in the light gray color. If that isn't working for you, I would advice to upgrade to version 1.0 beta which is pretty close to being release.

You can do this by editting the R.swift line your Podfile to `pod 'R.swift', '~> 1.0.0.beta'` and run `pod install` again.

**Comment by kaphacius** [comment]
ah! now it works perfectly!
dank je wel!

**Comment by mac-cain13** [comment]
Great! Your welcome. :)

Graag gedaan.
