### ISSUE TITLE
Type '_R' has no member 'validate'

### ISSUE THREAD

**Issue by andreyslyusar** [mac-cain13/R.swift#147]
While migrate to v1.0.0 I get a next compile exception: ```Type '_R' has no member 'validate'```

```  
  private struct intern: Validatable {
    static func validate() throws {
      try _R.validate()
    }
  }
```

**Comment by mac-cain13** [comment]
Thanks for reporting, I'll check if I can reproduce it! :)

**Comment by bclymer** [comment]
This is happening for me as well.

**Comment by mac-cain13** [comment]
This could be the case when you have a project without anything storyboards to validate. Maybe also in other cases I'm not sure of. I've fixed this on master and will release it into 1.0.1 asap.

**Comment by mac-cain13** [comment]
Aaaaaaand 1.0.1 is released, that release should fix this issues.

Would be awesome if you could confirm whether or not it fixes your issue!

**Comment by andreyslyusar** [comment]
I can do it first thing tomorrow at office. Thanks a lot for quick reply.

**Comment by mac-cain13** [comment]
:+1:

**Comment by andreyslyusar** [comment]
I can confirm v1.0.2 fix compile issue. One more time thanks a lot for quick response.

**Comment by mac-cain13** [comment]
Awesome! Thanks for letting me know!
