### ISSUE TITLE
Tif and other image file format support.

### ISSUE THREAD

**Issue by smumryak** [mac-cain13/R.swift#149]
Currently "tif" image format is completely ignored. Haven't got any look on sources, but i believe R.swift currently supports "png", "jpg" and "gif" formats.

**Comment by mac-cain13** [comment]
Tiff and all other formats support by UIImage are also supported by R.swift: https://github.com/mac-cain13/R.swift/blob/master/R.swift/ResourceTypes/Image.swift#L12-L13 

I've also added a test Tiff image to the project now, that works as expected.
