### ISSUE TITLE
Use of R.file.* should be easier (Ambiguous use of File)

### ISSUE THREAD

**Issue by CodeEagle** [mac-cain13/R.swift#150]
Ambiguous use of File
![image](https://cloud.githubusercontent.com/assets/2311352/12371941/775962b2-bc80-11e5-9f21-bb8689f304f0.png)

**Comment by mac-cain13** [comment]
You have to type hint in this case. `let file: NSURL = R.file.provinceJson()` or `let file = R.file.provinceJson() as NSURL` should work. The compiler isn't sure at this moment is you'd want a string or url.

**Comment by amarcadet** [comment]
Same issue over here and I admit I don't understand the solution.

Here is an excerpt of my R.generated:
```swift
struct R: Rswift.Validatable {
  // ...
  struct file {
    static let newsTemplateHtml = FileResource(bundle: _R.hostingBundle, name: "NewsTemplate", pathExtension: "html")

    static func newsTemplateHtml(_: Void) -> NSURL? {
      let fileResource = R.file.newsTemplateHtml
      return fileResource.bundle?.URLForResource(fileResource)
    }
    
    static func newsTemplateHtml(_: Void) -> String? {
      let fileResource = R.file.newsTemplateHtml
      return fileResource.bundle?.pathForResource(fileResource)
    }

    // ...
```

And how I use it: 
```swift
guard let templateURL = R.file.newsTemplateHtml() as? NSURL else { return }
```

I have the very same issue "Ambiguous use of newsTemplateHtml".

What should I do? (Note: I am using version 1.0.2).

**Comment by amarcadet** [comment]
After some tests it occurs that the following works:
```swift
guard let templateURL: NSURL = R.file.newsTemplateHtml() else { return }
```

Not an obvious solution to me, maybe you could add sample code on how to use it in `guard let` to help beginners.

**Comment by mac-cain13** [comment]
Thanks for letting me know this is not obvious to you. I can imagine and I'll revisit my decision to make `R.file.newsTemplateHtml()` return a `String` as well as a `NSURL`, this makes it less clear how to use it.

Can be handy, but it seems it's hard to use when you first encounter it. Clearly it's something to look into.

**Comment by tomlokhorst** [comment]
Related, it would also be nice to have a initialiser for NSDate. So you can just write:

```swift
if let data = NSDate(contentsOfResource: R.file.provinceJson) {}
```
