### ISSUE TITLE
segue with UIView that on top bar make building failed

### ISSUE THREAD

**Issue by loveZLL** [mac-cain13/R.swift#152]
![2016-01-18 12 06 25](https://cloud.githubusercontent.com/assets/9654172/12383031/efd23faa-bddb-11e5-844f-f1e57378c8a2.png)
segue associate with these views will make script run failed.Can i disable the script to make segues?I just want make images

**Comment by mac-cain13** [comment]
Thanks for using R.swift! At this moment you can't only generate the images.

What error you get from the script? I tried to reproduce the error, but I don't get an error when using views the way you do.

Could you make an example project with the error? That would be very useful and that probably will help me fix the error.

**Comment by loveZLL** [comment]
I have made a project,what is your email?I find it will build fail when you make a segue like i said and segue id is not nil.if segue id is nil ,it won't fail.

**Comment by mac-cain13** [comment]
You can upload it as a zip-file here on github, that is the easiest way. :)

But I think I've spotted the error now indeed. :)

**Comment by loveZLL** [comment]
Ok,I think I needn't post it yo you.I just set my id to nil to go on.

**Comment by loveZLL** [comment]
Hello, I find a characteristic.Once you set a segue like this with id,It will be polluted,and you must delete it ,then can run the script :(

**Comment by mac-cain13** [comment]
Fixed it, will release it later today!

**Comment by loveZLL** [comment]
Ok.great!!!

**Comment by mac-cain13** [comment]
1.1.0 is now released and has a fix for your crash
