### ISSUE TITLE
Segue 'unwindSegue' in 'ViewController' not found in storyboard 'Name'. Is this storyboard corrupt?

### ISSUE THREAD

**Issue by eeschimosu** [mac-cain13/R.swift#154]
I have a lot of unwind segues in my storyboard. They all have reuse identifiers and they are all linked with the exit of a view controller to another view controller. For each one of them I get this warning when building and running the app.

The warning: Segue `<unwindSegue>` in `<ViewController`> not found in storyboard <`Name`>. Is this storyboard corrupt?

How can I resolve this warnings?

**Comment by mac-cain13** [comment]
Thanks for using R.swift and reporting this issue!

Quite a coincidence that you report it now since I implemented this today, see #153. So the next release of R.swift will have this feature! I expect to release it in a few days. :)

**Comment by eeschimosu** [comment]
Thanks for the quick response! I'm very happy to hear that you are releasing this in a few days. R.swift is great. Keep it up!

**Comment by mac-cain13** [comment]
This is in the now released 1.2.0!
