### ISSUE TITLE
Add StoryboardSegue type

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#158]
_As a fix for calling `performSegueWithIdentifier` on controllers that don't match the provided StoryboardSegueIdentifier:_

Add a "StoryboardSegue" type that wraps a StoryboardSegueIdentifier together with the appropriate ViewController. Something similar to:

```swift
public struct StoryboardSegue<Segue, Source, Destination> {
  public let identifier: StoryboardSegueIdentifier<Segue, Source, Destination>
  public let sourceViewController: Source
}
```

That way we can add a `performSegue` method in an extension:

```swift
extension StoryboardSegue where Source: UIViewController  {
  func performSegue() {
    sourceViewController.performSegueWithIdentifier(identifier, sender: sourceViewController)
  }
}
```

If possible, also change the existing UIViewController extension so that `performSegueWithIdentifier` can only be called with segues of the correct source type. Or remove it all together.

**Comment by mac-cain13** [comment]
As soon as we merge https://github.com/mac-cain13/R.swift.Library/pull/2 this will be solved I think. So closing this one already, since we only need to discuss some details on that other PR.
