### ISSUE TITLE
`UICollectionReusableView` not picked up 

### ISSUE THREAD

**Issue by tomasharkema** [mac-cain13/R.swift#162]
I added a UICollectionReusableView xib view, but it is not picked up by R.swift. 

Instead of being picked-up as `typealias ReusableType = UICollectionReusableView`, it just becomes a `UIView`. 

So the overload method `registerNib<Resource: NibResourceType where Resource: ReuseIdentifierType, Resource.ReusableType: UICollectionReusableView>(nibResource: Resource, forSupplementaryViewOfKind kind: String)` becomes practically useless.

_*FYI:*_

A UICollectionReusableView is represented in XML with the following code:

```
<collectionReusableView opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" restorationIdentifier="DevelopmentHeaderView" reuseIdentifier="DevelopmentHeaderView" id="jmD-Da-JfJ">
            <rect key="frame" x="0.0" y="0.0" width="320" height="2"/>
            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
            <color key="backgroundColor" red="0.29019607843137252" green="0.050980392156862744" blue="0.52156862745098043" alpha="1" colorSpace="calibratedRGB"/>
            <point key="canvasLocation" x="539" y="467"/>
        </collectionReusableView>
```

**Comment by mac-cain13** [comment]
I see, this is clearly related to this todo: https://github.com/mac-cain13/R.swift/blob/master/R.swift/ResourceTypes/Nib.swift#L11-L16

Shouldn't be to hard to fix this one! Let me know if you have time to create a PR, if not them I'll fix it anytime soon.
