### ISSUE TITLE
Localized strings

### ISSUE THREAD

**Issue by philipengberg** [mac-cain13/R.swift#168]
It would be extremely awesome to integrate a feature like [Laurine](https://github.com/JiriTrecak/Laurine) in R.swift, so that **every** kind of resource is collected in **one** place.

**Comment by mac-cain13** [comment]
Agreed, strings should be added to R.swift. There is a somewhat longer running issue already here where we discuss how to implement it: https://github.com/mac-cain13/R.swift/issues/41#issuecomment-186031624
