### ISSUE TITLE
about UICollectionViewCell

### ISSUE THREAD

**Issue by jl322137** [mac-cain13/R.swift#170]
when I use UICollectionViewCell, but didn't set it's subclass in storyboard, R.swfit will generate it to a wrong type ---- UIView, not UICollectionViewCell

so I have to create some black subclass of UICollectionViewCell to work around this issues

UITableViewCell is OK.

**Comment by mac-cain13** [comment]
Looked into this issue, I've now fixed an issue where `R.nib.someCollectionViewCell.firstView()` did return `UIView` instead of `UICollectionViewCell`. Is this the issue that you also have?

This fix will be in the next release!

**Comment by jl322137** [comment]
yes, R.nib.someCollectionViewCell.firstView() return UIView.

thx

**Comment by mac-cain13** [comment]
Cool, I will release version 1.3.1 where this is fixed as soon as I have time.
