### ISSUE TITLE
Class prefix detection

### ISSUE THREAD

**Issue by vshahpledge** [mac-cain13/R.swift#179]
I have a class WPMenuViewController. R.swift generates a struct with a camel case name wPMenuViewController. Maybe this should just stay as WPMenuViewController or wp_MenuViewController. I have my class prefix set in my project.

**Comment by mac-cain13** [comment]
Yeah, you making a fair point. I've seen some names generated that I also didn't really like. It's not like it's a major bug, but would be nicer to convert names a little bit different so it looks more natural.

I think we should collect some examples and decide how we want to convert them, then implement it. If it's a big change it should go in a major release, but if it's only a small change maybe we can deal with it in a minor release.

I'm thinking about something like this:
- `WPMenuViewController` -> `wpMenuViewController`
- `MenuViewController` -> `menuViewController`
- `menuViewController` -> `menuViewController`

Here we would lowercase all capitals at the start of a string except the last one, but the first letter will always be lowercase. Should think a bit more about other possibilities where this would result in strange names.

**Comment by mac-cain13** [comment]
This is merged into master, the default casing will not change. The 4.0 release will be the first release with this new casing. For now you can opt-in to the new behaviour by passing `--edge` to the rswift binary.
