### ISSUE TITLE
associatedtype: Expected declaration

### ISSUE THREAD

**Issue by AnyhowStep** [mac-cain13/R.swift#184]
Followed CocoaPods install instructions. Tried to run. Got three instances of that error.

ReuseIdentifierProtocol.swift

    public protocol ReuseIdentifierType: IdentifierType {
        // Type of this reuseable
        associatedtype ReusableType <-- Expected declaration
    }

StoryboardResource.swift

    public protocol StoryboardResourceWithInitialControllerType: StoryboardResourceType {
        // Type of the initial controller
        associatedtype InitialController <-- Expected declaration
    }

StoryboardViewControllerResource.swift

    public protocol StoryboardViewControllerResourceType: IdentifierType {
        associatedtype ViewControllerType <-- Expected declaration
    }

**Comment by tomlokhorst** [comment]
The current version of R.swift requires Xcode 7.3 with Swift 2.2.
In Swift 2.2 `associatedtype` is a new keyword replacing `typealias` in protocols.

If you're using Xcode 7.2 with Swift 2.1, you should use version 1.4.2 of R.swift.
With CocoaPods, you can specify a specific version like so:

```ruby
pod 'R.swift', '1.4.2'
```

**Comment by AnyhowStep** [comment]
Ah, all right. Terribly sorry about that. I just did that and it worked.
