### ISSUE TITLE
Add some instructions to "Colors"

### ISSUE THREAD

**Issue by endorno** [mac-cain13/R.swift#187]
Hi,
I propose adding some instructions for use .clr file in R.swift.

I didn't know I need adding .clr file to project target and I only located it at project path.
I think some beginners also make such mistake.

So please add instructions to https://github.com/mac-cain13/R.swift/blob/master/Documentation/Colors.md

Thanks!

**Comment by mac-cain13** [comment]
Good suggestion, will add the instruction! :)

If you're in the mood to write the instruction and create a PR feel free to do so.
