### ISSUE TITLE
not running demo

### ISSUE THREAD

**Issue by J-phantom** [mac-cain13/R.swift#189]
hi
when i run demo 
error :` Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

**Comment by mac-cain13** [comment]
There is no official demo project, so what demo are you trying to run?

**Comment by mac-cain13** [comment]
Let me know if you can share more info so we can help you out!
