### ISSUE TITLE
R.swift fails at parsing some files

### ISSUE THREAD

**Issue by Tvede-dk** [mac-cain13/R.swift#191]
Problem from the outer world: some nibs (could be other files) are not parsed correctly (how i first noticed it)

Real problem: 
the resolved urls (resource urls) sometimes contains the path appended twice, like:
(real correct path): Users/kasper/some-app/SomeApp/SomeFile.xib 
(R.swift tries to open): Users/kasper/some-app/SomeApp/SomeApp/SomeFile.xib

Thoughts:
- first of, mabye there should be some error handling in the xml parsing, and returning a warning.
- second, the error handling should try to detect files that cannot be opened (eg just feed the parser a nsdata, since the parser do not tell about missing / invalid files). like so:

`let data = NSData(contentsOfURL: url.filePathURL!) `
`//if data == nil then the file could not be opened`
` let parser =  NSXMLParser(data: NSData(contentsOfURL: url)!)`

Error:
Somewhere in the resolution of urls,   (called from  Main.swift L 25 ) appends part of the path twice. 
The error is inside of PBXObject.
The error is whenever a group is relative to the project rather than the group, which means that if i have a group which is relative to a project rather than the group, the code would simply append the path one more time, which creates this odd behavior.

Workaround: change all paths to be relative to the group.

Solution:
inside of XCProjectFile.Paths handle files that are relative to the project.

**Comment by mac-cain13** [comment]
Thanks for reporting this issue in such detail! Have to take a better look at it, but we'll fix it asap.

**Comment by Tvede-dk** [comment]
I will try to see if i cannot come up with a PR for a solution, but i cannot guarantee a time frame. :)

**Comment by Tvede-dk** [comment]
I have been able to create a solution for the problem, but that is inside of xcode.swift, and hence I do not know if the PR should be on this version of xcode.swift or the upstream ? 
(the code is at https://github.com/Tvede-dk/Xcode.swift) in the latest commit.

**Comment by mac-cain13** [comment]
If you create the PR against upstream I'll ask @tomlokhorst to merge it in and we then can update R.swift to the latest Xcode.swift.

Would this fix in Xcode.swift mean that your previous PR #192 doesn't have to be merged anymore? Or is that still needed?

**Comment by Tvede-dk** [comment]
#192 is just a recommendation, as it only creates warnings if parsing nib files fails (eg the file is invalid, or its not there ). if you take a nib and modify the xml and malform it, R.swift would just "silently" ignore that. in #192 that changed into a warning (along when the file cannot be opened). 

I have Made the PR. (https://github.com/tomlokhorst/Xcode.swift/pull/14)
