### ISSUE TITLE
R.swift 2.2.1 errors where strings have '\r\n'

### ISSUE THREAD

**Issue by arden** [mac-cain13/R.swift#202]
R.swift 2.2.1 also have some errors where Localizable.strings have '\r\n'.

when my Localizable.strings's str have a '\r\n', there have some problems as below.
Localizable.strings

"We need a couple things\r\nbefore you get started." = "We need a couple things\r\nbefore you get started.";

errors:
```swift
      /// Locales: en, zh-Hans
      static let showMe = StringResource(key: "Show me", tableName: "Localizable", locales: ["en", "zh-Hans"])
      /// en translation: We need a couple things
 before you get started.
      /// 
      /// Locales: en, zh-Hans
      static let weNeedACoupleThingsBeforeYouGetStarted = StringResource(key: "We need a couple things
\nbefore you get started.", tableName: "Localizable", locales: ["en", "zh-Hans"])

      /// en translation: We need a couple things
 before you get started.
      /// 
      /// Locales: en, zh-Hans
      static func weNeedACoupleThingsBeforeYouGetStarted(_: Void) -> String {
        return NSLocalizedString("We need a couple things
\nbefore you get started.", comment: "")
      }
```

**Comment by tomlokhorst** [comment]
There appears to be something wrong with the 2.2.1 release. We're looking into it.

**Comment by mac-cain13** [comment]
Derp, seems like I released the latest version incorrectly. Was using the new fastlane setup, probably a bug in there, I'll check how to fix it and release a correct version!

Sorry for the inconvenience!

**Comment by mac-cain13** [comment]
2.2.2 is now released (hopefully correct). Let me know if there are any problems with it!
