### ISSUE TITLE
It seems that storyboard reference placeholders are not supported?

### ISSUE THREAD

**Issue by aufflick** [mac-cain13/R.swift#205]
I moved a view controller into it's own storyboard, using the storyboard reference placeholder feature in IB, and get an error from rswift complaining that the destination view controller with id H1D-3d-bc4 is not found and might be corrupt, but that id is now a reference:

    <segue destination="H1D-3d-bc4" kind="show" identifier="editBook" id="12a-1S-h8d"/>
    ...
    <viewControllerPlaceholder storyboardName="Edit" id="H1D-3d-bc4" sceneMemberID="viewController"/>

**Comment by mac-cain13** [comment]
Sounds like something that should work, I'll take a look if I can see what's wrong!

**Comment by leguman73** [comment]
After updating R.swift I have exactly the same issue for the two reference placeholders of my project

**Comment by mac-cain13** [comment]
@leguman73 Thanks for reporting this. Is this only after upgrading? Did it work in an older version of R.swift? If so, do you know what version you where using before the problem appeared and what version you are using now?

**Comment by leguman73** [comment]
@mac-cain13 Before upgrading to the last version it was working for me on the 0.12.0

**Comment by tomlokhorst** [comment]
I've been unable to reproduce this. Does this error also occur when creating new storyboard references?
