### ISSUE TITLE
R.swift with Cocoapods 1.0.0

### ISSUE THREAD

**Issue by arden** [mac-cain13/R.swift#206]
Today, i'm update cocoapods to 1.0.0，but when i'm build,  some errors below:

/Users/arden/Library/Developer/Xcode/DerivedData/Tujiao-bafrgozogaxtokbvptvjthyelasx/Build/Intermediates/Tujiao.build/Debug-iphonesimulator/Tujiao.build/Script-FCC0209F1C9C65E900675599.sh: line 2: /R.swift/rswift: No such file or directory

**Comment by mac-cain13** [comment]
Could you doublecheck if R.swift is installed according to the [latest installation instructions](https://github.com/mac-cain13/R.swift#cocoapods-recommended)? 

I just started a new project with R.swift 2.2.2 and Cocoapods 1.0.0 and that worked just fine, so I think there is some legacy configuration that is causing you errors.

**Comment by mac-cain13** [comment]
Since it running fine with Cocoapods 1.0.0 on our projects I assume this is another hiccup. Let us know if you can't get it working.

**Comment by chimura** [comment]
I had similar issue today, trying to open a xcode project that has R.swift on its Podfile

I did a pod install, but I was getting the following error: R.swift/rswift: Permission denied

Then I went to the folder of that file and executed from the terminal:
chmod a+x rswift

It worked okay then
