### ISSUE TITLE
Another module

### ISSUE THREAD

**Issue by codwam** [mac-cain13/R.swift#207]
While I use another module like JSQMessagesViewController,
and reuse JSQMessagesCollectionViewCellIncoming.nib

It will be error:Use of undeclared type 'JSQMessagesCollectionViewCellIncoming'

**Comment by mac-cain13** [comment]
Would [_How to fix missing imports in the generated file?_](https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file) in the docs help you out here or is this another kind of problem?

**Comment by codwam** [comment]
Very thanks.
