### ISSUE TITLE
R.swift Carthage integration

### ISSUE THREAD

**Issue by josete89** [mac-cain13/R.swift#209]
Hi,

It's possible do a Carthage integration?

Thanks

**Comment by tomlokhorst** [comment]
Thanks for using R.swift! Carthage is an awesome tool, but not suitable for R.swift since we are a buildstep and not a dynamic library.

This was already discussed in some more detail in issue https://github.com/mac-cain13/R.swift/issues/42

**Comment by josete89** [comment]
thanks for the fast response 👍
