### ISSUE TITLE
Typed overload of dequeueReusableCellWithIdentifier

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#21]
Would be nice to write this:
`let x = tableView.dequeueReusableCellWithIdentifier(R.reuseIdentifier.rerouteBusinessHoursCell, forIndexPath: indexPath)`

instead of this:
`let x = tableView.dequeueReusableCellWithIdentifier(R.reuseIdentifier.rerouteBusinessHoursCell, forIndexPath: indexPath) as RerouteBusinessHoursCell`

**Comment by tomlokhorst** [comment]
I'm not sure you can do that. However you could definitely write something like:

```swift
let x = tableView.dequeueReuesableCellRerouteBusinessHours(forIndexPath: indexPath)
```

Although I'm not sure I like "polluting" UITableView with a bunch of extension methods.
Maybe put the functions on the generated code, something like:

```swift
let x = R.reuseIdentifier.dequeueRerouteBusinessHourCell(withTableView: tableView, forIndexPath: indexPath)
```

**Comment by tomlokhorst** [comment]
Now that I think about it, you can of course do what you originally wrote, using a phantom type:

```swift
struct ReuseIdentifier<T> : Printable {
  let value: String

  var description: String {
    return value
  }
}

extension UITableView {
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableCellWithIdentifier(identifier.value, forIndexPath: indexPath) as? T
  }
}
```

And by having R.swift generate:

```swift
struct R {
  struct reuseIdentifier {
    static var rerouteBusinessHoursCell: ReuseIdentifier<RerouteBusinessHoursCell> { return ReuseIdentifier(value: "RerouteBusinessHoursCell") }
  }
}
```

**Comment by mac-cain13** [comment]
Closing this, moving discussion to the pull request
