### ISSUE TITLE
Adding shell script to automatically download latest binary

### ISSUE THREAD

**Issue by zhigang1992** [mac-cain13/R.swift#211]
```bash
#!/usr/bin/env bash

[ -d "./.rswift" ] || mkdir "./.rswift"

if [ ! -f "./.rswift/rswift" ]; then
	pushd ./.rswift
	rm -rf *
	latest_version_url=$(curl -s https://api.github.com/repos/mac-cain13/R.swift/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
    curl -f -L  -o rswift.zip $latest_version_url
    unzip rswift.zip
    popd
fi

./.rswift/rswift $1
```

and save it as `rswift` in `$SRCROOT`, 
Then we can still use the same command in xcode.
expect that we don't have to track the binary in our project.

Not sure where to put this into repo, so I figure I just create an issue instead. 😄

**Comment by mac-cain13** [comment]
Thanks for the suggesting and sorry for my late reply.

Interesting way to download it right within the build process, good to have this here in the issue list for future reference. If someone asks for it I'll refer them to heren. Thanks for using R.swift!
