### ISSUE TITLE
Colors not added to R.generated.swift

### ISSUE THREAD

**Issue by kaunteya** [mac-cain13/R.swift#214]
I initially tried with linking clr file from `~/Library/Colors`. It didnt work.
I also tried enabling the `copy file to project` still does not work.
My `struct color` in generated file only contains `private init`
Is there anything I might be doing wrong?

**Comment by tomlokhorst** [comment]
The .clr file should be a member of the project target for it to be picked up by R.swift. Can you confirm that it is?

**Comment by kaunteya** [comment]
My bad. 
Its working when added to the target.

**Comment by tomlokhorst** [comment]
Yeah, sorry, the documentation isn't very clear on that. Glad it's working now!
