### ISSUE TITLE
InitialViewController

### ISSUE THREAD

**Issue by tomasharkema** [mac-cain13/R.swift#22]
Wil je mij de initiele viewController via R.swift aanbieden?

```
// <3 R.swift
let storyboard = R.storyboard.main.instance
let initialViewController = storyboard.instantiateInitialViewController() as UIViewController
```

**Comment by mac-cain13** [comment]
Zit nu in develop, volgende release hebben we dit. Je kan erbij met: `R.storyboard.main.initialViewController`
