### ISSUE TITLE
Complex plural string in stringsdict doesn't work

### ISSUE THREAD

**Issue by tomquist** [mac-cain13/R.swift#220]
The following .stringsdict file fails with a warning 
> Skipping string documentList.info.remaining in 'Localizable' (Base), not all format specifiers are consecutive

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>documentList.info.remaining</key>
        <dict>
            <key>NSStringLocalizedFormatKey</key>
            <string>%1$#@days@</string>
            <key>days</key>
            <dict>
                <key>NSStringFormatSpecTypeKey</key>
                <string>NSStringPluralRuleType</string>
                <key>NSStringFormatValueTypeKey</key>
                <string>ld</string>
                <key>zero</key>
                <string>%2$#@hours@ remaining</string>
                <key>one</key>
                <string>One day remaining</string>
                <key>other</key>
                <string>%ld days remaining</string>
            </dict>
            <key>hours</key>
            <dict>
                <key>NSStringFormatSpecTypeKey</key>
                <string>NSStringPluralRuleType</string>
                <key>NSStringFormatValueTypeKey</key>
                <string>ld</string>
                <key>zero</key>
                <string>%3$#@minutes@</string>
                <key>one</key>
                <string>One hour</string>
                <key>other</key>
                <string>%ld hours</string>
            </dict>
            <key>minutes</key>
            <dict>
                <key>NSStringFormatSpecTypeKey</key>
                <string>NSStringPluralRuleType</string>
                <key>NSStringFormatValueTypeKey</key>
                <string>ld</string>
                <key>zero</key>
                <string>%4$#@seconds@</string>
                <key>one</key>
                <string>One minute</string>
                <key>other</key>
                <string>%ld minutens</string>
            </dict>
            <key>seconds</key>
            <dict>
                <key>NSStringFormatSpecTypeKey</key>
                <string>NSStringPluralRuleType</string>
                <key>NSStringFormatValueTypeKey</key>
                <string>ld</string>
                <key>one</key>
                <string>%ld second</string>
                <key>other</key>
                <string>%ld seconds</string>
            </dict>
        </dict>
    </dict>
    </plist>

**Comment by tomlokhorst** [comment]
Does this work in all permutations if your using it without R.swift?

**Comment by tomlokhorst** [comment]
To elaborate:
R.swift doesn't allow this because `String(format:)` doesn't work with non-consecutive format specifiers in a stringsdict.

Using this example, the following expression:

```swift
String(format: NSLocalizedString("documentList.info.remaining", comment: ""), 0, 0, 1, 0)
```

Results in: `0 seconds remaining` instead of: `One minute`.

I think the stringsdict format is not intended to be used in such a way.
