### ISSUE TITLE
Additional root objects in a .xib causing reuse identifiers to be lost

### ISSUE THREAD

**Issue by mbernson** [mac-cain13/R.swift#223]
After adding more root objects (such as a gesture recognizer or custom object) to a .xib, R.swift will not add the reuse identifier to its generated struct anymore.

I've found two possible fixes. In `Nib.swift`, we could blacklist the objects:

```diff
diff --git a/R.swift/ResourceTypes/Nib.swift b/R.swift/ResourceTypes/Nib.swift
index 609c75d..c30d3b2 100644
--- a/R.swift/ResourceTypes/Nib.swift
+++ b/R.swift/ResourceTypes/Nib.swift
@@ -40,7 +40,10 @@ struct Nib: WhiteListedExtensionsResourceType, ReusableContainer {
 }
 
 private class NibParserDelegate: NSObject, NSXMLParserDelegate {
-  let ignoredRootViewElements = ["placeholder"]
+  let ignoredRootViewElements = [
+    "placeholder",
+    "customObject",
+    "tapGestureRecognizer",
+    // ...and many more :(
+  ]
   var rootViews: [Type] = []
   var reusables: [Reusable] = []
```

Otherwise, we could change or remove [this condition in `NibGenerator.swift`](https://github.com/mac-cain13/R.swift/blob/d49c00dfe93066d5ab61ab7ae92965857c98d60f/R.swift/Generators/NibGenerator.swift#L149):

```diff
diff --git a/R.swift/Generators/NibGenerator.swift b/R.swift/Generators/NibGenerator.swift
index 085c434..d222acb 100644
--- a/R.swift/Generators/NibGenerator.swift
+++ b/R.swift/Generators/NibGenerator.swift
@@ -146,7 +146,7 @@ struct NibGenerator: Generator {
     let reuseIdentifierProperties: [Property]
     let reuseProtocols: [Type]
     let reuseTypealiasses: [Typealias]
-    if let reusable = nib.reusables.first where nib.rootViews.count == 1 && nib.reusables.count == 1 {
+    if let reusable = nib.reusables.first where nib.rootViews.count >= nib.reusables.count {
       reuseIdentifierProperties = [Let(
         isStatic: false,
         name: "identifier",
```

What is the desired solution for this?
I'd like to fix this in a PR, but wanted to discuss it first. :)

**Comment by mac-cain13** [comment]
If I'm correct Apple takes the first root item in case of reusable things and uses that. So it will probably work if the reusable view is on top in IB and everything else is below, but I remember having read somewhere that it officially isn't supported. Though I can't remember where I read that atm...

So; I think we should proceed with caution if we are going to change this and make very sure it does always correctly work with multiple roots in any order. If that is indeed supported we could also support it but make sure we don't start supporting cases that would crash your app.

**Comment by mbernson** [comment]
You are correct. After testing my patch in an actual app, using a collectionviewcell with a gesture recognizer resulted in this exception:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'invalid nib registered for identifier (myCell) - nib must contain exactly one top level object which must be a UICollectionReusableView instance'`

Regular xibs are not affected by this, and storyboards (referenced issues) will need a different solution.
