### ISSUE TITLE
the segue trigger by UITapGestureRecognizer in storyboard has no R.segue.xxx

### ISSUE THREAD

**Issue by langyanduan** [mac-cain13/R.swift#224]
the segue trigger by `UITapGestureRecognizer` in storyboard does not generate `R.segue.xxx`

**Comment by tomlokhorst** [comment]
Sounds like this may be related to https://github.com/mac-cain13/R.swift/issues/223

**Comment by mac-cain13** [comment]
I guess this is indeed the same as #223 if not feel free to let us know.
