### ISSUE TITLE
Don't create nibs for private classes

### ISSUE THREAD

**Issue by Noobish1** [mac-cain13/R.swift#225]
We have some views that can be created from nibs but only within one file so they should be private, but when we do this R.swift throws build errors (`use of undeclared type`).

Is it possible to not create nibs for classes that are private?

**Comment by tomlokhorst** [comment]
Good idea, this would be a nice feature to have.

I think it might be a bit difficult to implement, though. At the moment we don't parse Swift code.
So I don't think its currently possible for R.swift to know what classes are private and which are internal/public. 

Does someone have any bright ideas for implementing this?

Related:
 - [Generate warnings when not using R.swift in code where you should](https://github.com/mac-cain13/R.swift/issues/30)
 - [IBAction and IBOutlet validation](https://github.com/mac-cain13/R.swift/issues/146)

**Comment by mac-cain13** [comment]
I'll close this one in favor of #276. I think that will resolve this one as well once implemented.
