### ISSUE TITLE
Use of undeclared type - using custom Segue classes from other libraries

### ISSUE THREAD

**Issue by adhanji** [mac-cain13/R.swift#226]
Hi there,

I was wondering if there is a way to use R.swift in conjunction with using an external library that provides a custom Segue type. When I set segues in my storyboard to that custom type and try to build the project, the R.generated.swift file has errors on "could not infer type" and "use of undeclared type".

I look forward to a reply, and thank you for putting in such fantastic work on this library - I love the concept and I think this is how things should be handled natively :)

**Comment by tomlokhorst** [comment]
I haven't tried this for segues, but does it work to [set the module explicitly in the storyboard](https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file)?

**Comment by adhanji** [comment]
Ah, that fixed it. Thank you so much for the quick response!
