### ISSUE TITLE
R.swift with Cocoapods 1.0.0 dosen't work

### ISSUE THREAD

**Issue by arden** [mac-cain13/R.swift#228]
when i'm use R.swift with Cocoapods 1.0.0，it's dosen't work. some errors below:

/Users/arden/Library/Developer/Xcode/DerivedData/Tujiao-bafrgozogaxtokbvptvjthyelasx/Build/Intermediates/Tujiao.build/Debug-iphonesimulator/Tujiao.build/Script-FC2117771D0D8897004D8522.sh: line 2: /R.swift/rswift: No such file or directory

and  R.swift is installed according to the latest installation instructions.

**Comment by arden** [comment]
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Tujiao' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tujiao
  # 将图片资源自动转换成对象调用
  pod 'R.swift'

  target 'TujiaoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'TujiaoUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end

So....
Because pod 'R.swift' must in a target

**Comment by tomlokhorst** [comment]
This appears to be the same issue as https://github.com/mac-cain13/R.swift/issues/227

Do you know if your `project.pbxproj` is completely correct?
