### ISSUE TITLE
Customize generated `R.generated.swift` file path

### ISSUE THREAD

**Issue by honghaoz** [mac-cain13/R.swift#229]
Currently `rswift` will generate `R.generated.swift` in root of the project directory.

However, I may want to organize this file into a `Utilities` directory. I wonder can we add a parameter for specifying generated file path? 

Thx.

**Comment by tomlokhorst** [comment]
You can specify the destination directory of the generated file in the build phase.

For your example (assuming you're using CocoaPods):

```bash
"$PODS_ROOT/R.swift/rswift" "$SRCROOT/Utilities"
```
