### ISSUE TITLE
Specify certain type of resources that R.swift file generated for

### ISSUE THREAD

**Issue by mbesnili** [mac-cain13/R.swift#233]
Hello, 

Is there any way to specify type of resources that R.swift file generated for ? I'm looking for something like configure me R.swift for only images and localization resources. 

Thank you for your help.

**Comment by mac-cain13** [comment]
At the moment we don't have that feature. Would be possible to add it in a future version but I'm not sure how valuable it is for users.

Could you maybe explain a little bit about why generating all the structs is a problem for you? You could just ignore the things that you don't need.

**Comment by mbesnili** [comment]
Well, i'm trying to integrate R.swift into a project that has a objective-c code base. Now, i can successfully create R.swift but it's displaying too many errors while trying to create segue and nib as they are objective-c files. That's why i want to specify build configuration for R.swift to prevent these kinds of errors. Do you have any idea how i can get rid of 'Use of undeclared type _classname_' errors ?

**Comment by tomlokhorst** [comment]
Does it work if you [fix the missing imports in the generated file](https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file)?

**Comment by rubensbubens** [comment]
For me the reason to specify type of resources that R.swift file generated for is compile time increasing exponentially on a large projects and each time I wanna build/archive it's incredibly annoying to wait so long while script doing it's job. 

In one of the projects someone attached the script before I participate it and there's tons of images, so such a script make sense to use but it's also generating code for every kind of supported resources which no one needs and it's only waste of time. So would be very nice if there will be a feature to specify types.

**Comment by tomlokhorst** [comment]
You can run only specific generators.
For example, to only generate R.image

https://github.com/mac-cain13/R.swift/blob/master/Documentation/Ignoring.md#only-run-specific-generators-exclude-rsomething

**Comment by rubensbubens** [comment]
@tomlokhorst oh great! couldn't find this page.. thanks! :))
