### ISSUE TITLE
Skipping 3 resource files because symbol 'aboutHtml' would be generated for all of these files

### ISSUE THREAD

**Issue by Blackjacx** [mac-cain13/R.swift#236]
Hey guys,

I've seen this issue before but it is not solved in the current version (2.4.0) of R.swift. We have the file About.html localized in French, English and German. They reside in the respective lproj folders like all other localized files but the warning still appears. Any suggestions?

**Comment by tomlokhorst** [comment]
Support for [localized resources is a missing feature](https://github.com/mac-cain13/R.swift/issues/155).

Thinking about this, I think simple files in `R.file` are simpler to fix than the more complicated storyboard with possibly conflicting segues and the like. So we can probably fix localised files first, before doing storyboards and nibs.
