### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by kaunteya** [mac-cain13/R.swift#237]
Are there any plans to support macOS in future?

**Comment by tomlokhorst** [comment]
Yes, this is a feature we'd like to have in the future.
However, no one is currently working on it.

See also: https://github.com/mac-cain13/R.swift/issues/102

**Comment by innoreq** [comment]
Do you have an idea what should have to be done for macOS?

**Comment by tomlokhorst** [comment]
No, I haven't looked into macOS support.
