### ISSUE TITLE
An interesting bug....If a png named as default.png

### ISSUE THREAD

**Issue by Onetaway** [mac-cain13/R.swift#243]
I have a png called `default.png`. And in use it looks like 
<img width="592" alt="today at 11 24 13" src="https://cloud.githubusercontent.com/assets/3251826/17236867/07110030-557f-11e6-9865-e7b206bce782.png">

So, the compiler will angry......  Because `default` is a key word in Swift....This should be enhanced by R.swift.

**Comment by callmewhy** [comment]
default is a keyword in Swift.

**Comment by Onetaway** [comment]
Yep, so I think R.swift should rename or something else to prevent such thing happen. Because a png's name could be every thing...

**Comment by Limon-O-O** [comment]
Workaround: ``` `default`() ```

**Comment by tomlokhorst** [comment]
R.swift will escape any Swift keywords, if they happen to occur in the generated code. See the code in `R.generated.swift`.

Unfortunately, Xcode autocomplete doesn't correctly auto complete by escaping keywords, so you'll have to write that manually.

Indeed, the intended way of referring to something like this is with ``` R.image.`default`() ```
