### ISSUE TITLE
Add `public` modifier, to support dynamic frameworks

### ISSUE THREAD

**Issue by DanielAsher** [mac-cain13/R.swift#245]
As I understand it, R.swift can only be used in a project containing a target app, and doesn't support use in dynamic frameworks linked to a target app.

If I'm correct I believe this would be usefully described in the readme and I would be prepared to create a PR for this.

Long term: perhaps a move to using an `R` protocol and protocol extensions, or other strategies could be employed in supporting this feature.

Thanks.

**Comment by tomlokhorst** [comment]
You can use R.swift in multiple projects, by setting up a build phase for each project.

In my current setup, I have an iOS app with a R.generated.swift file. That project links to a different project that is a separate Cocoa Touch Framework.
The framework has its own R.generated.swift file, for its own resources.

Is this what you're referring to, or do you mean something else?

**Comment by tomlokhorst** [comment]
Although I can't use the library's resources from the app, because the `R` struct is internal.

If the generated code would be public, the app could simply refer to `OtherFramework.R.image.someImage()`

**Comment by DanielAsher** [comment]
@tomlokhorst : thanks for this reply - it is what I mean. 

I have experimented with a modified VIPER architecture with each part built in its own dynamic framework and all referenced by a seperate top-level target and project app. View/ViewController/Main.storyboard is in an AppnameView dynamic framework that is referenced by an seperate AppnameApp project. Setting the `rootViewController` in the AppDelegate becomes impossible using the Rswift `R` struct. Having the `R` struct made fully public would allow loading dynamic framework resources in the app and in playgrounds.

I do need to think a bit more about this, but perhaps making the R struct public may be all that is needed.

**Comment by tomlokhorst** [comment]
To play around with this, you can use this as a build phase. It replaces strings to add public modifiers:

```bash
"$PODS_ROOT/R.swift/rswift" "$SRCROOT/SomeProject"
sed -i -e 's/struct /public struct /g' "$SRCROOT/SomeProject/R.generated.swift"
sed -i -e 's/func /public func /g' "$SRCROOT/SomeProject/R.generated.swift"
sed -i -e 's/static let /static public let /g' "$SRCROOT/SomeProject/R.generated.swift"
```

If this works, it can be added it to the code generator. We'll have to investigate to see if there are unintended side effects for changing this previous internal struct to be public.

**Comment by DanielAsher** [comment]
@tomlokhorst thanks for this workaround. The script is ingenious! It didn't quite work first time requiring the following (in the context of a Carthage + manual installation):
```
"$SRCROOT/rswift" "$SRCROOT"
sed -i -e 's/private //g' "$SRCROOT/R.generated.swift" 
sed -i -e 's/struct /public struct /g' "$SRCROOT/R.generated.swift"
sed -i -e 's/func /public func /g' "$SRCROOT/R.generated.swift"
sed -i -e 's/static let /static public let /g' "$SRCROOT/R.generated.swift"
sed -i -e 's/let bundle /public let bundle /g' "$SRCROOT/R.generated.swift"
sed -i -e 's/let name /public let name /g' "$SRCROOT/R.generated.swift"
```

I'll play around with this and report back.

**Comment by DanielAsher** [comment]
Allowing `public` access to the `R` struct looks like providing the necessary support for this use case. The script I'm using, however, does not scale, as I have to add individual items to the `storyboard` struct (e.g. `sed -i -e 's/let storyPageController /public let storyPageController /g' "$SRCROOT/R.generated.swift"`). This is because of the impossibility of replacing `let` with `public let` globally.
Adding this facility to the code generator would be awesome!

**Comment by tomlokhorst** [comment]
Note to self:
When we add this feature, we need to double check if we correctly load all resources via the hosting bundle.

For example, before https://github.com/mac-cain13/R.swift/pull/238 we didn't do that for Strings, maybe there's other resources that also rely on the default bundle.

**Comment by mac-cain13** [comment]
I decided to start out with everything in the R struct internal, because it didn't feel right to make it public by default. The this is that if you create a library with a public resource you can't change any resource without potentially breaking depending projects. That didn't feel as a correct default.

That said, I think your use case @DanielAsher is a valid one, but I'm not sure if it is so common that it should change the default visibility of resources. I'm interested in what you all think about this;

Should the default visibility be changed to public or should this be some kind of setting? Or is there another option that we could explore?

**Comment by DanielAsher** [comment]
I strongly believe that refactoring to use dynamic frameworks and the use
of playgrounds for REPL-based development are powerful techniques and
growing trends.

Could an alternative could be a command-line flag to `Rswift`, perhaps
`--public`? This would allow for the default `internal` to be maintained,
while allowing for these use cases.

**Comment by mac-cain13** [comment]
I agree that dynamic frameworks are the way to go, the only thing is not every dynamic framework is going to expose their resources to the outside world. :)

A `--public` flag could be an option. That keeps the default on internal. That is nice, it would be even nicer if we could come up with a solution that gives you control on what resources are public and what are internal. Not sure how that would look like, maybe a name convention or something else I'm not yet thinking about.

**Comment by mac-cain13** [comment]
I've merged this feature into master and it will be available in the next R.swift release. Thanks for reporting your needs and thinking with us.

You can specify the access level you want the `R` struct and its nested structs/properties/methods generated on by passing the `rswift` binary the `--accessLevel public` flag. (You can also specify `internal`, `fileprivate` or `private`.)

**Comment by DanielAsher** [comment]
very much looking forward to this!
