### ISSUE TITLE
Can it using in Mixed Project?

### ISSUE THREAD

**Issue by lacklock** [mac-cain13/R.swift#247]
my project is mixed by OC.
so i wonder if this lib can using in the project?

**Comment by tomlokhorst** [comment]
I don't have any experience with using R.swift in a mixed Objective-C/Swift project.

It's not something we've tested before. It may work for the Swift specific parts.
If you want to try it out, please do let us know the results!

See also: https://github.com/mac-cain13/R.swift/issues/241

**Comment by tomlokhorst** [comment]
I've renamed issue https://github.com/mac-cain13/R.swift/issues/241 so we can continue discussion over there.
