### ISSUE TITLE
Include segues sourced from views attached to a storyboard scene

### ISSUE THREAD

**Issue by nolanw** [mac-cain13/R.swift#248]
It seems that R.swift doesn't see segues whose source is a view attached to a storyboard scene. For example, in this magnificent storyboard:
<img width="630" alt="lil-storyboard" src="https://cloud.githubusercontent.com/assets/177228/17440354/9a4e60ee-5b02-11e6-8af3-a7cf3db86461.png">
One of those segues is from the button directly in the view controller, with the identifier "Direct". R.swift generates code for that. The other segue is from the button attached to the view controller, with the identifier "Attached", that R.swift does not generate code for.

I think R.swift should generate code for both!

Here's a sample project I made to illustrate the issue, if it's helpful: [AttachedViewSegueTest.zip](https://github.com/mac-cain13/R.swift/files/403996/AttachedViewSegueTest.zip)

**Comment by tomlokhorst** [comment]
This is similar to https://github.com/mac-cain13/R.swift/issues/224.

Pull request https://github.com/mac-cain13/R.swift/pull/221 fixes this, although I'm not sure if that's the correct way of implementing this.

**Comment by nolanw** [comment]
Looks similar indeed, I managed not to see those when looking through the existing issues. I don't really understand the referenced PR but if it works in this case then I'm on board!

**Comment by tomlokhorst** [comment]
This should be fixed in the latest 2.5.0 release
