### ISSUE TITLE
Enable/disable certain features, to speed up generation time

### ISSUE THREAD

**Issue by CodeEagle** [mac-cain13/R.swift#250]
Hi there,
   Just wanna ask if it's possible to just enable like Image compile, not other resource

**Comment by tomlokhorst** [comment]
It's currently not possible to enable/disable specific features.

Could you explain why you want to disable certain features? You can just ignore the generated code for features you don't use.

Related: https://github.com/mac-cain13/R.swift/issues/233

**Comment by CodeEagle** [comment]
because I just using R.image in my project, every time archive R.swift take certain time, may be it can optimize a bit.

**Comment by mac-cain13** [comment]
I'll close this one in favor of #276. I think that will resolve this one as well once implemented.
