### ISSUE TITLE
The "My app colors.clr" is also in file struct?

### ISSUE THREAD

**Issue by wenzhaot** [mac-cain13/R.swift#257]
The "My app colors.clr" is also in file struct?

**Comment by tomlokhorst** [comment]
Yes, color palette files in R.swift are [a bit of a hack](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Colors.md).

They must be included as files in the target to be correctly picked up by R.swift. That also means there being shipped as runtime resource in the app.

It's weird, but it sort of works... Do you have a specific problem with the clr file shipping with the app as a resource?

**Comment by wenzhaot** [comment]
OK, thanks
