### ISSUE TITLE
Download as zip file - ResourceApp should perhaps compile out of the box

### ISSUE THREAD

**Issue by neoneye** [mac-cain13/R.swift#258]
Cool project.

I just downloaded this repository as a zip file, however it doesn't compile.

I opened the `R.swift.xcworkspace`, but the `ResourceApp` target cannot compile.

I tried running `pod install` in the root dir, but no luck.

I'm using Xcode 7.3.1

**Comment by tomlokhorst** [comment]
Thanks for your comments!

R.swift (and the additional [library](https://github.com/mac-cain13/R.swift.Library)) is currently written in Swift 2.3, requiring Xcode 8.

If you just want to use R.swift, you can follow the [installation instructions](https://github.com/mac-cain13/R.swift#installation) for either cocoapods, or manual installation. The [latest](https://github.com/mac-cain13/R.swift/releases/tag/v2.5.0) stable release is compatible with Swift 2.2 (Xcode 7) and Swift 2.3 (Xcode 8).

If you want to contribute to R.swift by submitting a pull request, you'll need Xcode 8.
