### ISSUE TITLE
Fail to build in swift 2.3

### ISSUE THREAD

**Issue by wenzhaot** [mac-cain13/R.swift#261]
My project is using swift 2.3, when I complete pod install，I get some errors
<img width="272" alt="screen shot 2016-09-18 at 12 28 39" src="https://cloud.githubusercontent.com/assets/1284393/18612894/76fbaa3c-7d9b-11e6-9c74-2f9d7a93562b.png">

**Comment by tomlokhorst** [comment]
What version of R.swift are you using?

The latest release (3.0.0) is only compatible with Swift 3.
The 2.* versions of R.swift are compatible with Swift 2.3. 

See the migration guide: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md

**Comment by wenzhaot** [comment]
Ok, thanks
