### ISSUE TITLE
Possible name clashes and unexpected behaviour

### ISSUE THREAD

**Issue by tomquist** [mac-cain13/R.swift#262]
We had a name clash with types contained within the Rswift namespace. Usually this is no problem since Swift has namespaces, however, ``R.generated.swift`` usually lies within the namespace of the App so when the compiler resolves types within ``R.generated.swift`` it prefers the types defined in the app namespace.
In our case we had a protocol which was called ``ReuseIdentifierType`` which is also present in Rswift and had very similar (but still slightly different) implementation. The result was that we were unable to call methods like ``tableView.register(R.nib.myNib)`` since the generated type ``_R.nib._MyNib`` implemented the protocol of the app instead of the one of R.swift. It took us quite a while to find the reason.

The solution would be to use fully qualified names within ``R.generated.swift``.

**Comment by mac-cain13** [comment]
Thanks for reporting this issue! I can see how this is hard to figure out. :)

Using fully qualified names for the types from the Rswift package sounds like a good idea. Not yet sure if we should also do this for types in packages that we discover from for example storyboards etc.

**Comment by mac-cain13** [comment]
This is now resolved on master and will be in the next release. Thanks for bringing this up!
