### ISSUE TITLE
Add constraints with identifiers to the R file

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#27]
@sdevos mentioned that identifiers are not really made for lookups, so should think about whether this is really a good idea.

**Comment by ntnmrndn** [comment]
What's the additional value compare to IBOutlet ?

**Comment by mac-cain13** [comment]
Yeah, that would be minimal. IBOutlet or just keeping the reference in code if you create it there would be preferable. Identifiers would be more of a debugging thing.

**Comment by mac-cain13** [comment]
I'll close this one, unless someone can make a good case for it. :) Too much downsides and no real win.
