### ISSUE TITLE
Add ability to let R.swift skip certain files

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#276]
It would be nice to have the ability to make R.swift skip certain files completely. This would make it easy to work around certain edge cases/issues or speed up generation times if needed.

This would be a workaround/solution for these issues:
- [Enable/disable certain features, to speed up generation time](https://github.com/mac-cain13/R.swift/issues/250)
- [Don't create nibs for private classes](https://github.com/mac-cain13/R.swift/issues/225)
- [Nest class with @objc renaming](https://github.com/mac-cain13/R.swift/issues/265)

Nicest solution would be a CLI flag that you can pass the path to a gitignore style file that describes what files should be ignored. Depending on how hard that would be we also could scale down to a plain list of files to ignore.

**Comment by shiraji** [comment]
If no one work on this issue, can I contribute this project?

**Comment by mac-cain13** [comment]
@shiraji I did a little bit of fiddling around for this feature on the [feature/skip-file](https://github.com/mac-cain13/R.swift/tree/feature/skip-file) branch, but I do not have the time to finish it atm. So you are very welcome to work on this issue, either building on top of that branch or starting from scratch.

So I think of this feature as a CLI flag that you can pass the path to a gitignore style file, then we would use something like file globbing or a simple version of globbing to discover the files we have to skip. I would like to filter out the files as early as possible in the process so that it has as little impact on the code as possible.

Please let me know when you start working on that (feel free to open a "work in progress" pull request for example) so that we won't do any duplicate work.

Thanks for using and contributing to R.swift!

**Comment by shiraji** [comment]
Thanks! Actually, I have already started working on this but yours seems better. I will use your commit to complete this issue. However, feel free to finish up yours if i am too slow to do this.

**Comment by mac-cain13** [comment]
This is merged to master and will be in the next release.
