### ISSUE TITLE
Custom segue warning shows when deployment target > iOS 8

### ISSUE THREAD

**Issue by AttilaTheFun** [mac-cain13/R.swift#278]
I'm working on an application that targets iOS 9 and uses R.swift
I'm getting warnings from the swift script from [this line]( https://github.com/mac-cain13/R.swift/blob/master/R.swift/ResourceTypes/Storyboard.swift):
`warn("Set the segue of class \(customType) with identifier '\(attributeDict["identifier"] ?? "-no identifier-")' to type custom, using segue subclasses with other types can cause crashes on iOS 8 and lower.")`
Is it possible to only show this error when being run on a project targeting iOS versions before iOS 9?
If not is there a way I can suppress this warning without recompiling the rswift binary?

**Comment by mac-cain13** [comment]
Thanks for using R.swift. At this moment it's not possible to suppress this warning. Note that, even when you're building iOS 9 only, you should set the type of your segue to `custom` if you're using a custom segue subclass. It may not crash anymore, but it's still a conflicting configuration.

So I would suggest fixing this in your storyboard, but you are correct that this warning was introduced to prevent crashes and R.swift doesn't warn about other things. In a next release maybe we could only emit this warning when building for iOS 8, but that requires a code change in the binary. So for now I think the easiest workaround is to change the type of those segues to `custom` in the storyboard.

**Comment by AttilaTheFun** [comment]
@mac-cain13 thanks for the tip!
