### ISSUE TITLE
how to disable R.swift generate R.image in Xcode8?

### ISSUE THREAD

**Issue by jl322137** [mac-cain13/R.swift#280]
in Xcode8 ,  we can create a image use a strong type generate by xcode, so i think we did not need R.image any more

**Comment by tomlokhorst** [comment]
It's currently not possible to disable certain features, there's [an issue](https://github.com/mac-cain13/R.swift/issues/276) for that.

Note that the image literals in Xcode 8 aren't a full replacement for `R.image.*`.

When deleting or renaming image files, R.swift will cause compile errors at the locations where those images are used. In contrast, image literals won't cause a compile-time error, but will instead crash the app at runtime on a forced unwrap of nil.
