### ISSUE TITLE
the swift3 specific version

### ISSUE THREAD

**Issue by BMR731** [mac-cain13/R.swift#282]

**Comment by tomlokhorst** [comment]
The current 3.x versions of R.swift are fully compatible with Swift 3.
If you still need Swift 2.3, use the 2.x releases of R.swift. The latest being [R.swift 2.5](https://github.com/mac-cain13/R.swift/releases/tag/v2.5.0).

See also our [migration guide](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md).
