### ISSUE TITLE
How to use R.swift in Dynamic Framework?

### ISSUE THREAD

**Issue by saltwat5r** [mac-cain13/R.swift#285]
I have the following error while using in Dynamic Framework:
`Use of unresolved identifier 'R'`

**Comment by tomlokhorst** [comment]
You can use R.swift in multiple projects, by setting up a build phase for each project.

To call the `R` struct from a different framework, you'll need to instruct R.swift to generate public structs. This can be done by passing the `rswift` binary the `--accessLevel public` flag.

See also: https://github.com/mac-cain13/R.swift/issues/245

Does this answer your question?

**Comment by saltwat5r** [comment]
Thanks for your answer! Problem solved. Finally I've found that there was a problem, because my framework is distributed as a Pod and I forgot to add R file directory to resources in my Podspec.
Now everything is working correctly.

**Comment by tomlokhorst** [comment]
Good to hear your problem is solved!
