### ISSUE TITLE
Typealias error when --accessLevel public

### ISSUE THREAD

**Issue by dunada** [mac-cain13/R.swift#286]
When I try to use R in a framework with the option --accessLevel public. I'm receiving the error:
Typealias must be declared public because it matches a requirement in public protocol
Workaround:
Add the line in R.Swift Script:
sed -i -e 's/  typealias /  public typealias /g' "${SRCROOT}/R.generated.swift"

**Comment by mac-cain13** [comment]
Thanks for reporting this! I've just pushed a commit so that the access level is respected by the typealiases, this will be in the next release.
