### ISSUE TITLE
Objective-C generation

### ISSUE THREAD

**Issue by ntnmrndn** [mac-cain13/R.swift#287]
Hi, 

Yes I know it the project has swift in the name.
Yes I know we can use the project provided we include the right things

But... the swift library overhead (8mo) is just too much for the project I'm working on. 
Since R.swift is really awesome, I'd like to use it anyway.

Is an optional objective-c code generation something you would consider ?

**Comment by mac-cain13** [comment]
Thanks for your idea. I don't consider ObjC code generation in the scope of this project. It would make things way more complex and I feel the way UIKit works by default is quite close to the nature of ObjC. It falls back to `nil` silently in most places.

You could look at something like https://github.com/ksoichiro/rdotm if you want R.swift like behaviour for ObjC projects.
