### ISSUE TITLE
Shuffled folders around, R.generated.swift not updating

### ISSUE THREAD

**Issue by xiaosongshu** [mac-cain13/R.swift#289]
Moved some of my files around around,

ie.

Project/Profile/photoCell.xib
Project/Profile/photoCell.swift

to

Project/Profile/Views/photoCell.xib
Project/Profile/Views/photoCell.swift

But R.generated.swift doesn't seem to be picking up the xib file (now just in a different folder structure). I've made sure both xib and swift file are added to Compile Sources and Copy Bundle Resources, but 

struct nib {
...

doesn't seem to be updating in R.generated.swift (I do not have a `static let photoCell = ...` anymore when I used to

Am I missing something silly here?

**Comment by mac-cain13** [comment]
Did you also move the `R.generated.swift` to another folder? If you did R.swift is probably generating the file at the wrong location. You have to adjust the path in the build phase to the new location if you did.

Also; Does the file correctly work in Xcode? R.swift looks at your Xcode project so if the project doesn't have the file in the target you are generating for it will also skip the file.

**Comment by xiaosongshu** [comment]
Looks like it was because I didn't link the folders correctly after renaming name in Xcode. Thanks!
