### ISSUE TITLE
Support specifying the bundle for localized strings

### ISSUE THREAD

**Issue by vatrif** [mac-cain13/R.swift#292]
Currently, there seems to be no way to get a localized string in a language different from the `hostingBundle`. 

It would come in handy to be able to specify the bundle when retrieving a localized string, for example:
`R.string.localizable.cancel(bundle: languageBundle)`

If someone is aware of any other way of changing the language on the fly (by retrieving localized strings from a different bundle), I would really appreciate hearing about it.

**Comment by mac-cain13** [comment]
I remember that @tomlokhorst did think about this while implementing, but I'm not sure anymore what his opinion was on this.

@tomlokhorst could you take a look at this?

**Comment by tomlokhorst** [comment]
@vatrif I'm unsure what you mean by using a different bundle.
Do you mean the ability to get a string in a different language from the default one? Or something else?

See also: https://github.com/mac-cain13/R.swift/issues/219

**Comment by vatrif** [comment]
@tomlokhorst The issue you linked is exactly the solution I'm looking for.

**Comment by tomlokhorst** [comment]
Great, then I'll close this one as a duplicate.

I do plan on working on the specific language issue, since I do need the feature myself. But I'm not sure when.
