### ISSUE TITLE
`R.generated.swift` should contain newline at the end of file

### ISSUE THREAD

**Issue by peterprokop** [mac-cain13/R.swift#298]
Otherwise it violates `trailing_newline` SwiftLint rule (and also not nice and fluffy)

**Comment by mbernson** [comment]
In my opinion, generated code doesn't have to be checked by SwifLint. You can exclude it in `.swiftlint.yml` like so:

```yaml
excluded:
  - MyApp/Resources/R.generated.swift
```

**Comment by peterprokop** [comment]
Yes, but it's still nice to have newline at the end of file - otherwise github complains!

**Comment by mac-cain13** [comment]
Agreed that you shouldn't lint generated code, but still a newline at the end would be nice. :)
Will fix this in a next release.
