### ISSUE TITLE
What are required/optional parameters when rswift is run from console?

### ISSUE THREAD

**Issue by ildarsharafutdinov** [mac-cain13/R.swift#299]
With src root:
```
./Pods/R.swift/rswift App
error: [R.swift] Missing option: [-p|--xcodeproj] requires 1 parameters
```

With project name and src root
```
./Pods/R.swift/rswift -p App.xcodeproj/ App
error: [R.swift] Missing option: [-t|--target] requires 1 parameters
```

The same story when I pass project, target and src root.

Does rswift require all the params in the '-h' list?

**Comment by mac-cain13** [comment]
It needs quite some information if you run it by hand, normally this information is provided by Xcode when it runs the binary from within the build proces.

R.swift needs al these options to run:
- sdkRoot
- sourceRoot
- developerDir
- buildProductsDir
- productModuleName
- bundleIdentifier
- target
- xcodeproj

Source:  https://github.com/mac-cain13/R.swift/blob/master/R.swift/input.swift#L73-L112
