### ISSUE TITLE
pod install R.swift error

### ISSUE THREAD

**Issue by nyl340827** [mac-cain13/R.swift#300]
[!] Error installing R.swift
[!] /usr/bin/curl -f -L -o /var/folders/pf/zq_c86_x2h515v9fmyvx8qlr0000gn/T/d20170222-17833-188kaw7/file.zip https://github.com/mac-cain13/R.swift/releases/download/v3.2.0/rswift-3.2.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   593    0   593    0     0     68      0 --:--:--  0:00:08 --:--:--   143
  0     0    0     0    0     0      0      0 --:--:--  0:00:46 --:--:--     0
curl: (52) Empty reply from server

**Comment by mac-cain13** [comment]
Seems to work from here, maybe a temporary Github server hiccup?
