### ISSUE TITLE
Consider generating an `all` (static) property on R nested types

### ISSUE THREAD

**Issue by DanielAsher** [mac-cain13/R.swift#305]
Hi,

First, thanks for a great framework! I've been using this for a while, and the `--public` flag has allowed me to use this in many dynamic frameworks too :)

Strongly-typed resource references are great, but don't allow us to iterate over our resources. I register my custom fonts (required in a dynamic framework) using [this](http://stackoverflow.com/questions/30507905/xcode-using-custom-fonts-inside-dynamic-framework) method. I started creating an enum listing my fonts and their bundle urls manually - cringing at maintenance burden and release risk - when I remembered that `R.swift` already did this, all compile-time checked and with zero maintenance - but there is no way to iterate over `R` classes. Swift reflection doesn't support `static var`s at this time, so...

Would it be useful to add an `all` property to `R`'s data structure to allow iterating over `file` `font` etc.

thanks again,

Daniel

**Comment by DanielAsher** [comment]
Addendum - this is a common boiler-plate pattern in swift (pre swift 7 that is :)
```
enum State {
case on, off
static var all : [State] { return [.on, .off] }
}
```

**Comment by tomlokhorst** [comment]
Sounds like a good idea for a feature!

We'll need to come up with something for when a resource already exists that is named `all`.

**Comment by mac-cain13** [comment]
Options when a resource named `all` is also in the project:
- Don't generate the `all` propery, but only the resource (type changes so code will break)
- Warn and don't generate the resource reference
- Rename `all` to something a resourcename can never be, like `_all` for example
- Maybe there is some Iterable/Sequence protocol that we can implement so you can so something like `for image in R.image()`?

**Comment by DanielAsher** [comment]
I like option 4. If `R.image()` et al are safe why not simple return an
array?

**Comment by tomlokhorst** [comment]
If we change from what we currently generate:

```swift
struct R {
  struct image {
    static let image1 = ImageResource()
  }
}
```

to generating:

```swift
struct R {
  static let image = _R.Image()
}

struct _R {
  struct Image : Sequence {
    let image1 = ImageResource()
  }
}
```

We don't need the `R.image()` function and can loop over `R.image` itself.

**Comment by mac-cain13** [comment]
@tomlokhorst I think this issue is a nice candidate to pick up for the new 4.0 major release. Since then we are allowed to break here and there if needed. Do you agree?

**Comment by mac-cain13** [comment]
Looking into this I realized that we also have nested structs, for example for segues:

```swift
struct R {
  struct segue {
    struct firstViewController {
      static let toAVPlayerController: Rswift.StoryboardSegueIdentifier = //...
    }
  }
}
```

This extra level of nesting should also be represented in `_R`:

```swift
struct R {
  static let segue = _R.Segue()
}

struct _R {
  struct Segue : Sequence {
    let firstViewController = FirstViewController()

    struct FirstViewController: Sequence {
      let toAVPlayerController: Rswift.StoryboardSegueIdentifier = //...
    }
  }
}
```

---

I also think that a downside of this change could be that the lazy loading we get from the static properties is gone. We should consider making the properties of these struct instances lazy, so they won't be initialised all at once when you touch a single segue for example.

**Comment by DanielAsher** [comment]
Closing as [Sourcery](https://github.com/krzysztofzablocki/Sourcery) is a more complete solution.
