### ISSUE TITLE
Proposal: generate UIVIewController's Identity

### ISSUE THREAD

**Issue by pffan91** [mac-cain13/R.swift#308]
Will be good to have strong typed Storyboard IDs Identity for our view controllers:
<img width="406" alt="viewcontrolleridentity" src="https://cloud.githubusercontent.com/assets/5795989/24075183/7eb22392-0c38-11e7-93d6-26fc10cbc76e.png">

**Comment by tomlokhorst** [comment]
I'm not quite sure what you mean.

With a storyboard called Main.storyboard, you can instantiate a view controller like so:
`R.storyboard.main.registrationViewController()`

Is this what you're asking for?

**Comment by pffan91** [comment]
Oh, yes, this is what I mean! Thank you for explanation, I am newbie for R.swift
