### ISSUE TITLE
.clr generated from Zeplin not translated well in XCode

### ISSUE THREAD

**Issue by YotamGolomb** [mac-cain13/R.swift#309]
When defining colors in Zeplin and exporting it to .clr file , the R.swift isn't creating the right colors.
e.g : i have created a color from RGB 77 217 180 which is 4DD9B4. it was translated to 43D4A5

**Comment by tomlokhorst** [comment]
This may be related to https://github.com/mac-cain13/R.swift/issues/301

R.swift currently always assumes the colors defined in a .clr are in the sRGB color profile. 
If the .clr file is in a different color profile, R.swift converts the color incorrectly. This is a bug.

Do you know in what color profile the .clr file is that was exported from Zeplin?

**Comment by YotamGolomb** [comment]
All i know is that the Color Representation of the project is automatic. As for the exporting option , it doesn't allow me to choose a profile

**Comment by mac-cain13** [comment]
I've merged the PR that checks the colorspace so the next release of R.swift should at least warn you if the color space is not correct. Hope that at least makes this problem clearer.

@YotamGolomb could you share a problematic clr file so we can check if the color profile in your clr is indeed the problem?

**Comment by mac-cain13** [comment]
Also; Support for P3 colors in CLR files would be nice!

**Comment by mac-cain13** [comment]
I'm going to assume this is fixed with PR #312, P3 support has its own ticket now: https://github.com/mac-cain13/R.swift/issues/317
