### ISSUE TITLE
Better support for images in different bundles

### ISSUE THREAD

**Issue by nmccann** [mac-cain13/R.swift#31]
I have some `IBDesignable` classes that rely on images. Unfortunately using `UIImage(named:)` doesn't work in Interface Builder, as Interface Builder creates separate bundles for each class which you're supposed to use when creating images. For example, I have the following code:

```
let bundle = NSBundle(forClass: self.dynamicType)
let image = UIImage(named: "chevronAccessory", inBundle: bundle, compatibleWithTraitCollection: nil)
return UIImageView(image: image)
```

`"chevronAccessory"` is an image that exists in my asset catalog, so it would be nice if I could use R.swift to get the name.

Perhaps with the following format:
`R.imageName.chevronAccessory`
or
`R.image.name.chevronAccessory`

I'm not sure how typical this use case is, so it might not be worth decreasing the usability of images, but if you wanted to do so you could make images into a nested struct like `nib`. So then you could have:
`R.image.chevronAccessory.instance`
`R.image.chevronAccessory.insantiateWithBundle(bundle)`

**Comment by mac-cain13** [comment]
Thanks for bringing this to my attention. The bundle "problem" is something I'm aware of, didn't run into it myself yet so that's the reason I didn't fix it.

At least the `imageName` solution would be something that I could implement easily, but I hope I can create an even nicer solution. It's not at the top of my Todo list, but I'll look into it.

_If you're reading this and want this also fixed, please comment with a +1 to this issue._

**Comment by mac-cain13** [comment]
Alright, took a little peek into this. But I'm wondering what good example use cases are, maybe extensions of designables, but me or someone else should create some good example cases to see what is the best way to implement this.

**Comment by iv-mexx** [comment]
+1

I have a pretty large project with several targets for different versions of the App. I also have a target _CustomGUI_ that builds as a Framework in which some custom views are implemented that are used by all/some of the other targets. The _CustomGUI_ also needs some images which are shipped in an assets catalog of the _CustomGUI_ target. 

In order to use these Images, I need to load them from the correct bundle like this:
```
UIImage(named: "someImage", inBundle: NSBundle(identifier: "com.myCompany.customGUI"), compatibleWithTraitCollection: nil)
```

**Comment by mac-cain13** [comment]
Thanks for the concrete use case! I'll look into it. :)

Any proposal of how you would use R.swift?

**Comment by iv-mexx** [comment]
Initially, I would have expected to be able to the image name somehow like @nmccann originally suggested.

I agree on this:
> I'm not sure how typical this use case is, so it might not be worth decreasing the usability of images

Maybe, one solution would be to have an `imageResource` 

```
protocol ImageResource {
  var instance: UIImage? { get }
  var name: String { get }
}
```

```
struct _R {
    ...
    struct image {
        struct _testImage: ImageResource {
            var instance: UIImage? { return UIImage(named: "image.jpg") }
            var name: String { return "image.jpg" }
        }
    }
    ...
```

and have both:



```
struct R {
    ...
    struct imageResource {
        static var testImage: ImageResource { return _R.image._testImage() }
    }
    
    struct image {
        static var testImage: UIImage? { return _R.image._testImage().instance }
    }
    ...
}
```

Not sure if this is the best approach though...

**Comment by mac-cain13** [comment]
Yeah, interesting approach. Could work.

I'm now thinking; If R.swift would know the bundle the image is in we could always load based on the `UIImage(named: inBundle: compatibleWithTraitCollection:)` constructor. Then it would always work, in depended from the bundle you're calling the `R.image.someIcon` from.

**Comment by iv-mexx** [comment]
Yeah that would be nice. 

I have been using `NSBundle(forClass: self.dynamicType)` previously for that which might work here.

But for some reason, this has failed me today (unrelated, don't know why) so I had to use `NSBundle(identifier: "com.myCompany.customGUI")`

**Comment by iv-mexx** [comment]
By the way, in my scenario I have several `R.generated.swift` Files - one for each Target.

**Comment by mac-cain13** [comment]
One R-file per target is the correct approach when working with a setup like yours.

If I may ask; Am I correct that this problem does occur when you try to access an image that is in the app target from code that is in your library (using the `R`-struct from the app)? Just to be sure that I create the correct testcase when implementing this.

Maybe you could show me the line of code that fails and a little bit of it's context.

**Comment by andreyslyusar** [comment]
```
struct R {
    ...
    struct imageResource {
        static var testImage: ImageResource { return _R.imageResource._testImage() }
    }

    struct image {
        static var testImage: UIImage? { return _R.imageResource._testImage().instance }
    }
    ...
}
```

Current example do not take in account that 2 bundles can have an image with the same name. Maybe as an option we can target bundle first and image resource after:
```
R.bundle.<Bundle_name>.image.<Image_name>
```

And as a shortcut target main bundle as a default
```
R.image.<Image_name>
```

The same patter can be used for loading xibs, etc from none-main bundle.

**Comment by iv-mexx** [comment]
> Maybe you could show me the line of code that fails and a little bit of it's context?

I can try to create a small sample project representing my use case later today or maybe tomorrow.

**Comment by iv-mexx** [comment]
Oh sorry, forgot about the sample project. Today I discovered the need to specify the bundle when for `UINib.instance` as well, so I was reminded of that: https://github.com/iv-mexx/r.swift-example

**Comment by mac-cain13** [comment]
Tnx! I'll take a look. :)
