### ISSUE TITLE
Enforce using R.swift 

### ISSUE THREAD

**Issue by RishabhTayal** [mac-cain13/R.swift#313]
How can we enforce everyone in the team so that we can not use hardcoded strings anymore?

**Comment by mac-cain13** [comment]
The teams I work on use Pull Request for this, we just check each other code and if we spot a missing R.swift reference we comment on it.

If you want to automate it I think your best bet is to create a [SwiftLint](https://github.com/realm/SwiftLint) rule for things like `NSLocalizedString` and `UIImage(named:)` etc that warns you.

There is also an (very old) issue with a discusion about this: https://github.com/mac-cain13/R.swift/issues/30
