### ISSUE TITLE
I can't compile R.swift for swift 3, any settings I was missing?

### ISSUE THREAD

**Issue by menhui222** [mac-cain13/R.swift#314]
![2017-03-31 11 25 09](https://cloud.githubusercontent.com/assets/12657294/24535120/bbb0987a-1604-11e7-97c1-38b561b8b6ff.png)

**Comment by mac-cain13** [comment]
Looks like your computer has trouble connecting to AWS, could you give it another try? Probably just a glitch in your internet connection or AWS not working optimal in your region.

**Comment by mac-cain13** [comment]
I'll close this one but feel free to comment if you need more help!

**Comment by menhui222** [comment]
thank you
