### ISSUE TITLE
Spaces in image names not supported

### ISSUE THREAD

**Issue by M0rph3v5** [mac-cain13/R.swift#32]
xcode works fine with spaces in asset names, however R.swift generates invalid code

`static var detail Disclosure: UIImage? { return UIImage(named: "Detail Disclosure") }`

**Comment by mac-cain13** [comment]
Sounds like a bug. R.swift should take out the space for you!

Op wo 8 jul. 2015 om 14:26 schreef Benjamin de Jager <
notifications@github.com>

**Comment by M0rph3v5** [comment]
exactly

**Comment by mac-cain13** [comment]
Fixed in 0.8.1! :)
