### ISSUE TITLE
R.generated.swift for multiple targets?

### ISSUE THREAD

**Issue by theamorn** [mac-cain13/R.swift#320]
I have tried all the possible thing that I could before posting here. and look into all issues in this repo but couldn't find any clues. 

My project has to have multiple target for Swift 3.1 like production, staging, and etc
I've used R.swift since the project is started and it's working fine until last 2-3 days after I have added more Targets in the xcode and it's failed to build on other targets but the original one is still working

Here's the Error that I've got 
![screen shot 2017-04-26 at 11 09 22 am](https://cloud.githubusercontent.com/assets/6716483/25417794/de8b189a-2a70-11e7-852d-eb06697ff525.png)

I have different project `LivePopKit` to import into our project. That's project is just for Our API, and Model to use in this project.
![screen shot 2017-04-26 at 11 16 22 am](https://cloud.githubusercontent.com/assets/6716483/25417897/d28cc718-2a71-11e7-8ebe-696685caed1b.png)

But My main app is still working fine, just different target is not working. I suspect that it would because of sharing R.generated.swift for 3 different targets? but 3 different targets have exactly the same config because I did duplicated on the original one that's all. the different is just Display name and Bundle Identifier. that's it. 

even I did rename my main target to other name and rename my new targets to be the same name as original.  it's still not working. They have error about in R.generated.swift about `Could not infer type XXX`   XXX is Project name

Do you have any recommend for me to look for?
Thank you

**Comment by tomlokhorst** [comment]
I think I've been able to reproduce your issue in a test project.

In your storyboard, do you have "LivePop" set as an explicit module for the TagsPageController?
If so, try checking the "Inherit From Target" setting:

<img width="261" alt="screen shot 2017-04-26 at 06 55 46" src="https://cloud.githubusercontent.com/assets/75655/25419143/2215592e-2a51-11e7-8fee-9656884e1dc6.png">

**Comment by theamorn** [comment]
It's all checked as `Inherit From Target` 
![screen shot 2017-04-26 at 1 25 43 pm](https://cloud.githubusercontent.com/assets/6716483/25420783/f353d4c0-2a83-11e7-8851-e653b03b2736.png)

but isn't it weird that only this storyboard that has a problem? and I did picked the module in that storyboard and try to build. it's not working also
![screen shot 2017-04-26 at 1 27 56 pm](https://cloud.githubusercontent.com/assets/6716483/25420824/35a663a6-2a84-11e7-8b9c-7ca25e6cf7a0.png)

I'm still investigated more into it. I strongly believe that it should be a problem with naming thing

**Comment by tomlokhorst** [comment]
Is there `-> LivePop.CreateBroadcastViewController?` in the generated code?
Checking the box "Inherit From Target" should make R.swift generate: `-> CreateBroadcastViewController?`

Are you passing any extra arguments to the `rswift` executable?

**Comment by theamorn** [comment]
@tomlokhorst Thanks for your help.

I just look into all the storyboard from your guide and it's seem that some storyboard has untick the module so it's cause the problem because it's not inherit from target anymore 

but I found out new problem again  :\

![screen shot 2017-04-26 at 2 13 11 pm](https://cloud.githubusercontent.com/assets/6716483/25422264/878addd6-2a8a-11e7-8026-a6f7596c93dc.png)
