### ISSUE TITLE
String parameter name

### ISSUE THREAD

**Issue by guilhermearaujo** [mac-cain13/R.swift#321]
The example for localizable strings says:

```swift
let progress = R.string.localizable.copyProgress(completed: 4, total: 23)
```
I suppose the .string file has a line like:
```
"copyProgress" = "You have completed %d of %d";
```
Or something similar. I'd like to know do those parameters get labeled as `complete` and `total` instead of `value1` and `value2`.
I read the docs, but I couldn't find any example.

**Comment by tomlokhorst** [comment]
Argument labels for `R.string.*` functions are only generated for strings from a `.stringsdict` file. See [Apple's documentation](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/StringsdictFileFormat/StringsdictFileFormat.html) on the file format. For example, see [Settings.stringsdict](https://github.com/mac-cain13/R.swift/blob/master/ResourceApp/ResourceApp/Strings/Base.lproj/Settings.stringsdict#L13-L41) from our example app.

There's an issue discussing generating argument labels (https://github.com/mac-cain13/R.swift/issues/294) for `.strings` values, but no work has been done on that.
