### ISSUE TITLE
Getting framework not found error

### ISSUE THREAD

**Issue by RishabhTayal** [mac-cain13/R.swift#322]
I have `"$PODS_ROOT/R.swift/rswift" "--import" "Spring" "$SRCROOT"` script in my build phase in Xcode. 

I am getting the following error while compiling the project.

```
ld: framework not found Rswift for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tomlokhorst** [comment]
What version of R.swift are you using?

**Comment by RishabhTayal** [comment]
Just found the solution. The pod was not included in the `Podfile`. It works fine now. Thanks.
