### ISSUE TITLE
Missing option: --bundleIdentifier requires 1 parameters

### ISSUE THREAD

**Issue by hardeep68** [mac-cain13/R.swift#323]
Actually, we are using .xcconfig files to handle multiple environments. When we replace $(PRODUCT_BUNDLE_IDENTIFIER) with our .config file key $(APP_IDENTIFIER) then it is showing following error.

error: [R.swift] Missing option: --bundleIdentifier requires 1 parameters
usage: rswift [--version] [--edge] [--import] [--accessLevel] [--rswiftignore]
[-p|--xcodeproj] [-t|--target] [--bundleIdentifier]
[--buildProductsDir] [--developerDir] [--sourceRoot] [--sdkRoot]
[--productModuleName] [-h|--help]

**Comment by tomlokhorst** [comment]
I'm not sure what your exact setup is, but it sounds like you need to pass the `--bundleIdentifier` argument to the rswift executable.

In your "R.swift" build phase, use something like this:

> `"$SRCROOT/rswift" "--bundleIdentifier" "$(APP_IDENTIFIER)" "$SRCROOT"`
