### ISSUE TITLE
Include base translation in string generator.

### ISSUE THREAD

**Issue by gruchas** [mac-cain13/R.swift#324]
Hi!
It would be nice to have `value` property filled in all `NSLocalizedString`calls with base translation string. It will be included in exported for localization file. Then instead:
```
<trans-unit id="string-key">
        <source>string-key</source>
        <note>No comment provided by engineer.</note>
</trans-unit>
```

it will have:

```
<trans-unit id="string-key">
        <source>my base translation</source>
        <note>No comment provided by engineer.</note>
</trans-unit>
```

Source entry will be filled with translation instead of id.

**Comment by tomlokhorst** [comment]
Doesn't `NSLocalizedString` already fallback to the base translation if it exists?

**Comment by gruchas** [comment]
@tomlokhorst I have checked it, and if You don't provide default value in `NSLocalizedString` call, source is filled with ID.

**Comment by tomlokhorst** [comment]
Oh right, of course. The fallback to Base only happens for unsupported languages, not for missing translations.

R.swift currently logs a warning for files where values are missing for certain localised string resources. That should help with finding missing translations.

I'm not sure if it's a good idea for R.swift to add extra features above the default behaviour of `NSLocalizedString`.
R.swift's main feature is providing statically typed references to dynamic resources. Not to add a bunch of convenience "utility" methods. That could grow out of hand fast.

However the types used in the generated code do allow for extension in your own code, so you can for example write:

```swift

extension StringResource {
  public func withFallbackToBase() -> String {
    guard
      let basePath = bundle.path(forResource: "Base", ofType: "lproj"),
      let baseBundle = Bundle(path: basePath)
    else {
      return NSLocalizedString(key, bundle: bundle, comment: "")
    }

    let fallback = baseBundle.localizedString(forKey: key, value: key, table: tableName)

    return NSLocalizedString(key, tableName: tableName, bundle: bundle, value: fallback, comment: "")
  }
}
```

Which can be used like so: `R.string.settings.title.withFallbackToBase()`

**Comment by gruchas** [comment]
Hi!

This is not why I meant. When parsing Localized.strings, it will be nice to persist Base translation in call :`NSLocalizedString("Key", tableName: "table", bundle: Bundle, value: "base_tanslation", comment: "comment")` - When exporting for localization, since Xcode is scanning every use of NSLocalizedString in code, it will add base translation in xliff file instead of Key. This can allow easier translation. I think it would be good feature.

**Comment by tomlokhorst** [comment]
After discussing this with @mac-cain13, I now understand what you mean.
Previously I thought Xcode only looks at the .strings files when exporting .xliff files, but it also (or only?) scans for `NSLocalizedString` calls.

This seems like a good improvement. Feel free to send a pull request for this feature.
Otherwise, I'll implement this the next time I'm working on the R.strings part.

**Comment by mac-cain13** [comment]
This is now in master and will be in the next release!
