### ISSUE TITLE
No such module 'ChartsDemo'

### ISSUE THREAD

**Issue by dfing** [mac-cain13/R.swift#326]
I've install the latest version of RSwift, and drag the R.generated.swift files into my project.
Then I'm going to build project, I got the error that 'No such module 'ChartsDemo'' in R.generated.swift
[](url)

<img width="184" alt="2017-05-24 12 56 44" src="https://cloud.githubusercontent.com/assets/8773116/26387601/872223c4-4081-11e7-8b4f-dcbb7fa6e673.png">
<img width="188" alt="2017-05-24 1 04 56" src="https://cloud.githubusercontent.com/assets/8773116/26387616/9b411626-4081-11e7-97a0-6d599ba93a19.png">

I've google about the error, and try to add `$(SRCROOT)` to Build Setting - Framework Search Paths.
But it's not work for me, I still got the error.

I want to ask that is there any solution? 
Or perhaps I lost some step when install RSwift? 

Thank you for your response

**Comment by mac-cain13** [comment]
Thank you for using R.swift!

It sounds like the ChartsDemo is not correctly linked into you project at this moment. Can you import ChartsDemo in another Swift file of your project? And can you use a class/method or function from ChartDemo in another Swift file? 

If that also doesn't work you maybe missed a stap in the installation instructions of ChartsDemo, if it does we have to dig a little bit further into this problem

**Comment by dfing** [comment]
Hi, @mac-cain13 it seem to I don't have 'ChartsDemo' file in my project, I can't import it and use any class/method cause this file not exist :((

I install RSwift following this ..

1. Add `pod 'R.Swift'` to podfile and run pod install
   -> this step complete, it've install 
```
Installing R.swift (3.2.0)
Installing R.swift.Library (3.0.2) 
```
2. Add Run Script and paste `"$PODS_ROOT/R.swift/rswift" "$SRCROOT"` 
3. Build my project, and I got the file named `R.generated/swift`, and draw to xcode

In swift file of my project I can use R.image.xxxxx method, but I got the error when I compiler my project.

Did I need to extra install ChartsDemo or add the file?

**Comment by dfing** [comment]
@mac-cain13 I just create a new demo project, only install R.swift, and all step are same
I open the R.generated.swift, It not exist `import ChartsDemo`, so ChartsDemo isn't create by R.swift?

**Comment by dfing** [comment]
@mac-cain13 Sorry, this is my mistake. In my project, some file use 'ChartsDemo' module, I just find it. Then, I remove the module, and build project successful. Thanks your help!!! :))

**Comment by mac-cain13** [comment]
Good to hear you figured it out! Good luck building your app! :)
