### ISSUE TITLE
The new release (0.8.1) is broken

### ISSUE THREAD

**Issue by stefangeir** [mac-cain13/R.swift#33]
It generates a file where `UITableViewCell` and `UICollectionView` (and more) are written as `Uitableviewcell` and `Uicollectionview` (or similar) and a project using it won't compile.

**Comment by mac-cain13** [comment]
Thanks for reporting this. Stupid mistake. Will release a new version asap!

For now you can of course downgrade by requiring 0.8.0 in your podfile.

Sorry for the trouble it is causing!

**Comment by stefangeir** [comment]
No problem, yeah I just downgraded straight away :).

**Comment by mac-cain13** [comment]
And fixed! :) 0.8.2 is now available.

**Comment by stefangeir** [comment]
Nice, thank you!
