### ISSUE TITLE
Add support for loading local project files

### ISSUE THREAD

**Issue by RishabhTayal** [mac-cain13/R.swift#330]
Can we add support to recognize the local files stored in the project? Sometimes we add videos, html or json files to the project directory. We should add capability to recognize those files as assets as well.

Happy to create a PR for this if someone can give me directions on how to implement.

**Comment by tomlokhorst** [comment]
Resource files that are members of the target are available under `R.file.*`, see [Examples](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#resource-files).

Is this what you mean?

**Comment by RishabhTayal** [comment]
That's exactly what I meant. Thanks. I did not know this feature exists. I checked the examples before and maybe I missed it.

**Comment by RishabhTayal** [comment]
However if I have a video asset in the `xcassets` file, it's not recognized by `R.swift`. 

For e.g. I have `video1.mp4` in the `Assets.xcassets` file. I am not able to get `R.swift` to recognize the `video1.mp4` file. I would like to get url of the video.

**Comment by mac-cain13** [comment]
The paths to files in an `xcassets` folder are not directly available as far as I know. How would you get the path/url to the mp4 file without R.swift?

**Comment by RishabhTayal** [comment]
Not sure but something like `Bundle.main.pathForResource` should work. right?

**Comment by mac-cain13** [comment]
Well I don't think that would work. If I look in the docs [I don't see mp4 files listed here](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/AssetTypes.html#//apple_ref/doc/uid/TP40015170-CH30-SW1) as a supported file type for asset catalogs. Also answers like this [one on SO](https://stackoverflow.com/a/19001255/586489) show that paths are not available for assets in a catalog, at least in older iOS versions.

If you could do some research and give an example of how it works without R.swift we could add the feature.

**Comment by RishabhTayal** [comment]
I believe in the `xcasset` all the file types other the image are under folder `.dataset`.

<img width="188" alt="screenshot 2017-05-31 15 13 30" src="https://cloud.githubusercontent.com/assets/2100166/26652004/0d96cfb2-4614-11e7-952c-796041e2242e.png">

`.dataset` is supported [here](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/DataSetType.html#//apple_ref/doc/uid/TP40015170-CH23-SW1)

**Comment by mac-cain13** [comment]
Yeah that is a good point, you can add arbitrary data using the dataset type. The question that remains is; how do you get the URL to that resource using the standard Foundation and UIKit APIs?

**Comment by RishabhTayal** [comment]
I believe we can do it like this `Bundle.main.resourcePath! + "/Video.mp4"`

**Comment by RishabhTayal** [comment]
I will try to take a stab at implementing this. I think it's possible.

**Comment by RishabhTayal** [comment]
Created a pr for this. Need some help with how I can implement this.

**Comment by tomlokhorst** [comment]
I would suggest starting by adding a (small) example video file to ResourceApp example project.
Use that with Apple's native APIs, instead of R.swift. That gives you an idea of what actual code should be generated.

**Comment by RishabhTayal** [comment]
I am not able to do `pod install` in the example project.

**Comment by mac-cain13** [comment]
Do you get some kind of error? I'm affraid there is not much I can do to help without a little more info.

**Comment by RishabhTayal** [comment]
It hangs on this message for a while and then throws an error.

Hangs on:
```
Pre-downloading: `R.swift.Library` from `git@github.com:mac-cain13/R.swift.Library.git`, commit `594965c3c1d42d9a4390eec3ecf159ab8210cb78`
```

Finally getting error:
```
[!] Error installing R.swift.Library
[!] Failed to download 'R.swift.Library'.
```

**Comment by mac-cain13** [comment]
Well, this is a bit of a "works on my machine" situation. Maybe verbose logging tells you some more about what's going wrong or it was Github having a hiccup.

**Comment by RishabhTayal** [comment]
I see these two lines in the `Podfile`. 

```
  pod 'R.swift.Library', :git => 'git@github.com:mac-cain13/R.swift.Library.git' # for CI builds
  # pod 'R.swift.Library', :path => '../R.swift.Library' # for development
```

I wonder which one should I use?

**Comment by mac-cain13** [comment]
The top one should work since you then get the latest version from github. You can also just remove the `:git` part to get the latest stable version of the library.

**Comment by mac-cain13** [comment]
I'm going to close this due inactivity, feel free to comment here again if you're going to work on it again.
