### ISSUE TITLE
Make R struct public.

### ISSUE THREAD

**Issue by Samback** [mac-cain13/R.swift#333]
Is it possible to make  R struct public at least as an option?
Now I have faced with an issue that if `R.generated.swift` placed at one of my pod's, I didn't have any access to get files/images from there.

**Comment by tomlokhorst** [comment]
Yes, you can pass this option to the `rswift` executable: `--accessLevel public`

I just noticed, this isn't documented anywhere except for in release notes.
Note to self: We should document the options somewhere.

**Comment by Samback** [comment]
Probably you can double save my life and say next thing. Is it possible to change R struct to something else?  Just with another name if I want to use it at couple of pods.

**Comment by Samback** [comment]
+ Am I right? I need to add make something like this ?
"$PODS_ROOT/R.swift/rswift --accessLevel public" "$SRCROOT"

**Comment by Samback** [comment]
Small update. "$PODS_ROOT/R.swift/rswift --accessLevel public" "$SRCROOT" - doesn't  work for me :(

**Comment by tomlokhorst** [comment]
This should work:
`"$PODS_ROOT/R.swift/rswift" --accessLevel public "$SRCROOT"`

It's not possible to name `R` something else.
But you can use the fully qualified name:

```swift
import MyPod

...
let logo = MyPod.R.image.logo()
```

Or using a typealias:

```swift
import MyPod

typealias MyPodResources = MyPod.R

...
let logo = MyPodResources.image.logo()
```

**Comment by Samback** [comment]
Yeah, `typealias` can save me. 
```
error: [R.swift] The option 'Invalid option: --accessLevel' is invalid.
usage: rswift [--version] [-p|--xcodeproj] [-t|--target] [--bundleIdentifier]
              [--buildProductsDir] [--developerDir] [--sourceRoot] [--sdkRoot]
              [--productModuleName] [-h|--help]
```

**Comment by tomlokhorst** [comment]
You're using an older version of R.swift, update to the latest version.

**Comment by Samback** [comment]
Thanks! Now it's work!

**Comment by Samback** [comment]
Have a nice day!
