### ISSUE TITLE
Xcode source code editor plugin -  discussion

### ISSUE THREAD

**Issue by Tvede-dk** [mac-cain13/R.swift#335]
Related to #30; 
It is possible to create somewhat a source code editor plugin that will allow "mostly" to do the "vanilla" to R.swift conversion automatically* (with the click of a button, can be mapped to a shortcut in xcode )
Currently i have the following example / preview; 
![Example / preview](https://github.com/Tvede-dk/rswift-xcode-source-editor-plugin/raw/master/preview.gif)
(the repo https://github.com/Tvede-dk/rswift-xcode-source-editor-plugin/ contains all the code).
However, there are some limitations to what is possible, such as and editor plugin is only allowed to process the current open file..

so the discussion is about :
1) is this still a thing people want ? / is it usable enough ? 
2) (assuming 1) should it then use R.swift.library to generate the "correct code" ? 
3) should source kitten (eg), be used, to process the file more correctly than regexp's ?
4) should this plugin eventually be distributed ? (to my knowledge, the only way to install an xcode source editor plugin (for regular users), is to install an application from the app store ?) 

EDIT:
- in the case of bundling with an application; one could create a cli (and or gui) with the ability to install R.swift into a project, upgrading all vanilla references (in all files), and create / insert the run phase script ?

**Comment by mac-cain13** [comment]
Oh wow quite cool you created this! Nice. :)

1. Yeah I think it's a nice thing to have, not entirely sure it should be an extension/part of R.swift itself/a set of swiftlint rules. But yeah I think it is definitely a nice thing to have.
2. I don't think there is a handy point to hook into for this kind of thing. But at least you could use the `SwiftIdentifier` code to convert from a string to the method R.swift generates.
3. Would be nice, but I'm not sure how complex that it is for the cases we need. A regex could be a good start, if it becomes popular we could always improve on it.
4. Yeah, that's a thing. It should be in a Mac AppStore app. Also that you can handle one file at a time is not super handy. Maybe a seperate commandline tool `rswift-convert`, `rswift-lint` or maybe integrated in swiftlint...

Regarding your edit; Yeah agree, it could be a "helper" app that supports integrating R.swift on a broader level.

Again; nice work. I think it definitely is interesting to develop somewhat further and share it with R.swift users. What do you think are the best next steps to take with this?

**Comment by Tvede-dk** [comment]
You are welcome (I should still be thanking for R.swift ,which I am :) ) [sorry for the late answer]
So let me turn the comments around and into what appears to be the "concerns" (if you will):

- this will play nicely with swiftlint rules ; IF(and only if) they are aligned (so they use the same rules.
  - this also goes for the "quick fix" / automatic fixes. (again, requires the same rules, and opens up another issue, how can we "align" this nicely ?, as you state "I don't think there is a handy point to hook into for this kind of thing..." )
- I belive this (together with swiftlint) could provide a good senario, where the user are able to gradually see this in action (though the plugin) and then later setup swiftlint with it as well. it also allows one who is learning to see what he /she can do to convert / improve (using R.swift). 

- lastly (regarding actually bundling this)
    the vision for me is that; i could go on the app store after hearing about R.swift. then download a help application (or from github); then this bundled application would contain some "information" about R.swift, and links (for good sake), and then some "getting started functionality"; such as
   -  add R.swift to a vanilla project (maybe even a guide (visual) and a real convert project button, that applys R.swift to a project), and also add the run with script (thus, install is a one click of a button)
   -  install it using homebrew ? 
   - you tell me ?  


The next step ? well I could try and see if I can do some of the above. 
- and especially see if it is possible to distribute it without the appstore. It would be nice to be able to try it out in xcode , and let people try it out, without having to have a developer license just to get some feedback on it :)

**Comment by mac-cain13** [comment]
I think a separate app with extension could indeed be nice, feel free to experiment with what could work. Once you have something we could look what is the best way to release it.

Not that I think that the effort of maintaining an app on the Mac AppStore for this is quite high, that is one of the reasons I suggested a separate tool or integrating with swiftlint. I think in the long run that is easier to maintain and a Mac app is nice for a solo dev, but when working in a team everybody needs the app if you also want to use it for linting and not only for setup.

**Comment by mac-cain13** [comment]
Doing a bit of a cleanup round, so I'm going to close this. Feel free to comment here again if there is any news or if there are new ideas about a source code plugin!
