### ISSUE TITLE
Avoid name collision of R.swift in multiple pods

### ISSUE THREAD

**Issue by gotev** [mac-cain13/R.swift#344]
When developing a pod in which I want to use R.swift, it will be nice to have the R.generated.swift to match the pod name, to allow external users to easily get resources contained in my pod. I had to do it in a bunch of projects. I've made a workaround I wanted to share. Basically, you just have to add a build script after R.swift. The script is the following:

```bash
#!/bin/bash -e

MODULENAME="YourPodModuleName"
NEW_RSWIFT_NAME="TheNewNameYouWantToGiveToRswift"
CLASS_FROM_YOUR_BUNDLE="AClassFromYourPod"

SRCFILE="$SRCROOT/$MODULENAME/R.generated.swift"
DESTFILE="$SRCROOT/$MODULENAME/$NEW_RSWIFT_NAME.swift"

mv "$SRCFILE" "$DESTFILE"

sed -i.bak "s/public struct R: Rswift.Validatable {/public struct $NEW_RSWIFT_NAME: Rswift.Validatable {/g" "$DESTFILE"

sed -i.bak "s/R\./$NEW_RSWIFT_NAME\./g" "$DESTFILE"

sed -i.bak "s/_$NEW_RSWIFT_NAME/_R/g" "$DESTFILE"

sed -i.bak "s/Bundle(for: DesignResources.Class.self)/Bundle(url: Bundle(for: $CLASS_FROM_YOUR_BUNDLE.self).url(forResource: \"$MODULENAME\", withExtension: \"bundle\")!)!/g" "$DESTFILE"

rm -rf "$DESTFILE.bak"

```
You only have to configure the first three parameters, and what you will get will be a fully working customized R.swift which pod users can use without worrying about bundles.

**Comment by tomlokhorst** [comment]
Thanks for sharing your script.

I haven't used R.swift in different pods, but I have used it from different Xcode projects.
Once you've supplied `--accessLevel=public`, you can use a `R` struct from a different module like so:

```swift
import MyModule


let logo = MyModule.R.image.logo()

```
