### ISSUE TITLE
Error when trying to register(NibResourceType) cell to a UITableView

### ISSUE THREAD

**Issue by edulpn** [mac-cain13/R.swift#346]
I created a UITableViewCell subclass called IssueTableViewCell:
![image](https://user-images.githubusercontent.com/4682317/28689481-2068ec74-72ec-11e7-834a-8f79b76b8c42.png)

When trying to register the cell to my UITableView I get:
![image](https://user-images.githubusercontent.com/4682317/28689760-0c4dcbfa-72ed-11e7-8622-64aa232d176a.png)

Checking R.genereated.swift further, the NibResourceType was generated for my cell:
![image](https://user-images.githubusercontent.com/4682317/28689810-41b5f948-72ed-11e7-91b7-5a76872148dc.png)

I installed R.switft through Cocapods, created the build phase and it's running all the other features fine.

**Comment by edulpn** [comment]
Fiddling a bit more, I saw I forgot to set the "Reuse Identifier" on Interface Builder for my cell:
![image](https://user-images.githubusercontent.com/4682317/28690023-1111e616-72ee-11e7-9e12-c2cd4eee77de.png)

And now it works fine:
![image](https://user-images.githubusercontent.com/4682317/28690032-2073e33e-72ee-11e7-87e2-bc8f0591e9bd.png)

It'd be cool to see a bit more documentation on https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#reusable-table-view-cells

**Comment by mac-cain13** [comment]
I was just writing a comment to ask you to check if a reuse identifier was set. I think it would be nice to update the docs a bit.

I'm leaving tomorrow on a holiday so I don't have time to do it now, but feel free to submit a PR! Will be happy to merge it. :)

**Comment by edulpn** [comment]
Awesome, will send you a PR! Have a nice holiday!

**Comment by edulpn** [comment]
@mac-cain13 sorry for not doing it on time, I just sent the PR. #350

**Comment by User2004** [comment]
[Click here](https://webappcodes.com/uitableview-custom-cell-in-swift-3-or-later) for register custom UITableViewCell in ViewController
