### ISSUE TITLE
Extending for custom usage

### ISSUE THREAD

**Issue by semireg** [mac-cain13/R.swift#347]
Somewhat related to #263, I'd like to explore parsing an external resource such as JSON and build Swift enums.

Here's an example of the JSON I'd like to parse:

```
{
  "Function": {
    "type": "UInt8",
    "cases": {
      "read": {
        "value": "0x01"
      },
      "write": {
        "value": "0x02"
      },
      "foo": {
        "value": "0x03"
      }
    }
  },
  "Memory": {
    "type": "UInt16",
    "cases": {
      "mode": {
        "value": "0x01",
        "encoding": "uint16",
        "interval": {
          "lower": "-60",
          "upper": "300",
          "step": "10"
        },
        "displayName": "test",
        "unit": "meter",
        "override": "setup"
      },
      "setup": {
        "value": "0x02"
      },
      "service": {
        "value": "0x03"
      }
    }
  }
}
```

This would produce the following Swift within R.

```
enum Function: UInt8 {
    case read = 0x01
    case write = 0x02
    case foo = 0x03
}

enum Memory: UInt16 {
    case mode = 0x01
    case setup = 0x02
    case service = 0x03
}

struct MemoryMode {
    let value = Memory.mode
    let encoding = Encoding.uInt16
    let interval = Interval(lower: -60, upper: 300, step: 10)
    let displayName = "test"
    let unit = Unit.meter
    let override = Memory.setup
}
```

I've read through the documentation and readme for both R.swift and R.swift.Library. I'm not sure on the best path forward. I'd be happy to fork and offer a pull request once I get my bearings within the project. 

Thoughts on achieving this?

**Comment by tomlokhorst** [comment]
As was mentioned in that other thread, arbitrary code generation is really outside the scope of R.swift.

R.swift is meant to create static references to stringly typed Apple interfaces, working on (soft of) known file formats. It is not a general purpose code generator.

Perhaps you could use something like [Sourcery](https://github.com/krzysztofzablocki/Sourcery) to get what you need?
