### ISSUE TITLE
The Xcode build system has crashed

### ISSUE THREAD

**Issue by kagenZhao** [mac-cain13/R.swift#348]
MAC: 10.12.6
Xcode 9 beta 5

When I dragged "R.generated.swift" into the project, "XCBBuildService" crashed. Reopening "Xcode" still crashes

![image](https://user-images.githubusercontent.com/15279361/29392632-b24087c4-8331-11e7-8bd3-4ab1cb0929e6.png)

**Comment by mac-cain13** [comment]
That's not so nice! Did you use the latest R.swift version? If so this sounds to me like an Xcode beta issue that you should report to Apple. Xcode should never crash on whatever file you drag into it.

**Comment by kagenZhao** [comment]
Hope that "Xcode 9 beta 6" can solve this problem ...
