### ISSUE TITLE
error of 'ImageResource' can't convert to 'UIImage' type

### ISSUE THREAD

**Issue by Longroader** [mac-cain13/R.swift#349]
Hi, thanks for your great working, I have a problem with using this framework this days.
after I "pod install" the latest version, and rebuild R.generated, everywhere reported  the same error named:  "Cannot convert value of type 'ImageResource' to expected argument type 'UIImage?',  and I don't know why, please show me how to resolve this. thanks again!!!

**Comment by tomlokhorst** [comment]
The R.image struct has two overloads for each image.
A property with a ImageResource that can be used by other libraries, and a function that returns a UIImage.

You can pick the UIImage by calling the method with `()` at the end, like so:
```
someImageView.image = R.image.logo()
```

**Comment by Longroader** [comment]
Thanks very much! problem solved! wish you have a good weekend!!
