### ISSUE TITLE
Specify access control based on resource type or specific file

### ISSUE THREAD

**Issue by thedavidharris** [mac-cain13/R.swift#351]
As noted in https://github.com/mac-cain13/R.swift/issues/245, while the --accessLevel public is incredibly useful for a project that is constructed from dynamic frameworks, unfortunately specifying access on the R.generated.swift file is an all or nothing process, thus requiring potential over-exposure of classes. This was noted in [one of the comments on the issue](https://github.com/mac-cain13/R.swift/issues/245#issuecomment-241990539). This would be particularly useful to avoid over-exposure of view controller classes just to expose things like Fonts or Images.

I think there's two ways to probably make this happen:

1. Add separate accessLevel params for each generator type (i.e. `--accessLevelFont public`)
2. Keep the core `--accessLevel` flag, but have something like a `.rswiftaccess` file to override it that behaves similarly to the `.rswiftignore`

**Comment by mac-cain13** [comment]
Thanks for taking the time to create an issue about this!

I'd like to try to keep the complexity of the R.swift codebase under control and while I can see the benefits for libraries exposing a few assets I think that it's not a feature that would be used by the majority of the users. If it's low impact and low maintenance I would consider it, but adding a whole bunch of flags or parsing a extra config file doesn't make things simpler I'm afraid.

What kind of use cases would you use this feature for? And are those things you use very often?

**Comment by thedavidharris** [comment]
One issue we're running into (and it's maybe not really even an issue) is that we'd like to expose things like fonts and images in one of our dynamic frameworks to other frameworks that import it from within our app, but in order to do so we also have to make a bunch of things on our view controllers public when they really don't need to be, we'd prefer them to stay internal. I 
can see an argument too for why this would be intended behavior though.

**Comment by mac-cain13** [comment]
Personally I only use these feature to expose resources in internal frameworks to my app. For example for shared UI/resources where it's not a real problem if we expose a little bit too much. (Note that resources are always loadable with Apples UIKit methods, it's only that R.swift now exposes them in autocomplete.)

Also if you want to restrict the set of assets you expose with your lib you probably also don't want to export all images for example but just a few. So in that case I think it's better to roll your own explicit resource file where you export only the specific things you want to expose. Could look something like:

```
public struct Resources {
  public static let someImage { return R.image.someImage() }
}
```

The thing is; I'm not convinced this is a very common use case (like 80% of the users use this) and to do it right you need a pretty complex `. rswiftaccess` file to makt include specific asset public.

**Comment by mac-cain13** [comment]
Did think a bit more about this an I think I stand by the above reasoning to not make more finer grained access control to R.swift generated code. If someone has compelling arguments against this I would love to hear them!

**Comment by avangel** [comment]
Your proposal of manually expose some assets is a great workaround when you stick to shared resources. In my context, I'm using dynamic frameworks to structure my app by business domain and I'm making big use of storyboards and Nibs.

Let's say I have a `User` module containing all user-related stuff: assets, reusable tableview cells, storyboards, data model, etc. Regarding assets, I'm okay with sharing the whole set of images, etc. This does not look like an issue to me.

I'd like to expose only some of this stuff for external use: a tableview cell that's used all over the app, one storyboard VC but not some others, etc. 

One "simple" way of enabling this could be to check access level of individual classes related to the generated property.  For example, if my storyboard has 5 ViewControllers, one of them having an associated `public` class, the others internal classes. When generating the `R.generated.swift` only those identifiers that reference public classes are generated as public as well. The same could apply to Nib files.

What's your opinion on this ? Many thanks for your great work.
