### ISSUE TITLE
images in main.bundle

### ISSUE THREAD

**Issue by iOSleep** [mac-cain13/R.swift#352]
i have some big images, only use once at launch. To save the memory i use these images by 
```
UIImage(contentsOfFile:_)
```
but R.swift just generate as a `URL` by `R.file.xxx`
shall we have  plan to distinguish image by the pathExtension ?

**Comment by tomlokhorst** [comment]
R.swift generates both a function and a FileResource for each file.
For example: `R.file.onboarding()` will return a `URL?`, but `R.file.onboarding.path()` returns the full path.

So you can currently do something like:
```swift
UIImage(contensOfFile: R.file.onboarding.path()!)
````

Is this what you're looking for?

**Comment by iOSleep** [comment]
thanks, its helpful~
how about images in a custom bundle(add extension `.bundle` to a finder)

**Comment by mac-cain13** [comment]
I think the path should always create a valid absolute path to the resource, so I think it doesn't matter if you're a custom bundle.

Or am I missing something? If so, could you give an example of what code you would use to load the resource normally without R.swift?

**Comment by mac-cain13** [comment]
I'm closing this one, but feel free to comment again on this issue if you need more help!
