### ISSUE TITLE
Fail to generate R.swift for development Pods

### ISSUE THREAD

**Issue by kristiyanP** [mac-cain13/R.swift#357]
I currently have an Example app with a development pod
generated with the following command `pod lib create Design`

Our resources are in the development pod
The development pod obviously will be published with cocoapods

Our main problem is that the generated `R.generated.swift` does not contain the resources of the development pod.

From my understanding and your description it has to do with the fact that R.swift uses the pbxproj and target for the building as source set for the generation of the resources. Which leads to the generation of a R.generated.swift without resources.

If I do put the R.swift generation script on the CocoaPod project referencing my development pod, it works correctly. 

Too bad that CocoaPods does not save the scripts used for the pods.

**Comment by kristiyanP** [comment]
I solved it temporarly with a workaround
# For future reference:
Instead of using cocoapods library
### I have two projects one for the library and one for the demo
   * demo project references the library as a local pod
   * in the library project I have the r.swift scripts
   * in the demo project I have a script that using **xcodebuild command line** builds the library project and a script that does **pod install** to update the demo reference to the library

**Comment by tevelee** [comment]
My take on this was
```ruby
puts "Adding code generation build phases to development pods"
  installer.pods_project.targets.each do |target|
    if modules.include? target.name
      phase = target.new_shell_script_build_phase("Code generation")
      phase.shell_script = "\"$PODS_ROOT/R.swift/rswift\" generate \"$SRCROOT/Modules/#{target.name}/Sources/Generated/R.generated.swift\""
      phase.input_paths << "$TEMP_DIR/rswift-lastrun"
      phase.output_paths << "$SRCROOT/Modules/#{target.name}/Sources/Generated/R.generated.swift"
      target.build_phases.unshift(target.build_phases.pop()) # move it to the beginning
    end
  end
```
