### ISSUE TITLE
Use of undeclared type 'ViewController'

### ISSUE THREAD

**Issue by aliasdoc** [mac-cain13/R.swift#365]
Hi,

I'm trying to use this library with Xcode 9 and swift 4 and I have this error when i'l building:

`Use of undeclared type 'ViewController'`

I'm using cocoa pods and use 4.0.0 version:

`Installing R.swift 4.0.0`

Thank you.

**Comment by tomlokhorst** [comment]
One of your storyboards or xibs probably has a Custom Class set to "ViewController".
If your change or remove this custom class, the compile error should go away.

**Comment by tomlokhorst** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.

**Comment by bbookman** [comment]
I'm getting the same issue.  However I'm not understanding the suggested solution.  I have a story board item that i want to have a custom class on - you know so i can do segues or whatever.  For clarity, I created a coco touch file and have code there as a custom view controller.  In that same storyboard item i have placed a Cosmo View (a view with class Cosmo View).

Please help me out.  My code is at [](https://github.com/bbookman/MVP/tree/broken)

**Comment by Johnyoat** [comment]
> One of your storyboards or xibs probably has a Custom Class set to "ViewController".
> If your change or remove this custom class, the compile error should go away.

**Solution for Swift 4+**

Change the `ViewController` to `UIViewController`
