### ISSUE TITLE
how to use in Unit Test of Xcode9

### ISSUE THREAD

**Issue by gongyucheng** [mac-cain13/R.swift#367]
I test the viewcontroller in Unit Test,but the R.image can't find the image,how to resolve it?

**Comment by mac-cain13** [comment]
It should just work. Does the image load if you just run the app? And if you load the image with the regular Apple APIs in the unit tests?

**Comment by tomlokhorst** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.
