### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#37]
As @ntnmrndn points out in issue #36; R.swift is not yet Swift 2.0 compatible. The only fix needed so far is this one:

https://github.com/ntnmrndn/R.swift/commit/a1d58b9825c2395dafea3cde7e175ce8c0f3ce74

**Comment by remzr7** [comment]
+1

**Comment by Ewg777** [comment]
+1

**Comment by ntnmrndn** [comment]
TODO: instantiateViewControllerWithIdentifier now return a UIViewController, the cast is now unnecessary and generate a warning.

**Comment by mac-cain13** [comment]
Thanks for pointing this out @ntnmrndn! :)

**Comment by aidenluo177** [comment]
+1

**Comment by mac-cain13** [comment]
Working on this in PR #44! R.swift will be completely Swift 2 when version 0.9.0 is released. :)

**Comment by ntnmrndn** [comment]
Cool :) If you need some testers, we can give a hand.

**Comment by mac-cain13** [comment]
This is in the develop branch now! Will be in the next release. :)
