### ISSUE TITLE
Usage example of `registerHeaderFooterView`

### ISSUE THREAD

**Issue by allenhumphreys** [mac-cain13/R.swift#378]
I've attempted to figure out how to use [`registerHeaderFooterView`](https://github.com/mac-cain13/R.swift.Library/blob/4f9858b8a4022d74a647d6747dc7ebef7514790e/Library/UIKit/UITableView%2BReuseIdentifierProtocol.swift#L64) correctly. I've defined a view in an XIB file with a custom subclass of `UITableViewHeaderFooterView`. But, since it does not have a reuse identifier, I cannot use it in the same way I use `UITableViewCell`s defined in XIB files. 

I believe I understand how this function is intended to be used, but R.swift is not generating a struct that can be passed in. There are no examples of header/footer views in the documentation. Guidance on this would be appreciated.

**Comment by tomlokhorst** [comment]
Unfortunately, R.swift currently doesn't support for table view headers and footers. See https://github.com/mac-cain13/R.swift/issues/144
