### ISSUE TITLE
Type fonts

### ISSUE THREAD

**Issue by ntnmrndn** [mac-cain13/R.swift#38]
On iOS, user can provide custom fonts through Info.plist's UIAppFonts.
It would be nice to provide completion for:

     func R.font.appFonts.fontName(fontSize:14.0) -> UIFont!
     var R.font.appFonts.fontName: String

Bonus:

    R.font.system.helvetica(fontSize:14.0) -> UIFont!
    var R.font.system.helvetica: String

This is a bit complicated since with have to find the right names for the fonts, but it would be a really nice feature :)

Maybe I can find some time to implement that.
Can you give me a feedback before I start ?

**Comment by mac-cain13** [comment]
Agreed, that would be awesome! Great idea. :)

I would prefer `R.font.myOwnFont(fontSize: 14.0) -> UIFont?`. This is a bit shorter and R.swift never force unwraps anything, the library should not crash if the resource is not available.

System fonts could also be under `R.font.anIosFontName(fontSize:14.0) -> UIFont?` since duplicate font names will not work anyway. :)

If you have time to create a PR please go ahead! Keep me posted about your state. :)

**Comment by ntnmrndn** [comment]
Good point, `R.font` would be enough.

**Comment by mac-cain13** [comment]
Looked a bit into this and I think that the `fc-query` commanline tool can help us out to get the fontname that we have to use in iOS.

`fc-query --format "%{family}" [fontfile]` will report a list of fontnames in this file. So far the last one in the list seemed to be the correct one the use. Look like it is `fontname` or `familyname,fontname`, but it seems that all kind of crazy combinations are possible, so it could be that we're wrong.

**Comment by ntnmrndn** [comment]
Good job !
fc-query is definitely the way to go, and it should be trivial to integrate the fonts now.
        `find -E .  -regex ".*\.(ttf|otf)" -exec fc-query {} -f "%{postscriptname}\n" \;`
Using this command display the correct names of all fonts in sub directories.
I'll do some PR by the end of next week if you don't do it before :)

**Comment by ntnmrndn** [comment]
I wrote a draft which is returning font names as Strings.
I used `fc-query` at `"/opt/X11/bin/fc-query"` path.

Since `fc-query` seems to be an optional binary, I'm a bit puzzled about wether it is safe to use a hardcoded path.
Reading PATHS from environment might be a better solution, but I'm wondering wether this is the way to go or not.

We could also fail and ignore font generation if fc-query is not at the expected path (my preferred solution).

An other solution would be to forget about fc-query and try to do it programmatically.

What do you think ?

**Comment by mac-cain13** [comment]
Hardcoded paths sounds like a no-go to me. My `fc-query` is at `/usr/local/bin/fc-query`. Can't we just call `fc-query something..` without a path? We should check a clean OS X install with Xcode for the availability of `fc-query` I think. 

We can't just skip the font part when `fc-query` is unavailable, because if we're working in a team and you have `fc-query` and I don't then you'll write code that I can't compile on my system. Since the `R.font` struct will disappear when I compile but you have written code that depends on it.

**Comment by mac-cain13** [comment]
Just realized I installed Fontforge through brew, so that probably installed the Fontconfig binaries on my system.

This doesn't give much hope for `fc-query` being there by default: http://apple.stackexchange.com/questions/118737/does-osx-10-9-1-have-fontconfig-installed-by-default

**Comment by tomlokhorst** [comment]
For reference; There is no `fc-query` in my path on my OS X installation.
Although I did find one in a Mono installation. I'm not sure how it is supposed to get installed on a system.

**Comment by ntnmrndn** [comment]
Ok so let's rule out fc-query.

I will try in 3 steps:

1. List all fonts with `NSFontManager.sharedFontManager().availableFonts`

2. Load fonts found in XCROOT

3. List all fonts again and retain the difference.

To add system fonts, I think an hardcoded list avaliable/deprecated annotation is best, since we have no way of discovering fonts available on iOS from an OS X application. 

I will try to push a preview very soon.

**Comment by mac-cain13** [comment]
4. Only generate font struct when a flag is given to R.swift. Like `--enable-font` and error when fontconfig is not installed then. That would make it an optional thing.

**Comment by ntnmrndn** [comment]
Actually, just loading the file allow us get its name very easily.

     let fontDataProvider = CGDataProviderCreateWithURL(fileURL);
     let customFont = CGFontCreateWithDataProvider(fontDataProvider);
     let postsciptName = CGFontCopyPostScriptName(customFont) 

3 lines !
I made a pull request with the feature.

**Comment by mac-cain13** [comment]
Awesome!

Currently I'm in the middle of moving all of my stuff to my new house. So it can take a few days before I have time to look into your PR. But your please be assured that your effort is highly appreciated!

**Comment by mac-cain13** [comment]
@ntnmrndn A little heads-up from my side:

I'm back from my "move to a new house"-vacation and your PR is the next thing to merge in! If I have questions, I'll let you know, but I hope it will be merged quite easily. :)

**Comment by mac-cain13** [comment]
And merged this one into develop. :)

Thanks for all contributions on this one, great feature to have in R.swift!
