### ISSUE TITLE
[question] work with unavailable attribute

### ISSUE THREAD

**Issue by RishabhTayal** [mac-cain13/R.swift#384]
I am using `@available(*, unavailable, message: "Use `NewRequestListTableViewCell_v2` instead")` attribute for one of class. Upon compiling the project, I get error in `R.swift` file because the library generates code for the unavailable class as well. 

What is the right way to use `unavailable` attribute with `R.swift`?

**Comment by tomlokhorst** [comment]
Unfortunately, R.swift can't read your source code, so it doesn't know about the `unavailable` attribute.

At the moment, the only way to have R.swift _not_ generate a reference to an unavailable class, is to not reference it from your Storyboard / Nib. Or perhaps by [ignoring the file](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Ignoring.md), but I haven't tried that for this use case.

**Comment by RishabhTayal** [comment]
I will try the 'ignore the file' option. Closing the issue now. Thanks for the response.
