### ISSUE TITLE
Unable to build demo app

### ISSUE THREAD

**Issue by viktor-malieichyk** [mac-cain13/R.swift#386]
Wasn't able to build demo app after installing pods and didn't find anything about it in the readme. 
Is it even supposed to be built?

I got this error:

/Users/viktor/Library/Developer/Xcode/DerivedData/ResourceApp-gchgulduayzydycwojrywknrsywn/Build/Intermediates.noindex/ResourceApp.build/Debug-iphonesimulator/ResourceApp.build/Script-D55C6CED1B5E172900301B0D.sh: line 2: /Users/viktor/Desktop/R.swift-master/ResourceApp/../build/Debug/rswift: No such file or directory

**Comment by tomlokhorst** [comment]
The ResourceApp that's in the repo isn't really a demo app, but more of a helper app we use during the development of R.swift itself.

If you're just looking for examples of using R.swift, these should be useful: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md

If you want to work on the development of R.swift, you can use the ResourceApp project. You should be able to build it, if you first build R.swift itself via the instructions in the Readme.
