### ISSUE TITLE
[Question] Possibility to change hostingBundle

### ISSUE THREAD

**Issue by MSavisko** [mac-cain13/R.swift#390]
Hi!
Is there are a way to change generated hostingBundle to custom?
`fileprivate static let hostingBundle`

Why?
All app use R.string.localalizble.XXXX() for extracting localized string.
R file generates on every build start.
Need to change app language without additional manipulation.

Thanks in advance!

**Comment by tomlokhorst** [comment]
Would this be covered by this feature request?

https://github.com/mac-cain13/R.swift/issues/219

**Comment by MSavisko** [comment]
@tomlokhorst 
Yes, if it will be implemented as discussed in comment https://github.com/mac-cain13/R.swift/issues/219#issuecomment-293896894 and case of an enum specifically generated for the Settings.strings file will not be private.

Thanks for the answer!
