### ISSUE TITLE
Support templates

### ISSUE THREAD

**Issue by 4brunu** [mac-cain13/R.swift#391]
First of all, thanks for this amazing project.

It would be great if R.swift would support templates for the generated source like [SwiftGen](https://github.com/SwiftGen/SwiftGen#choosing-your-template) or [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

**Comment by tomlokhorst** [comment]
Can you explain what you're specifically looking for with templates in R.swift?

One of the design goals for R.swift is to be as simple as possible, zero configuration, it Just Works.
If you're looking for general purpose templates, it seems Sourcery or SwiftGen already provide that feature.

**Comment by 4brunu** [comment]
I would like to make the generated source compatible with Objective-C code, by adding some @objc annotations (not really sure if this would be possible, but since I work with mixed code bases, it would be a huge win for me)

I would also like to have some control over the instantiation of UIViewControllers from UIStoryboard to return a non optional UIViewController, otherwise throw a fatal error

So in my code I would go from this
```Swift
guard let xptoViewController = R.storyboard.xptoStoryboard.xptoViewController() else {
      fatalError()
}
```
To this
```Swift
let xptoViewController = R.storyboard.xptoStoryboard.xptoViewController()
```

Nothing major, just to have more control over the generated source, but if this doesn't fit with the design goals of R.swift I understand that 🙂 

I know that SwiftGen already does this, but it doesn't support so many types of resources as R.swift, like Reusable cells.

**Comment by tomlokhorst** [comment]
Thanks for your reply!

If the features you need are generally applicable and non-interfering (like the @objc annotations), you could send a PR and we can add it to a newer version of R.swift.

But if you're looking for general purpose templating, then Sourcery or SwiftGen might indeed be better suited to your use case.
