### ISSUE TITLE
.rswiftignore doesn't work

### ISSUE THREAD

**Issue by marekpridal** [mac-cain13/R.swift#397]
Hi, I want to implement R.swift in my project but I need to use it just for Localizable.strings file. Unfortunately I am not able to implement it with .rswiftignore file. I have .rswiftignore file in the same folder as generated R.swift file but it seems, generator doesn't use it.

**Comment by evanxie-cn** [comment]
@mac-cain13 R.swift is an amazing tool for managing resources, thank you very much. I want to ignore a whole folder, I tried several ways, but failed, can R.swift implement it?

**Comment by mac-cain13** [comment]
The file should be in the source root of your project, this probably means you need to place it next to your `xcodeproj` file. Like this: https://github.com/mac-cain13/R.swift/tree/master/ResourceApp

Does this fix the problem for you?

**Comment by marekpridal** [comment]
No, I have it next the xcodeproj and xcworkspace and it doesn't ignore any of the file declared in .rswiftignore.

**Comment by marekpridal** [comment]
My bad I should have `**/*.xsl` instead of `*.xsl`, now it's working fine, on the other hand it still doesn't ignore some PDFs.

**Comment by jshl8612** [comment]
> The file should be in the source root of your project, this probably means you need to place it next to your `xcodeproj` file. Like this: https://github.com/mac-cain13/R.swift/tree/master/ResourceApp
> 
> Does this fix the problem for you?

Hi, is it possible to ignore nib files? I failed on it.
