### ISSUE TITLE
Localized string with %f fails to generate

### ISSUE THREAD

**Issue by stuartro** [mac-cain13/R.swift#398]
I'm running into a weird issue, which I can only think is a bug:

testStringA = "%1$d of %2$i files copied, %3$f.2 completed."; // GENERATES FINE
testStringB = "%1$d   %2$f.2 completed."; // GENERATES FINE
testStringC = "%1$f.2 completed."; // FAILS TO GENERATE 

Any ideas?

**Comment by tomlokhorst** [comment]
Which version of R.swift are you using, and what is the error you're seeing?

I just copy-pasted you three lines into the .strings file of my project, and they're all picked up by R.swift.

**Comment by stuartro** [comment]
I'm using R.swift 4.0.0 with Swift 4.0 (Xcode 9.2) on macOS Sierra (10.12.6). 

I think I found the issue: In my base (en) locale I had a string using "%0.2f", while in a German localization of the same strings file I had "%d" (for the same string key). The result is that the string simply isn't generated – that is, doesn't appear in the generated R.strings.<tablename> file.

My bad. 

And, thank you for a really sweet piece of work. R.swift has made my life/work a lot easier.

Perhaps a log entry / error warning when keys couldn't be generated? Or is there already a log entry and I'm simply not logging?

**Comment by tomlokhorst** [comment]
A warning should be generated as part of the build logging, if the placeholders in the different translations don’t match.
