### ISSUE TITLE
Error when add `@available` to UIView

### ISSUE THREAD

**Issue by PH9** [mac-cain13/R.swift#400]

**Comment by tomlokhorst** [comment]
Please provide a more detailed description of your issue.

**Comment by PH9** [comment]
when App Deployment Target is 8.0.
And mark some storyboard to higher deployment target.

It will fail when build

**Comment by mac-cain13** [comment]
To help you out we really need a clear description of the error and how to reproduce the error.

I'm going to close this issue, but please feel free to open a new one with more context or add more context here, at least we need:

- The error itself
- How to reproduce it
- What you tried to fix it
