### ISSUE TITLE
R.swift error on installation: xcodeproj could not be parsed

### ISSUE THREAD

**Issue by johnnysay** [mac-cain13/R.swift#405]
Hey,

I am trying to install R.swift with the recommended CocoaPods installation. However after building my project I get this error message:

`error: [R.swift] Project file at 'file:///Users/johnny/git/aaa/bbb.xcodeproj/' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?`.

FYI there are also one submodule in the project plus one submodule including another submodule.

Thanks in advance for your answer.

**Comment by mac-cain13** [comment]
Thanks for using R.swift.

When this issue pops up there is, probably due to a merge conflict or so, a reference in the project file that isn't valid or duplicate. Often you see a red file or folder somewhere in Xcode (in the project explorer or build phases). In some cases the fault is more subtle and a bit harder to find. Could this be the cause of your issue?

Submodules should not be the problem here since R.swift doesn't interact with git at all, it just looks at your Xcodeproj file.

**Comment by johnnysay** [comment]
Thanks for your answer :)

I have followed your instructions but I still haven't succeeded in installing R.swift. Would you have some other hints? Or could I provide some more useful information?

**Comment by mac-cain13** [comment]
Could you try to install R.swift in a fresh Xcode project? That would at least validate that your method of installation is correct. 

If that works but your current project not I guess the project file isn't valid.

**Comment by phyodor2** [comment]
Hey, 

I'm having the exact same issue.

> Could you try to install R.swift in a fresh Xcode project? That would at least validate that your method of installation is correct.
> 
> If that works but your current project not I guess the project file isn't valid.

mac-cain13, unfortunately it's not possible to make a fresh project, could you please maybe give some further comments on how could this be fixed?

Thanks a lot, appreciate

**Comment by phyodor2** [comment]
Oh and yes, i've installed r.swift to other projects all okay, in this very project i was updating from 4.0.0 to 5.2.2 (pod update) and this happened

> Could you try to install R.swift in a fresh Xcode project? That would at least validate that your method of installation is correct.
> 
> If that works but your current project not I guess the project file isn't valid.
