### ISSUE TITLE
Add support for Xcode 10 localization catalog

### ISSUE THREAD

**Issue by fabb** [mac-cain13/R.swift#411]
There is a localization catalog in Xcode 10:
https://developer.apple.com/wwdc18/404

It would be nice if R.swift would support it.

**Comment by mac-cain13** [comment]
Yep, sounds like something we should support! Sounds like I should watch that session. :)

**Comment by fabb** [comment]
From Xcode release notes:
> Xcode 10 supports a new Xcode Localization Catalog (xcloc) export/import format for localization data that can contain both an XLIFF file and other localizable content such as image files. (28662326)

**Comment by fabb** [comment]
Let‘s see!

**Comment by fabb** [comment]
Ok you were right, this is just a format for exporting and importing localizations, so I‘ll close the issue.

But there‘s a new method `deferredLocalizedIntentsString` that takes a localized string key which might benefit from some R compile time safety.

**Comment by mac-cain13** [comment]
Thanks for watching out for possible new features and updating this issue. 👍

**Comment by fabb** [comment]
You‘re welcome! Thanks for maintaining this tool. Noone likes to maintain a project with string identifiers...
