### ISSUE TITLE
NibResource+UIKit.swift with Xcode 10

### ISSUE THREAD

**Issue by max-potapov** [mac-cain13/R.swift#412]
Due to API changes, this extension will not work anymore with Xcode 10. I'm getting error while building the project:
> Cannot convert value of type '[AnyHashable : Any]?' to expected argument type '[UINib.OptionsKey : Any]?'

But didn't find any usage of this method. Should it be removed?

**Comment by mac-cain13** [comment]
Thanks for reporting this, we needed to adjust our argument parameter type. This is now done on master and will be in the next R.swift release.

For now you can depend on master for things you try in the Xcode 10 beta.
