### ISSUE TITLE
Warning on external build tool configuration

### ISSUE THREAD

**Issue by frankatstyleshoots** [mac-cain13/R.swift#419]
Hello,

I have a project which uses an external build system target. The main target references this external build target in the Target Dependencies section of its Build Phases.

At compile time I get the following warning:

```
warning: [R.swift] project.pbxproj is internally inconsistent.
 - XCConfigurationList ([some id string here]) is not used
Perhaps a merge conflict?
```

The warning references the id of the XCConfigurationList associated with the PBXLegacyTarget section of the external build system target in the project.pbxproj file. Is this an R.swift issue, or is there any way to circumvent this warning? I don't think there is anything broken in the project.pbxproj file.

I'm using R.swift 4.0.0 with Xcode 9.4 (9F1027a).

Thanks!

**Comment by mac-cain13** [comment]
Could be that we detect this as an issue while it's not a problem in this case. It would mean that the `XCConfigurationList` is declared in the Xcodeproj file, but is never referenced from anywhere. I'm not sure if that is the default thing that happens with external build system targets.

It would help a lot if you can recreate the setup in a sample project so we can investigate it easier. Would that be something you could do?

**Comment by frankatstyleshoots** [comment]
I'll see if I can put something together and will update here when I do...

**Comment by frankatstyleshoots** [comment]
Here ya go!

[R.swiftTest.zip](https://github.com/mac-cain13/R.swift/files/2101438/R.swiftTest.zip)

**Comment by tomlokhorst** [comment]
Thank you for this example project!

It seems [XcodeEdit](https://github.com/tomlokhorst/XcodeEdit), our library for parsing xcodeproj files doesn't support LegacyTargets. I'll add that to the library and we'll update the R.swift dependency in the next R.swift release.

**Comment by frankatstyleshoots** [comment]
Awesome! Thank you!

**Comment by mac-cain13** [comment]
We've merged the fix, this will be in the next release!

**Comment by phehaz** [comment]
Do you have an ETA for the next release? :)

**Comment by mac-cain13** [comment]
Just released R.swift 5.0.0.alpha.1 that contains this fix.
