### ISSUE TITLE
XIB containing a single UITableViewCell does not conform to `ReuseIdentifierType`

### ISSUE THREAD

**Issue by rafaelnobrepd** [mac-cain13/R.swift#423]
Hi! Using R.swift 5.0.0-alpha1 along with Xcode 10 beta 2, whenever I have a plain `UIView` element *anywhere* in the view hierarchy, the nib is considered to have `rootViews.count != 1`, generating a cell such as this, which cannot be used in `tableView.register()`, as if there was some parsing issue. This is happening in several cells, and could be reproduced in a new XIB file as well with the most basic structure possible:

    struct _MyCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = MyCell
      
      let bundle = R.hostingBundle
      let name = "MyCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MyCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MyCell
      }
      
      func secondView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[1] as? UIKit.UIView
      }

      fileprivate init() {}
    }
![screen shot 2018-07-03 at 16 04 17](https://user-images.githubusercontent.com/20772372/42239616-d4c7e062-7eda-11e8-82a4-edc7a1b64d6c.png)

**Comment by rafaelnobrepd** [comment]
Well, in fact I couldn't reproduce on a newly created xib :( I'm trying to understand what triggers the issue exactly, it seems some rogue xml tag on the xibs/view hierarchies this particular app brought from earlier xcode versions. I'll keep digging and post back my results

**Comment by rafaelnobrepd** [comment]
I put some logging in `Nib.swift` to try to identify what my XIB files had that made `R.swift` break. This is the result of one of my failing xibs:

```
Parsing MyCell
Found rootView with name: tableViewCell
Found rootView with name: constraints
Found 2 rootViews in MyCell
Found 1 reusables in MyCell
```

Should this be added to `ignoredRootViewElements` ? Or is this a malformed XIB ?

**Comment by rafaelnobrepd** [comment]
The `constraints` tag found is deep down the hierarchy, it makes no sense.

**Comment by mac-cain13** [comment]
Hmm strange, could you share the xib file so I we can see what's up?

**Comment by rafaelnobrepd** [comment]
Ok, I found the issue! The rootView finder code that manages the tag level is handled in the default case. However the `image` and `color` cases do not update `levelSinceObjectsTagOpened`. So in some conditions the tags artificially seem to be at level 1 and are considered top level objects in the XIB. I'll try to come up with a PR fixing this

**Comment by SpacyRicochet** [comment]
I found the same issue, but in a UICollectionViewCell. It probably has the same root cause.

**Comment by abhimuralidharan** [comment]
I faced this issue today. I had to give the cell class name as the cell identifier in the cell's attribute inspector. The cell identifier column was empty.
