### ISSUE TITLE
add image xib or stroyboard  resource  by different person in one project  conflicts always coming

### ISSUE THREAD

**Issue by wmfgithub** [mac-cain13/R.swift#427]
add image xib or stroyboard  resource  by different person in one project  conflicts always coming

**Comment by mac-cain13** [comment]
It is recommended to put the generated file in your gitignore. R.swift will regenerate the file for you when you build and this will prevent conflicts in generated code. 

Alternatively; just run R.swift again. It will regenerate the file for you and solve the conflict.
