### ISSUE TITLE
Documentation on using R.swift in a cocoapod is not clear

### ISSUE THREAD

**Issue by teameh** [mac-cain13/R.swift#430]
I'm trying to integrate R.swift in my own library (which is a Cocoapod). 

According to the [docs](https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#can-i-use-rswift-in-a-library): 

> **Can I use R.swift in a library?**
> Yes, just add R.swift as a buildstep in your library project and it will work just like normal.

But in my case (because of cocoapods), I don't really have a library project of my own. The only project I have is one generated by Cocoapds. Since Cocoapods 1.4 and up there is a way to add build phase scripts but https://github.com/mac-cain13/R.swift/issues/387 indicates you don't support that yet? 

I've tried to [add generation to such a build script](https://github.com/teameh/SampleCocoapodUsingRswift/blob/original-issue/SampleCocoapodUsingRSwift.podspec#L31-L35) and was able to get it working but it's not ideal. You can find my example project [here](https://github.com/teameh/SampleCocoapodUsingRswift). To get it up and running you need to: 

```
// Clone the repo and install the pods
git clone git@github.com:teameh/SampleCocoapodUsingRswift.git && cd SampleCocoapodUsingRswift
pod install

// Try to build the app, this will fail but will run the generation script...
xcodebuild -workspace SampleApp.xcworkspace -scheme SampleApp build

// Regenerate the pod project which will now include R.generated.swift :)
pod install

open SampleApp.xcworkspace
```

Of course this is not ideal, and it only works in this example app. When other apps would include this pod as a regular pod instead of a development pod the script file [needs to be different](https://github.com/teameh/SampleCocoapodUsingRswift/blob/original-issue/SampleCocoapodUsingRSwift.podspec#L37-L42). 

Any ideas or best practises?

**Comment by mac-cain13** [comment]
Thanks for using R.swift!

What we've done for some CocoaPods is that we actually have a Xcodeproj file that we commit for the library and we work from there. An example is [tomlokhorst/SegueManager](https://github.com/tomlokhorst/SegueManager), we always work from that Xcode project during development.

For newer pods we often use Swift Package Manager to generate the Xcode project so there we would face the same problems if we want to use R.swift in the library. So I see your problem and I'm not sure if in the current state of the project you can fix this easily.

So why do the docs state that you can use it in a library? Well it does work perfectly fine if you do the setup by hand every time the project is created, in your case as a pure reusable library that will hurt, but we use that often in bigger projects where we have an app with a dedicated `Core` and `Api` library in the workspace. 

All in all I think we can improve the workflow for libraries best by automating the R.swift installation. If we do that you can easily call the installation command at some time and don't have to do the manual install or hack your own script together. @tomlokhorst did some work on that, but we've not finished it yet.

**Comment by teameh** [comment]
That makes sense. [I've added](https://github.com/teameh/SampleCocoapodUsingRswift/commit/2692e1c089f1b1a4a62c920112372c19c3295018) a 'development' xcode project (with that build script) to my sample repo and that works fine. The `R.generated.swift` is now generated when developing (and checked into git) instead of generated upon compilation in other projects. Much nicer.

The only downside of this approach I can think of is that Cocoapods does not use this project to build your library, so if the build in this project succeeds it does not mean your library builds fine in another project. But I guess that's what CI's are for. 

> All in all I think we can improve the workflow for libraries best by automating the R.swift installation.

Yes that makes sense. Keep up the good work!

**Comment by teameh** [comment]
Maybe this would improve the docs a bit https://github.com/mac-cain13/R.swift/pull/431.
