### ISSUE TITLE
String Fromat %s - Cannot invoke '...' with no arguments

### ISSUE THREAD

**Issue by kuzdu** [mac-cain13/R.swift#432]
Hi
I tried to use String Format that I can replace my values.

Example https://stackoverflow.com/a/35317237/4420355
```
let x = 1.2
let y = 2.4
let text = String(format: NSLocalizedString("From %@, %@", comment: ""), "\(x)", "\(y)")
// Or alternatively:
let text = String(format: NSLocalizedString("From %@, %@", comment: ""), NSNumber(double: x), NSNumber(double: y))
```

My concret string
`"profile_more_than_one_credit_expires_info" = "next expiry %s on %s";`

I got a `Cannot invoke 'profile_more_than_one_credit_expires_info' with no arguments`

I tried to escape the `\%s` but it hasn't any effect.

**Comment by tomlokhorst** [comment]
R.swift generates functions for each localised string, see the [examples](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#localized-strings)

The function call should have this form:

```swift
let text = R.string.yourFileNameHere.profile_more_than_one_credit_expires_info("one", "two")
```
