### ISSUE TITLE
Format Strings with String parameter

### ISSUE THREAD

**Issue by fabcarvalhal** [mac-cain13/R.swift#434]
How do I use strings like below?

`R.strings.myString("Example");`

I've tried to use the below on my .strings but no success. 
`myString = "My %s";`

The R is generating a function with an `UnsafePointer<unichar>` as parameter.

**Comment by tomlokhorst** [comment]
In .strings files, you should use a `%@` placeholder for strings.

`myString = "My %@";`

See the documentation of `NSLocalizedString` for more details.

**Comment by fabcarvalhal** [comment]
Works perfectly! Thank you.
