### ISSUE TITLE
Project doesn't recognize R

### ISSUE THREAD

**Issue by dgarcia1993** [mac-cain13/R.swift#436]
I setup the installation with Cocoapods but the project doesn't recognize the R struct yet.

The R.generated.swift is genereted and I reference the file to the project unchecking the "Copy items if needed" as the doc say, please help me with this.

![screen shot 2018-08-17 at 17 00 11](https://user-images.githubusercontent.com/34861603/44288663-17c18d00-a23f-11e8-87b1-5594f343a84c.png)

![screen shot 2018-08-17 at 17 00 31](https://user-images.githubusercontent.com/34861603/44288668-1d1ed780-a23f-11e8-8b7b-5eef39928bf5.png)

**Comment by mac-cain13** [comment]
The error doesn’t show that `R` is not found, but that you need to type something after the dot. Maybe it’s just autocomplete not doing its job?

If that’s not the case the file probably isn’t in the target, you can check this by clicking the R.generated.swift file and then at the right hand side info panel check your app target should be checked under targets. This should do the trick. 

You could also see if the contents of the generated file are indeed for resources your project to check that the generation of the file is going correctly.

**Comment by dgarcia1993** [comment]
Thanks mac-cain13 the error was check the target.
