### ISSUE TITLE
Problems with R.generated.swift

### ISSUE THREAD

**Issue by AndreyDatakam** [mac-cain13/R.swift#437]
Hello. I have some problems with R.swift. I hope I'll help me. 
macOs Sierra 10.12.6. Xcode 9.1. Swift 3.2. 

I've downloaded R.swift (3.3.0) (I have the following string   pod 'R.swift', '~> 3.3.0' in the Podfile). 
After that Podfile.lock contains the following strings:
 - R.swift (3.3.0):
    - R.swift.Library (~> 3.0.2)
  - R.swift.Library (3.0.2)

When I try to build my project, I get:
/Users/admin/Documents/AkenoriProjectNext/akenori/R.generated.swift:11:18: No type named 'Validatable' in module 'Rswift'
/Users/admin/Documents/AkenoriProjectNext/akenori/R.generated.swift:581:52: No type named 'ReuseIdentifier' in module 'Rswift'
/Users/admin/Documents/AkenoriProjectNext/akenori/R.generated.swift:581:16: Could not infer type for 'settingsDataTableViewCellID'

I'am beginner in the Xcode. Maybe You know what I do wrong. Thanks.

**Comment by mac-cain13** [comment]
If you're a beginner I for sure would advise you to use the most recent version of things. Please see if you can use Swift 4 and R.swift 4.0.0. That will prevent a lot of hairpulling.

From what you're reporting it sounds like the R.swift.Library is not included correctly. You could look up if `Validatable` can be found in the files of the R.swift.library to make sure that code is really there. Also you could retry to do the R.swift setup to make sure you did things correctly.
