### ISSUE TITLE
failed to complie

### ISSUE THREAD

**Issue by witchnana** [mac-cain13/R.swift#439]
> /var/folders/b_/crw_x7vj52g1g39w4dr5pv800000gp/T/CocoaPods-Lint-20180821-16308-ax4kba-R.swift/Pods/R.swift.Library/Library/UIKit/NibResource+UIKit.swift:22:84:
error:
 'OptionsKey' is not a member type of 'UINib'
      public func instantiate(withOwner ownerOrNil: Any?, options optionsOrNil: [UINib.OptionsKey : Any]? = [:]) -> [Any] 

> -

 ERROR | xcodebuild: Returned an unsuccessful exit code.
    - ERROR | xcodebuild:  R.swift.Library/Library/UIKit/NibResource+UIKit.swift:22:84: error: 'OptionsKey' is not a member type of 'UINib'

i cloned R.swift to my private pod, while R.swift.Library's source is still from github. 
In the terminal, i typed pod repo push, error came out. i check the code,OptionsKey is not available. Any idea?

**Comment by tomlokhorst** [comment]
The master branch of R.swift and R.swift.Library uses Swift 4.2.
If you want the Swift 4.0 compatible version, use the `v4.0.0` tag of both repositories.

**Comment by witchnana** [comment]
fixed. Thanks.
