### ISSUE TITLE
Use of undeclared type 'SearchHomeCollectionViewCell'

### ISSUE THREAD

**Issue by priyankakanojia36** [mac-cain13/R.swift#440]
Use of undeclared type 'SearchHomeCollectionViewCell'
Use of undeclared type 'SearchHomeVC'
somebody help asap
i am getting 3 errors in R generated file

**Comment by mac-cain13** [comment]
Sounds like this issue that is documented in the Q&A section: https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file

Could you see if this fixes things for you?
