### ISSUE TITLE
Issues with 5.0.0.alpha.1 

### ISSUE THREAD

**Issue by mureatencio** [mac-cain13/R.swift#442]
I've been trying to use 5.0.0.alpha.1 version, but the "Pods/R.swift/rswift" file is missing after installing the pod. Has anyone had any luck installing/using this alpha version? 
( Running on XCode 10 beta 6 / Swift 4.2 / iOS 12 sdk )

<img width="619" alt="screen shot 2018-08-28 at 12 55 52 pm" src="https://user-images.githubusercontent.com/2531394/44744388-4acb1280-aac2-11e8-8fc9-48e582e47e7e.png">

**Comment by tomlokhorst** [comment]
If you use the released version in your Podfile it should work:

`pod 'R.swift', '5.0.0.alpha.1'`

**Comment by mureatencio** [comment]
Thanks a lot!, it's working now, I was setting the pod version incorrectly.
