### ISSUE TITLE
After generate archive, R.string.localizable don't work

### ISSUE THREAD

**Issue by vitormeds** [mac-cain13/R.swift#446]
Hi, I have the following problem, after generating the file to by in the store the use of "R.string.localizable", does not work, i realized that in the first run before generating the file it does not work, to solve this, i edit the file with anything, and command to run, and it works, i do not know what might be happening, maybe it's a bug in Xcode

**Comment by vitormeds** [comment]
I changed the order in which the script was to work and it worked 

<img width="737" alt="captura de tela 2018-09-10 as 13 56 24" src="https://user-images.githubusercontent.com/12155092/45312062-7c4fcf00-b501-11e8-92c1-61eba6d793a9.png">

**Comment by mac-cain13** [comment]
I saw you comment that it now works, but it seems you deleted it. Please let me know if something is still not working for you.

**Comment by vitormeds** [comment]
Appeared was working, but came back with the same problem so i deleted the comment, was sent a print of how i am executing the script, and the podfile, thanks

<img width="740" alt="captura de tela 2018-09-12 as 08 05 26" src="https://user-images.githubusercontent.com/12155092/45421181-aec50d80-b662-11e8-8c7a-11e90e8e32ac.png">

<img width="438" alt="captura de tela 2018-09-12 as 08 06 43" src="https://user-images.githubusercontent.com/12155092/45421236-d6b47100-b662-11e8-9c79-6c8b4f4af2be.png">

**Comment by vitormeds** [comment]
I was able to solve the problem definitively, what was happening and that in the framework that I was using it used localizable, and used the default file Localizable.strings, in my project the file of strings also had that name, the solution was to change the name of the strings file in my project, it worked
