### ISSUE TITLE
Can change the generate File and Class name?

### ISSUE THREAD

**Issue by MagicalWater** [mac-cain13/R.swift#447]
ex: generate name is AA

File - AA.generated.swift

Code -
```
class AA {
...
}
```

**Comment by MagicalWater** [comment]
> Not sure about the R class name but it should be possible to rename the generated file by doing adding the following to the script phase's end:
> `mv path/to/R.generated.swift new/path/name`

thx, that worked for file name.

**Comment by tomlokhorst** [comment]
Thanks for your comment.

This is not a feature we plan on adding to R.swift.
