### ISSUE TITLE
version3 up to version4

### ISSUE THREAD

**Issue by CoderWan** [mac-cain13/R.swift#448]
i used R.swift.3，now i upgrade to 4，did as this

For R.swift 3.x and below, the rswift executable should be called with only one argument: rswift $SRCROOT
For R.swift 4, the rswift executable should be called with two arguments: rswift generate $SRCROOT

but it not work, errors are not found storyboard, xib , identity ...
if i am wrong, please help me, print detail.
tks.

**Comment by tomlokhorst** [comment]
Could you provide more details? What is the exact error message you're seeing?
