### ISSUE TITLE
Official version for Xcode 10

### ISSUE THREAD

**Issue by netbe** [mac-cain13/R.swift#449]
Hi,

I see there is an alpha version 5.0.0.alpha.2 compatible with Xcode 10. Will the 5.0.0 be officially compatible with Xcode 10?

Any ETA on the release?

Thanks,

François

**Comment by tomlokhorst** [comment]
The alpha version still has a know issue with the build system. We first want to resolve that before releasing an official version 5.0.

See: https://github.com/mac-cain13/R.swift/issues/456
