### ISSUE TITLE
Manual Install confusion

### ISSUE THREAD

**Issue by mlchild** [mac-cain13/R.swift#45]
I've dragged the unzipped R.swift-master into my $SRCROOT and attempted to run script build phase with "$SRCROOT/rswift" "$SRCROOT", but all I get is "/Users/mlchild//Developer/Project/rswift: No such file or directory".

I understand I am likely an idiot, but cannot figure this out. Prefer not to use cocoapods.

**Comment by mac-cain13** [comment]
Hi @mlchild! Thanks for giving R.swift a try! :)

The most obvious question is of course: Is the `rswift` file located at `/Users/mlchild//Developer/Project/rswift`? It looks like you've put R.swift a folder to deep or something like that.

The `$SRCROOT` variable points to the folder the `xcodeproj` file is in normally, so this should be `/Users/mlchild//Developer/Project` in your case. If you want R.swift only to detect a subset of resources you can change the buildstep to: `"$SRCROOT/rswift" "$SRCROOT/subfolder"`. You should _not_ put the `rswift` file into that subfolder.

Hope this gives some pointers to help you out. Let me know!

**Comment by mlchild** [comment]
Thanks for getting back to me! I'm not seeing the rswift file after downloading the zip— only the R.swift-master folder (within which is the R.swift folder, R.swift.xcodeproj, etc.). Do I need to change the name of the folder?

**Comment by mac-cain13** [comment]
Aah alright! You're downloading the source folder instead of the builded production ready thingy, you should use [this](https://github.com/mac-cain13/R.swift/releases/download/v0.8.4/rswift-0.8.4.zip) link from the [releases](https://github.com/mac-cain13/R.swift/releases) section.

Think that will clear things up. :)

**Comment by mlchild** [comment]
Got it! Apologies, I'm so used to downloading github zips, I didn't even think to click the link.

**Comment by mac-cain13** [comment]
Happens to the best of us! Hope you enjoy using R.swift, please let me know if you have ideas for improvements or run into something. Happy to help! :)

**Comment by justinmakaila** [comment]
@mac-cain13 I installed R.swift following the instructions from the README. I can't run the project though, because there's a line that reads `import Rswift` followed by an error saying "No such module 'Rswift'". Any advice?

**Comment by mac-cain13** [comment]
Sounds like you're using the beta version, but still followed the instructions for the latest stable version. Here are the instructions for the 1.0.0.beta versions: https://github.com/mac-cain13/R.swift/tree/release/1.0.0#installation

You basically need to include the [R.swift.Library](https://github.com/mac-cain13/R.swift.Library#rswiftlibrary----) into your project.

**Comment by justinmakaila** [comment]
@mac-cain13 nailed it. Thanks!

**Comment by mac-cain13** [comment]
:+1:
