### ISSUE TITLE
XCode 10 incremental build system

### ISSUE THREAD

**Issue by xmanu** [mac-cain13/R.swift#450]
The XCode 10 incremental build system can have problems with the R.swift script phase.
So in my case, I have a project in which the R.generated.swift is in the .gitignore.
When the CI build tool checks out the project, the R.generated.swift file does not exist (which is fine).

But as the new build system is incremental, the build might fail, even though the R.swift shell script phase actually runs before the compile phase, as the incremental system doesn't know, that the file will still be generated by the R.swift shell script.

This can be fixed by adding the generated file to the Output Files list in Xcode 10.
The Output Files section should include "${SRCROOT}/R.generated.swift".
If this is added, XCode 10 builds correctly again.

I vote for adding this information to the README, to prevent others from running into the same issue!

![Screenshot](https://user-images.githubusercontent.com/4720036/45885078-c6fd0100-bdb5-11e8-9b5c-63102df3f163.png)

**Comment by tomlokhorst** [comment]
Thanks for your comment.

Unfortunately, adding an output file isn't sufficient. With this, subsequent incremental builds won't run the R.swift build step, and the R.generated.swift file won't be updated again until the next clean build.

Further details here: https://github.com/mac-cain13/R.swift/issues/456
