### ISSUE TITLE
Support for Data Assets

### ISSUE THREAD

**Issue by 417-72KI** [mac-cain13/R.swift#454]
###  Introduction
**Asset Catalog** supports **Data Assets** from **macOS 10.11/iOS 9.0**.
**Data Assets** can use with `NSDataAsset`.

Here is a document.
https://developer.apple.com/documentation/uikit/nsdataasset

#### Now
I'm using `animation.gif` in `Assets.xcassets` with below.
```swift
if let asset = NSDataAsset(name: "animation.gif") {
    let data = asset.data
    let animationImage = imagesFromAnimationGif(data)
}

func imagesFromAnimationGif(_ data: Data) -> UIImage {
    // parse data
}
```
#### Hope
I want call `animation.gif` via R.swift like below.
```swift
let data = R.data.animation_gif
let animationImage = imagesFromAnimationGif(data)
```

**Comment by giulio92** [comment]
I would also like this feature!

**Comment by isaac-weisberg** [comment]
In real programming, usage of Data Assets is immensely rare, and right now, for the first time in 5 years I would've had use of this feature, probably for the last time in my life :)
