### ISSUE TITLE
UICollectionView register xib is not work!

### ISSUE THREAD

**Issue by xuhongfei** [mac-cain13/R.swift#457]
Cannot invoke 'register' with an argument list of type '(_R.nib._ECGoodsSearchHeaderView, forSupplementaryViewOfKind: String)'

![image](https://user-images.githubusercontent.com/3990919/46724910-953cd300-ccad-11e8-8fb3-e1230428fbde.png)

![image](https://user-images.githubusercontent.com/3990919/46724753-4abb5680-ccad-11e8-886d-5e66be61e8ee.png)

**Comment by AttilaTheFun** [comment]
I'm having this issue with table view cells as well.

**Comment by xuhongfei** [comment]
> I'm having this issue with table view cells as well.

It's just header view or footer view not work! @AttilaTheFun

**Comment by tomlokhorst** [comment]
Unfortunately, header and footer views are currently not supported.

There is an open issue for adding this feature: https://github.com/mac-cain13/R.swift/issues/144
