### ISSUE TITLE
In macOS 10.14 Xcode 10.0, R.generated.swift was always changed

### ISSUE THREAD

**Issue by YiYiZheng** [mac-cain13/R.swift#458]
In macOS 10.14 Xcode 10.0, the file `R.generated.swift` was always changed after build successfully despite no image or xib added.

The confuse part is git would observe the changed file.

Is it normal? 

Thanks!

**Comment by lammertw** [comment]
I'm having the same problem.

**Comment by mac-cain13** [comment]
Strange, this should normally not happen. Could you give an example of the diff between builds?

**Comment by YiYiZheng** [comment]
![screenshot](https://user-images.githubusercontent.com/43005999/47400688-d97da800-d770-11e8-91eb-5f71be7cb4fc.png)
From the screenshot, you can see it. The + and the - are the same image. It is part of the diff.

**Comment by mickamy** [comment]
@tomlokhorst 
So when would it be?

**Comment by mac-cain13** [comment]
5.0.0.alpha.3 is now released, this should fix this issue, please comment on this issue if this is still the case.
