### ISSUE TITLE
Unable to R.generated.Swift file manually 

### ISSUE THREAD

**Issue by bshashi1010** [mac-cain13/R.swift#461]
I'm trying to add R.generate.swift file to my project and im getting error show in screen short
![screen shot 2018-10-24 at 4 24 51 pm](https://user-images.githubusercontent.com/44433394/47425959-7e1bdc00-d7a9-11e8-8223-befa1df42722.png)

If anybody have any solution please suggest me, thanks in advance

**Comment by OdNairy** [comment]
It's looks like you have setup r.swift in a wrong way. Show you build script step, please.
Technically, it seems that issue is connected with space in your project directory name and have to be shielded with " symbols.

**Comment by mac-cain13** [comment]
If this still is an issue, please create a new issue with the content of your Build Phase please.
