### ISSUE TITLE
Different target with different generated file

### ISSUE THREAD

**Issue by nealsun** [mac-cain13/R.swift#465]
My project have several targets with different UI, it's no problem for colors and images in one generated file, but xib and storyboard associated with `View` and `ViewController` classes, it's conflict in these targets.

**Comment by tomlokhorst** [comment]
Could you provide some more details about your setup?

It should be possible to create a different `R.generated.swift` file for each of your targets.
R.swift should automatically find the exact resources you use in each target from the Xcode project file.

**Comment by nealsun** [comment]
It's a normal project, should I add build phases in every target？

**Comment by MrFuFuFu** [comment]
In my case. I built all Run Script in every target. I have a Today Extension. And shared all resources with the main target.

**Comment by tomlokhorst** [comment]
Indeed, a build phase should be added to each target. 

Let us know if this doesn't work for you @nealsun
