### ISSUE TITLE
Dynamic localization

### ISSUE THREAD

**Issue by NeverwinterMoon** [mac-cain13/R.swift#466]
It looks like `R.swift` doesn't support dynamic localization. Is this support planned for the future?

Currently, I am using `SwiftGen` and have something like this in the template that generates the code for localizable String constants:

```
private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let locale = UserDefaults.standard.userLocale
    let format: String
    switch locale {
      case .en:
        format = NSLocalizedString(key, comment: "")
      default:
        let bundle = LocalizationsManager.shared.bundle(forLocale: locale)
        format = NSLocalizedString(key, bundle: bundle, comment: "")
    }

    return String(format: format, arguments: args)
  }
```

So the app language is independent of the OS language and can be changed dynamically in the app and the selected value is stored in UserDefaults. Then the localization bundle is selected based on that.

**Comment by tomlokhorst** [comment]
Yes, this is a feature we want to add in the future, see https://github.com/mac-cain13/R.swift/issues/219

**Comment by NeverwinterMoon** [comment]
@tomlokhorst Aha, thanks for the info. Great to know! `SwiftGet` does appear a bit cumbersome, so I was thinking of switching to `R.swift`, but I do need at least this feature before I do that...

**Comment by tomlokhorst** [comment]
Closing this issue, see #219 for updates on this feature request.
