### ISSUE TITLE
Support for colors in the "System" catalog that Xcode adds itself

### ISSUE THREAD

**Issue by rist** [mac-cain13/R.swift#471]
I'm using 5.0.0.rc1 and get the error " [R.swift] Color named 'gridColor' is used in storyboard 'CredentialsViewController', but couldn't be loaded." when running ```R.validate()```

When searching for gridColor in my xibs and storyboards I find ```<color key="backgroundColor" name="gridColor" catalog="System" colorSpace="catalog"/>``` and assume this is added by interface builder.

**Comment by mac-cain13** [comment]
Interesting, I don't see this color currently in my xibs. Do you know/could you figure out what triggers that this color is added? So that we can reproduce and fix it.

**Comment by rist** [comment]
I have it in some files and our project is quite big and several years old. 
I see the same thing in lots of iles in github https://github.com/search?utf8=%E2%9C%93&q=gridcolor+extension%3AXib&type=Code&ref=advsearch&l=&l=XML

**Comment by mac-cain13** [comment]
Interesting, think we should take the `catalog` into account and assume things are okay if it is the "System" catalog.
