### ISSUE TITLE
Support for NSPersistentContainer？

### ISSUE THREAD

**Issue by shelldonhu** [mac-cain13/R.swift#473]
Any consideration about adding support for NSPersistentContainer?
When using Core Data, I should write this code:
`let container = NSPersistentContainer(name: "CoreDataModelNameString")`

**Comment by mac-cain13** [comment]
`NSPersistentContainer(name: "CoreDataModelNameString")` starts doing a lookup in different places, if you want to be sure a specific model is loaded you should use `NSPersistentContainer(name:managedObjectModel:)`. This will make sure iOS will always load that one specific model.

An `NSManagedObjectModel` can be initialised with an `URL`, I think that is something we can look into; if the CoreData model could be available in `R.file` so we have reference to the URL.

This is not super easy as the `xcdatamodeld` file is a compiled resource that in the _Build Phases_ sits in between the Swift files under _Compile Sources_. So it's converted and then placed in a specific place. For this to work R.swift should implement specific logic.

**Comment by mac-cain13** [comment]
I'm closing this one, if someone would like to have `xcdatamodeld` files available through R.swift feel free to open a new issue with a reference to this one. Also a PR would then be highly appreciated.

Not opening an issue now since it's not so easy to implement and is not asked for that often.
