### ISSUE TITLE
optionsOrNil produce error and warnings

### ISSUE THREAD

**Issue by ntnmrndn** [mac-cain13/R.swift#474]
Hi,

I just tried to upgrade to the 5.0 release, but got an error:

```
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _PlaybackCell.validate()
    }
    
    struct _DebugPanelViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "DebugPanelViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView //<== Cannot convert value of type '[UINib.OptionsKey : Any]?' to expected argument type '[NSString : Any]?'
      }
      
      fileprivate init() {}
    }
      
```

Any idea what's going on ?

**Comment by tomlokhorst** [comment]
You'll also need to update the R.swift.Library to version 5.0

**Comment by ntnmrndn** [comment]
@tomlokhorst I think I did:

See the Podfile update log :
```
Installing R.swift 5.0.0 (was 4.0.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing R.swift.Library 5.0.0 (was 4.0.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
```

**Comment by tomlokhorst** [comment]
Could you try deleting the R.generated.swift file, and doing a complete clean build?

Your example code looks to be generated by an earlier version of R.swift.

**Comment by ntnmrndn** [comment]
@tomlokhorst Thanks for your help ! 

On my first pod install the issue was an old R.swift generated file lingering around
On my second one, I forgot to update to Swift 4.2

**Comment by macdrevx** [comment]
@tomlokhorst I'm seeing this as well. I installed with cocoapods 1.6.0.beta.2. The generated R.swift.Library target has Swift Language Version set to Swift 4 at the target level, overriding Swift 4.2 at the Pods project level. If I manually change this to Swift 4.2 (just for this target), the error goes away. Perhaps there should be a `swift_version` specified in the podspec?

**Comment by macdrevx** [comment]
And I suppose that'd actually be on the R.swift.Library podspec.

**Comment by macdrevx** [comment]
Here's what I'm using for a workaround for now:

```
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'R.swift.Library'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end
        end
    end
```

**Comment by tomlokhorst** [comment]
Is your main project Swift 4.2 or Swift 4?

In my projects, the generated target is 4.2, but so are all my projects.

**Comment by macdrevx** [comment]
Main project is 4.2.
