### ISSUE TITLE
duplicate extention on build

### ISSUE THREAD

**Issue by KingOlami** [mac-cain13/R.swift#478]
Hi, awesome library. I noticed that every time I build or run the application, this is always duplicated and leading to an error so, I have to delete it manually every time 

```
extension R {
	// Don't have to type R.string.localizable everytime  
	typealias text = R.string.localizable  
}
```

any fix for this issue?

I am running the latest version 5

**Comment by tomlokhorst** [comment]
I don't quite understand your issue.

Is this code you've written yourself?
Is there some code that is generated in duplicate in your project? 

Could you provide more details on your project setup?

**Comment by KingOlami** [comment]
yes. the code I posted is generated in duplicate 

This

```
extension R {
	// Don't have to type R.string.localizable everytime  
	typealias text = R.string.localizable  
}
```

**Comment by tomlokhorst** [comment]
The example you posted is not code that is generated by the `rswift` tool. 

Are you sure you don't have some other build step or script that is generating that extension?
