### ISSUE TITLE
Ignore different files in different schemas\configurations

### ISSUE THREAD

**Issue by mkubista** [mac-cain13/R.swift#486]
In our project, which have multiple targets and multiple build configurations, we run into the issue with EXCLUDED_SOURCE_FILE_NAMES settings. We are excluding some files for production builds (and some parts of source codes). 

When we dont add ignore file, there is a problem with production build. If we add the global ignore file, the error is in our develop instance build.

I think, that R should have its own mechanism for selective ignore, or it should check EXCLUDED_SOURCE_FILE_NAMES for automatic ignore.

Or mI missing something?

**Comment by tomlokhorst** [comment]
R.swift uses all files from a target when generated the R struct.

It doesn't have support for EXCLUDED_SOURCE_FILE_NAMES (pull requests for new features are welcome!)

Thinking about this; Maybe it's possible to generate a [ignore file](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Ignoring.md) based on the EXCLUDED_SOURCE_FILE_NAMES variable?

**Comment by mac-cain13** [comment]
I've not used this Xcode feature myself, so to be clear; @mkubista you're excluding resources like images/xibs/storyboards from a certain configuration by putting them into `EXCLUDED_SOURCE_FILE_NAMES`?

Are you using this to build different variants of your app (like white-labeling)? Or is it to exclude some development features from the production build?

If you don't have too many variations a workaround could be to adjust the R.swift invocation in such a way that in production you do pass the ignore file and in debug you don't.

**Comment by mkubista** [comment]
> I've not used this Xcode feature myself, so to be clear; @mkubista you're excluding resources like images/xibs/storyboards from a certain configuration by putting them into `EXCLUDED_SOURCE_FILE_NAMES`?
> 
> Are you using this to build different variants of your app (like white-labeling)? Or is it to exclude some development features from the production build?
> 
> If you don't have too many variations a workaround could be to adjust the R.swift invocation in such a way that in production you do pass the ignore file and in debug you don't.

We are excluding some developer features from production builds - like some dialogs for switching REST API endpoint, extended logging of all API calls and other features.

So the solution you are proposing will work, if I check the current build configuration in script and pass ignore file as parameter. The slight flaw is, that we must remember to update ignore file when we will exclude other resources.
But it could be made by script.
