### ISSUE TITLE
Disable R.swift warnings

### ISSUE THREAD

**Issue by Anhelme** [mac-cain13/R.swift#496]
How can I disable warnings from R.Swift in Issue Navigator of XCode
All warnings start with `[R.swift] `, I need hide them in IssueNavigator, but other warnings must be visible

**Comment by mbernson** [comment]
Currently, there isn't a way to disable these warnings as far as I know. What kind of warnings would you like to disable? 
If there's a resource that can't be parsed or is missing, you would want to know about it, right?

**Comment by mbernson** [comment]
There is also another issue about refactoring the warnings: #136

**Comment by mac-cain13** [comment]
Thanks for letting us know this is a wish. To be honest, it's not something that has priority at the moment.

Lets track this issue further in #136 as @mbernson noted silencing warnings is als mentioned there. It would really help if you @Anhelme would comment in that issue _why_ you want to hide the warnings.
