### ISSUE TITLE
Custom Class incompatibility with R.Swift used in Unit Tests

### ISSUE THREAD

**Issue by nysander** [mac-cain13/R.swift#500]
Version used: 5.0.2

When I set Custom Class > Class in Storyboard I got error from compiler:

> Use of undeclared type 'xxxViewController' 

![image](https://user-images.githubusercontent.com/753327/54687458-e504ad80-4b1b-11e9-8071-8df611c58d0b.png)

when I remove it as below:
![image](https://user-images.githubusercontent.com/753327/54682434-365a7000-4b0f-11e9-94c6-24ce2794ce95.png)

I got broken outlet and action connections:

![image](https://user-images.githubusercontent.com/753327/54682608-b08af480-4b0f-11e9-905b-50a8865dd5fc.png)

and I get SIGABR panic when running app and test case

**Comment by mac-cain13** [comment]
Could you check if the Module is set correctly, it sounds like the Module is not set in interfacebuilder and therefore R.swift does not add the correct import statement at top of the generated file.

See also: https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file

**Comment by nysander** [comment]
I have there checked checkbox inherit from target.

**Comment by nysander** [comment]
When I uncheck "Inherit Module From Target" and write my main target "xxxMap" in Module field and leave valid class in field above I get: 

![image](https://user-images.githubusercontent.com/753327/54720874-d68cb500-4b60-11e9-8f93-4e36d5877ea6.png)

error shows twice per ViewController (I have 2 views controller's on storyboard ATM)

**Comment by nysander** [comment]
docs need to be fixed

to make my project compile with R.Swift I needed to change my Build Phase script to:

```
"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/[MAIN TARGET]/R.generated.swift"
```

and Output Files to

```
"$SRCROOT/[MAIN TARGET]/R.generated.swift"
```

Swift 4.2
Xcode 10.1

**Comment by mac-cain13** [comment]
Ah, sounds like you missed the upgrade instructions from R.swift 4 to 5: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-50

Any suggestions how we could improve this documentation so it's harder to miss?

**Comment by nysander** [comment]
Well for me this is not upgrading. I just started to use v5.0.2 for the first time. So I did not searched for any upgrade path.
