### ISSUE TITLE
Custom path is not supported $SRCROOT/[YOUR_PATH]/R.generated.swift

### ISSUE THREAD

**Issue by ildarsharafutdinov** [mac-cain13/R.swift#501]
hi,

I've followed https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md and found out that custom file path is not supported.

The output is generated if and only if file path is exactly `$SRCROOT/gen/R.generated.swift`.
E.g. this `$SRCROOT/gen/R.generated.swift` doesn't generate any output.

This used to work in 4.x, but not in 5.x.

**Comment by nysander** [comment]
you have to use same path in script definition and in output files, see #500

**Comment by tomlokhorst** [comment]
You need to configure both the argument to the executable, and the path in Output Files, and they need to point to the same file. As the documentation says.
