### ISSUE TITLE
Swift 5 / Xcode 10.2 compatibility

### ISSUE THREAD

**Issue by nysander** [mac-cain13/R.swift#502]
R.Swift generates lot of compiler warnings after update to Xcode 10.2. It does not matter if swift version is 4.2 or 5.0 warnings are the same:

```
.../Pods/R.swift.Library/Library/UIKit/UIStoryboard+StoryboardResource.swift:20:3: 'public' modifier is redundant for initializer declared in a public extension
```

and many more files

**Comment by mac-cain13** [comment]
These warnings are now fixed and a new release of the library has been published. You can get rid of the warnings by running:

```
pod update R.swift.Library
```
