### ISSUE TITLE
How Can I Use *.clr with R.Swift?

### ISSUE THREAD

**Issue by lynulzy** [mac-cain13/R.swift#503]
I'm using R.swift 5，
File, Image, Font all worked well but Colors struct was missed.
This was what I did:
I created a color pallet file (Using Apple Color Tool) and add to project then rebuild the project.

**Comment by tomlokhorst** [comment]
R.swift 5 no longer supports color pallet files, see the release notes: https://github.com/mac-cain13/R.swift/releases/tag/v5.0.0

R.swift 4 was the last version to support .clr files.
It is advised to use Color assets in an Asset catalog instead.
