### ISSUE TITLE
Error building project under tvOS

### ISSUE THREAD

**Issue by hintoz** [mac-cain13/R.swift#508]
When building under tvOS, a file with `if #available` for iOS is generated. Because of this, in some cases it is not possible to build the project, for example:
![Снимок экрана 2019-04-02 в 14 04 49](https://user-images.githubusercontent.com/1215299/55398172-8d6d3580-5550-11e9-90b5-48daef3da4e4.png)

I can enable _Legacy Build System_ and after an error change in the file `R. generated.swift` `if #available(iOS 11.0, *)` on `if #available(tvOS 11.0, *)` and it is not regenerated yet to make _Clean_. But I would like that to work all on the _New Build System_.

**Comment by mac-cain13** [comment]
That's a bug indeed, the `#available` condition should also check for tvOS 11+. I've fixed this in commit 0b041d0, it will be in the next release.
