### ISSUE TITLE
Rswift does not generate font files.

### ISSUE THREAD

**Issue by zero-tolerance0** [mac-cain13/R.swift#510]
I get an Xcode error while building my project saying: 

R does not have no member 'file'.
I use that member file in this func:
public static func loadCustomFonts() {
      let fontUrls: [URL?] = [
        R.file.sfuiDisplayBoldSFUIDisplayBoldOtf.url(),
        R.file.sfuiDisplaySemiboldSFUIDisplaySemiboldOtf.url(),
        R.file.sfuiDisplayHeavySFUIDisplayHeavyOtf.url(),
        R.file.sfuiDisplayLightSFUIDisplayLightOtf.url(),
        R.file.sfuiDisplayRegularSFUIDisplayRegularOtf.url(),
      ]
      fontUrls
        .compactMap { $0 }
        .forEach { CTFontManagerRegisterFontsForURL($0 as CFURL, .process, nil) }
    }
The problem is after updating Rswift does not generate file struct which used to be generated fun when using Rswift version ~> 4.0 and used to look like this:

  struct file {
    /// Resource file `(SFUIDisplay-Bold)SF-UI-Display-Bold.otf`.
    static let sfuiDisplayBoldSFUIDisplayBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "(SFUIDisplay-Bold)SF-UI-Display-Bold", pathExtension: "otf")
}

I used to have Rswift version: github "mac-cain13/R.swift.Library" ~> 4.0
however after updating it to github "mac-cain13/R.swift.Library" ~> 5.0

So now in order to project build fine I copy paste that pice of code "file". However Rswift does not generate it for me. Please help how it can be figured out to fix this issue of non generating font files for my application. Thanks.

**Comment by mac-cain13** [comment]
Few question to check your setup is correct:

- Have you adjusted the Build phase that runs R.swift? See https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-50
- Could you please check if the R.swift.Library and R.swift itself are both at the latest 5.0 version?
- I understand the fonts are missing under `R.file`, but are the fonts available under `R.font`? (If so you might be running into https://github.com/mac-cain13/R.swift/issues/498)

**Comment by zero-tolerance0** [comment]
@mac-cain13 thanks for responce,
1) yes, rswift is totally adjusted 
2) yes
3)yes, R.font is available.

**Comment by mac-cain13** [comment]
Okay, so this is indeed issue #498 that needs to be fixed.
