### ISSUE TITLE
build from source failed

### ISSUE THREAD

**Issue by nealsun** [mac-cain13/R.swift#515]
I gonna build rswift from source,  but try 
`swift build -c release -Xswiftc -static-stdlib -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.11"`, 
 I got `symbol(s) not found for architecture x86_64`.
my macOS version is 10.14.4 and Xcode is 10.2.1

**Comment by nealsun** [comment]
fixed by using swift 4.2 toolchain

**Comment by kenyth** [comment]
Just FYI. I encountered this issue as well.

Aside from going back to swift 4.2 toolchain. Using swift 5 you can also remove the `-Xswiftc -static-stdlib` part:
`swift build -c release -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.11"`

And I didn't succeed building from XCode following guide described in README.md:

>For developing on R.swift in Xcode, run `swift package generate-xcodeproj --xcconfig-overrides RswiftConfig.xcconfig`. 

The following errors occurred when using the XCode archived binary rswift with my project:

> dyld: Library not loaded: @rpath/RswiftCore.framework/Versions/A/RswiftCore
>   Referenced from: /Users/XXXX/Workspaces/Xcode/XXXX/Pods/R.swift/rswift
>   Reason: image not found
> /Users/XXXX/Library/Developer/Xcode/DerivedData/XXXX-XXXXX/Build/Intermediates.noindex/DemoBaby.build/Debug-iphoneos/XXXX.build/Script-XXXX.sh: line 3: 38683 Abort trap: 6           "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/Generated/R.generated.swift"
> Command PhaseScriptExecution failed with a nonzero exit code
