### ISSUE TITLE
Rswift and swinject in same project aren't working

### ISSUE THREAD

**Issue by Artemm208** [mac-cain13/R.swift#522]
I ran into a weird problem. I can't use R.swift and Swinject in a same project!

For the purity of the experiment, I created a new project and through Carthage added R.swift and everything worked fine. But as soon as I added Swinject the project did not even try to build with error:

```
/Users/sergeyborovikov/Library/Developer/Xcode/DerivedData/RswiftTest-adnwenoibwjahvbqwvkndylzsnse/Build/Intermediates.noindex/RswiftTest.build/Debug-iphonesimulator/RswiftTest.build/Script-EC3DE44A228A88AE00F9AB86.sh: line 3: /Users/sergeyborovikov/Documents/Repositories/RswiftTest/rswift: No such file or directory
```
```
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by mac-cain13** [comment]
The R.swift tool is not available through Carthage since it is not a library (but a build tool/step), are you sure R.swift is actually working before you add Swinject?
