### ISSUE TITLE
Command /bin/sh failed with exit code 137

### ISSUE THREAD

**Issue by tbfungeek** [mac-cain13/R.swift#523]
Hello  I use R.Objc in my self  project ，when i buid  i told me as follows: it work well before, this only happen  today, when i uncomment this script the project buid success

..................../Xcode/DerivedData/IDLFundation-ecijtfsbqjbuipappprlfcolesca/Build/Intermediates.noindex/IDLFundation.build/Debug-iphonesimulator/IDLFundationTest.build/Script-E5760FF8225F39550029B612.sh: line 3: 10488 Killed: 9               "${PODS_ROOT}/R.objc/Robjc" -p "$SRCROOT" --skip-themes --skip-storyboards --skip-segues -e "$SRCROOT/Pods"
Command /bin/sh failed with exit code 137

**Comment by mac-cain13** [comment]
This is R.swift, you can find R.Objc over here: https://github.com/SysdataSpA/R.objc
