### ISSUE TITLE
Multi project workspace support

### ISSUE THREAD

**Issue by catt-stefano** [mac-cain13/R.swift#524]
Hi,
I would like to use this (awesome) library in my multi module project.
I have a core module, various feature modules (depending on the core module) and an app module (depending on the features).
I have most of the resources that I would like to access with R.swift in the core module, so I setup R.swift for that module, set a public access level and I can access my core R struct from every module. This is working fine and is already a step up from my previous codebase.
If I try to setup R.swift for a Feature module, the newly generated R struct for the feature shadows the one from the core module, so I lose access to the core module resources.
I guess everything would work if I could someway set a different name or a prefix for the generated struct name, even if it meant knowing what module is the provider of a certain resource when we access it.
For example I would access core resources with CoreR.image.arrow() and FeatureR.image.heart() fro the feature resources.
Or maybe even better with R.core.image.arrow() and R.feature.image.heart() (I guess this could be achieved with extensions)

Is this something that could be supported by R.swift? Is it already achievable with customization?

Thanks

**Comment by mac-cain13** [comment]
I personally do not use this at the moment, but you can generate a public `R` struct by passing `--accessLevel public` to the generate command. That would be a start, but you can't currently rename the `R` struct to something like `CoreR`.

See also: https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#can-i-use-rswift-in-a-library

**Comment by highborncow** [comment]
You can use ModuleName.R to access a specific module R.generated.
