### ISSUE TITLE
Is it necessary for R.swift.Library to be added if R.swift is added using Homebrew?

### ISSUE THREAD

**Issue by losernobody** [mac-cain13/R.swift#527]
I have added R.swift to my computer using Homebrew and I am able to generate `R.generated.swift`.

The generated `R.generated.swift` has line to import `Rswift` which was resolved by installing `R.swift.Library` using Carthage.

The README contains the following line
> R.swift is a tool used in a build step, it is not a dynamic library.

Is there a way to use R.swift without linking/embedding any frameworks like it is done in [Shark](https://github.com/kaandedeoglu/Shark) or is it necessary to add `R.swift.Library` framework?

**Comment by mac-cain13** [comment]
Yes, the generated Swift file depends on the R.swift.Library, it contains datatypes it needs.

This prevents the generated file from containing extensions etc.
