### ISSUE TITLE
Error in R.generated.swift "Reference to generic type..."

### ISSUE THREAD

**Issue by npocmo** [mac-cain13/R.swift#530]
Xcode 10.2.1
R.swift 5.0.3

I am loading UIView into another UIView, which both have a xib file. First UIView is specifying second UIView Type using generics. It works fine, if I am not using R.swift.
![image](https://user-images.githubusercontent.com/23473411/60165060-f4705280-97fe-11e9-9af8-c79463394007.png)

With R.swift I am getting two compile errors:
![image](https://user-images.githubusercontent.com/23473411/60164188-68a9f680-97fd-11e9-845b-6480479ae30e.png)
![image](https://user-images.githubusercontent.com/23473411/60164663-4664a880-97fe-11e9-8c33-a5011e522a5d.png)

Any ideas of solving this problem?

**Comment by tomlokhorst** [comment]
Hmmm... I've never done anything with generic view controllers together with xibs. So this is something new.

Does your code work, if you're not using R.swift?

**Comment by npocmo** [comment]
yes it does. I have a simple ViewController, which sets view to ParentContentView. After that ParentContentView sets his contentView to ChildContentView. To make it more flexible, I am using generics. 
Unfortunately R.swift seems not to work with this idea.

**Comment by npocmo** [comment]
Sorry, my example project wasnt quite correct. Its not going to work, if you are using xib files. Workaround is to write whole view in code.

For more information: https://stackoverflow.com/questions/28258850/swift-generic-uiview-subclass-with-protocol-issue
