### ISSUE TITLE
Does this library supports components in the storyboard?

### ISSUE THREAD

**Issue by Ricardo1980** [mac-cain13/R.swift#532]
Helllo,

When using UILabel, UITextField or similar in my storyboard, is there any way to use this library without having to write code?
I mean, here:
![Screenshot 2019-07-18 at 14 31 59](https://user-images.githubusercontent.com/738681/61461651-0ad67d80-a969-11e9-8bb9-30afc414e9ec.png)

Otherwise, what approach do you follow? Thanks a lot.

**Comment by tomlokhorst** [comment]
Unfortunately no. 

R.swift helps with statically typed Swift code. So it always involves writing code.
So that's why I always end up creating .swift files, even for really simple views and view controllers.

**Comment by Ricardo1980** [comment]
Is it possible to create an extension for those components using IBDesignable or maybe using the "User Defined Runtime Attributes" for achieving what I want?

And, what people do in this case?

Thanks.

**Comment by mac-cain13** [comment]
Think it would be possible, but this is out of scope of R.swift I think. Since the goal of R.swift is helping you to avoid stringly typed code by generating and checking code for you.
