### ISSUE TITLE
What about UIViewController with Nib?

### ISSUE THREAD

**Issue by eikebartels** [mac-cain13/R.swift#54]
I don't think it is not possible yet to initial an UIViewController with nib file like the example below. 

```
/// Old way 
SelectPlanViewController(nibName: "SelectPlanViewController", bundle: nil)

/// Should be 
SelectPlanViewController(nibName: R.nib.selectPlanViewController.nibName, bundle: nil)

/// or even as extensions from UIViewController 
SelectPlanViewController(rResource: R.nib.selectPlanViewController)

```

What do you think about it?

**Comment by mac-cain13** [comment]
Good point! Thanks for suggesting this addition, definitely something R.swift should support. I think I'll prefer an extension method that is like `SelectPlanViewController(nib: R.nib.selectPlanViewController)`.

I will put this in a near future release!

**Comment by mac-cain13** [comment]
This is in develop now, will be in the R.swift 0.9.0 release! :)

**Comment by eikebartels** [comment]
Well done! Thank you for the implementation! :+1:
