### ISSUE TITLE
How to use R.swift generated strings in XCUITests?

### ISSUE THREAD

**Issue by szymon-kazmierczak** [mac-cain13/R.swift#543]
As the title says, is it possible to use R.swift generated strings in XCUITests and if yes, how does one do that?

**Comment by mbernson** [comment]
Hi,

A way to get this done is by using the `--generateUITestFile` flag in R.swift 5.1.0 alpha 4. This feature is still in development - we're using it in one of our projects to generate an R.swift struct containing only the **accessibility identifiers** from our app XIB's. 
In the UI tests, we only use the accessibility identifiers to reference UI elements on the screen.
It doesn't output the user-facing strings to this second generated file, though. 

Example command for the 'Run script' phase in your app target:

```
"$PODS_ROOT/R.swift/rswift" generate --generateUITestFile "$SRCROOT/MyAppUITests/R.generated.swift" "$SRCROOT/MyApp/Resources/R.generated.swift"
```

**Comment by szymon-kazmierczak** [comment]
I just had a look at it, and it looks very good! 
Any idea if it would be possible to extend that functionality to export UITestFile that contains only strings? We use R.swift for everything so the file is super bloated and the there are references to classes that are not available in the UI test bundle.

**Comment by mac-cain13** [comment]
That is exactly what `--generateUITestFile` is doing, generating a separate file containing only the *accessibility identifiers* available in your storyboards/xibs.

**Comment by szymon-kazmierczak** [comment]
Yeah it generates the accessibility identifiers, but what i need are the strings :D 

I had a look at the source code and noticed that it might be possible to pass the generators instead of hardcoding it to always return acc Ids?

So rather than just using --generateUITestFile, maybe pass in a comma separated list of generators to make it more customisable? 

Either that or always extract the accessibility IDs and strings :D I find that a lot of people access/verify strings in their UI tests.

**Comment by mac-cain13** [comment]
UI tests run in a separate target/app so you can't resolve localized strings in your UI tests, because you can't access the `.strings` files and don't know what localization the app under test is currently using.

How are you verifying localized strings currently in your UI tests (without the help of R.swift)? That might be good inspiration on how R.swift can help.

**Comment by szymon-kazmierczak** [comment]
I'm in the process of migrating from EarlGrey1(XCTest-based) to EarlGrey2 (XCUITest-based). KIF is also XCTest based.
XCTest based tools can access the app under test as they run in the same target/app. XCUITest is sadly a separate app/package, so I'm trying to figure out a solution to still be able to access the strings, rather than refactor the selectors :)

**Comment by mac-cain13** [comment]
Yeah, including the strings files would make it possible, but then still you're not per se using the same locale for example. So I think this is something you could setup yourself, but I'm not sure it's something R.swift should support out of the box.

**Comment by fmurtadho** [comment]
@szymon-kazmierczak does adding Localizable.strings to the UI Test Target suppose to generate the strings ?

**Comment by ast3150** [comment]
For my purposes, I've been able to use R.string.localizable data in UI tests simply by adding 

`cp "$SRCROOT/R.generated.swift" "$SRCROOT/MyUITests/R.generated.swift"`

to the R.swift build phase script, adding the output path, and adding the .strings files to the UI test target.
