### ISSUE TITLE
Colors added in IB from a separate Pod always fail tests, but still work when running

### ISSUE THREAD

**Issue by bclymer** [mac-cain13/R.swift#544]
When applying a color from an Asset Catalog that exists in another Pod to an element in Interface Builder, the test that gets created to validate that the color can be loaded will always fail. 

The problem stems from the fact that it's assumed the color exists in `R.hostingBundle`, which isn't the case when the Asset Catalog exists in another Pod. However, the `.xib` or `.storyboard` file does nothing to help the situation, because there is no indication of the bundle the color exists in. Surprisingly, despite the IB file not having that information, the color loads perfectly at runtime. 

<img width="708" alt="Screen Shot 2019-08-21 at 09 38 14" src="https://user-images.githubusercontent.com/538433/63441800-9a070300-c3f7-11e9-8a3a-57914aa83f85.png">

I have included a sample app, `RSwiftColors` (at the bottom) that will reproduce the issue if you run the tests. The line that fails is
```
UIKit.UIColor(named: "CoolColor", in: R.hostingBundle, compatibleWith: nil) == nil
```
At first I thought maybe colors are special, and passing a `nil` bundle will result in the framework searching for the color, it seems like that's what IB is doing anyway.
```
UIKit.UIColor(named: "CoolColor", in: nil, compatibleWith: nil) == nil
```
That fails too. However, specifying the correct bundle works as you would expect
```
UIKit.UIColor(named: "CoolColor", in: Bundle(url: Bundle.main.url(forResource: "SeparateBundle", withExtension: "bundle")!)!, compatibleWith: nil)
```

To be honest I don't know what the best solution to this problem is. R.swift does have a knowledge of all the colors from Asset Catalogs included in the main bundle, so for a workaround if the color included in the IB resource doesn't match, it's excluded from `validate`. But that also defeats the entire purpose of the test, making it basically pointless. 

The other solution is much more technical. If the select target has a `[CP] Copy Pods Resources` build phase, it can grab the output `.xcfilelist` from that phase and grab up all the Asset Catalogs from there, identifying the correct bundle to associate with each color. The impact here is 2-fold, performance and the added fragility due to the coupling with Cocoapods.

Perhaps somebody who understands more about how colors within Asset Catalogs actually works can help come up with a more elegant solution.

[RSwiftColors.zip](https://github.com/mac-cain13/R.swift/files/3525842/RSwiftColors.zip)

**Comment by tomlokhorst** [comment]
Hmm.... interesting...

I think using a color from a separate bundle isn't a supported feature in UIKit, and Interface Builder showing the color in the picker is a bug.

If you change the color in the asset catalog of the separate bundle, and relaunch the app, it will still show the old color. That old color was saved in the Storyboard when it was last opened in Interface Builder.

If you change the color in the asset catalog of the main bundle, and relaunch the app, it will show the new color.

**Comment by bclymer** [comment]
@tomlokhorst good observation, the color value is definitely cached in the storyboard until the storyboard is relaunched and updated. 

I was able to get an extra layer of verification by printing the `textColor` of the `UILabel`, and also printing the color fetched via `UIColor(name:bundle:)`.

Before changing the color in the pod bundle:
```
Optional(UIExtendedSRGBColorSpace 0 1 0 1)
Optional(kCGColorSpaceModelRGB 0 0 1 1 )
```

After changing the color in the pod bundle:
```
Optional(UIExtendedSRGBColorSpace 0 1 0 1)
Optional(kCGColorSpaceModelRGB 0 0 1 1 )
```

So the named color did change, but the storyboard didn't just like you suggested. It's understandable that the feature doesn't work, since image resources don't work like that either and collisions would cause problems. I was just excited for the possibility that Apple somehow supported it.

I'll close out this issue.
