### ISSUE TITLE
R.generated.swift is generated with an empty "import" which cause compilation error

### ISSUE THREAD

**Issue by marcosiino** [mac-cain13/R.swift#548]
I've used R.swift in two similar apps and there the R.generated.swift file is generated correctly. Then I'm trying to use it in a third app, which is similar to the other two (which is derived from this one) but in this third app the R.generated.swift file contains an "empty" import which causes a compilation error:

The file starts like this:

`//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import 
import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {

//etc....
`
What I did is just following the installation instructions in the README file, like i did with the other two apps: i've added the R.swift pod in the Podfile, I've run pod install, and then i've added the Run Script in both the two targets of the app.

I'm using Xcode 10.2.1 and the code of the app is written in swift 5. Cocoapods installed R.swift ver. 5.0.3 and R.swift.Library 5.0.1.

Anyone can give me some clue on what could be the cause ?

Thanks!

**Comment by tomlokhorst** [comment]
My first guess would be that there's a nib or storyboard somewhere that references an empty (or whitespace) module.

Although R.swift should never generate this code. So that part is a bug.

**Comment by marcosiino** [comment]
So i need to check each field 'module' of each view within each viewcontroller to be sure there are not empty/whitespace fields ? OMG, they are a lot!

**Comment by tomlokhorst** [comment]
You can use this command to search all files for a whitespace-only modules:

`grep -r customModule=\"\\s*\" *`

I do see that this can cause an issue, so I'll create a fix for this in R.swift.

**Comment by marcosiino** [comment]
You saved me!!! I found it, there was a xib which had an empty module for a custom class instead of "Inherit from current target".

Thank you so much!!

Are you going to push a new version into the cocoapod trunk repo when you will make the fix, right ?

**Comment by tomlokhorst** [comment]
Yes. I plan on fixing this in R.swift 5.1, but it will be a few weeks before that version is released.

**Comment by marcosiino** [comment]
THank you, i think i've encountered another possible bug: The generated R.generated.swift now doesn't contains a localized string which is instead contained in the Localizable.strings files i've in the app. The key name string is the following and it is contained in ALL the Localizable.strings files:

"challengeAgainstMyself" = "Challenge against Myself";

Is it possible that it's because the word "self" contained in the key ? Maybe you do a check and in this case the check prevent the string to be added in the generated file ?

**Comment by tomlokhorst** [comment]
The "self" shouldn't be an issue. Does R.swift generate warnings about this key?

**Comment by marcosiino** [comment]
Yes, i didn't realized there was some warnings from R.swift, i've found the problem, it was about different string format placeholders in the different localizations. Thanks!
