### ISSUE TITLE
Generating options

### ISSUE THREAD

**Issue by pskow** [mac-cain13/R.swift#552]
Would it be possible to generate file only with localization? 
Is it possible to change top level struct name from `R` to something else?
Ideally It would be cool to use it for example like `R.exampleText` instead of `R.string.localizable.exampleText`

**Comment by mac-cain13** [comment]
Thanks for using R.swift!

Currently this is not possible, but these could be features that we implement in R.swift. I'm curious about your use case, could you explain a bit why renaming the struct and only generating localizations would help you? 

Knowing the use case for a certain feature/change really helps to decide if it's worth the time and maintenance.

**Comment by pskow** [comment]
@mac-cain13 Only thing I currently need is to have strongly typed localization. 
So basically chaining with `R.string.localizable.exampleText` is a little long and would be cool to just call `R.exampleText`.
If it comes to renaming, `R` can be a little confusing and doesn't follow naming convention.

Those are just questions/suggestions for your library which is super awesome anyway :)

**Comment by pskow** [comment]
Szwagier zamknal temat, dziekuja

**Comment by remy-bardou-lifeonair** [comment]
+1

In my case we're running an app extension that needs access to localizable string but including the generated file doesn't work because it includes a lot of unaccessible classes (i.e: view controllers that are in the storyboards, which is not something needed in the app extension)

**Comment by tomlokhorst** [comment]
With version 5.1 you can choose to only run the string generator by adding a flag: `--generators string`

So the whole call becomes something like:
```bash
"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift" --generators string
```
