### ISSUE TITLE
R.color in watchOS (5.1.0.alpha.4)

### ISSUE THREAD

**Issue by xmanu** [mac-cain13/R.swift#559]
Hello,

let me start with saying a sincere thank you for bringing watchOS support to R.swift. R.swift is one of my absolute go to libraries I always use and I was sad to resort to untyped code for watchOS until now.

I don't know if it is approriate to report "bug" for alpha versions, but I found an issue with watchOS support in 5.1.0.alpha.4.

When trying to use the usual syntax to get a UIColor `R.color.background()` this won't work on an watchOS target. The static let is correctly generated and the ColorResource is accessible, but the necessary static func to get the `UIColor` is still marked with `#if os(iOS) || os(tvOS)`.

Attached find a snippet of the generated code.

```
    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.background, compatibleWith: traitCollection)
    }
    #endif
```

Thanks in advance for the great work. This saves me so much work on specific watchOS code I had to write before, especially because I can now use `R.string.`!

**Comment by tomlokhorst** [comment]
R.color will be available as part of version 5.4.0
