### ISSUE TITLE
R.swift not compatible with Xcode 11

### ISSUE THREAD

**Issue by tomasharkema** [mac-cain13/R.swift#561]
In some cases, when you have a dependency on a static library, target is not present in the de project file, which crashes the R.swift process.

**Comment by mac-cain13** [comment]
Would it be possible for you to set up a small demo project giving the error, would help @tomlokhorst and me to fix the issue.

**Comment by jamalalayq** [comment]
I have this issue, but i my case mac OS Catalina see R Swift  as a harmful thing, i am using fastlane for building and archiving and getting an IPA.

**Comment by tomlokhorst** [comment]
@tomasharkema  This should be fixed in the develop branch, we'll release R.swift 5.1 soon.

@jamalalayq This doesn't sound like its related to this particular issue with static libraries in an Xcode project. Can you create a new issue that describes how to reproduce your problem?

**Comment by Arya-Wang** [comment]
I have the same issue, But I found that this problem has been fixed in version 5.2.2
