### ISSUE TITLE
Xcode 11.1 - Rswift from SPM not linkable 

### ISSUE THREAD

**Issue by mszyszylo** [mac-cain13/R.swift#565]
Hey guys,
am I wrong or isn't it possible to use Rswift with the Swift Package Manager even that you can add that as a package?

**Comment by tomlokhorst** [comment]
I haven't tried to, but I'm assuming it's not possible to use R.swift using SPM.

R.swift is an executable, not a library, so you need the executable on your system to run it before you build your code.

Perhaps you can use Mint to install R.swift?
https://github.com/mac-cain13/R.swift#mint

Note that you can use [R.swift.Library](https://github.com/mac-cain13/R.swift.Library) from SPM, that library is also needed when using R.swift
