### ISSUE TITLE
R.image for sf symbols?

### ISSUE THREAD

**Issue by kuls14** [mac-cain13/R.swift#568]
I would love to use R.image for the system provided icon (sf symbols) in iOS 13.
Is there any way I can do this?

**Comment by 131e55** [comment]
I want it too😻

**Comment by flowtoolz** [comment]
There is this: https://github.com/piknotech/SFSafeSymbols

But it would be nice to have system symbols safely typed via R.swift.

**Comment by mac-cain13** [comment]
I think this is out of scope for R.swift since this a fixed set that Apple provides, just like the system fonts. Good idea, but I think a separate tool/library for this is just fine!
