### ISSUE TITLE
Could not be parsed in Xcode11 with tools

### ISSUE THREAD

**Issue by syatyo** [mac-cain13/R.swift#570]
# Error
[R.swift] Project file at 'myxcodeproj' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?

# Reproduce
1. `xcodegen`(spm & carthage)
2. `bundle exec pod install` (cocoapdos)
3.  cmd + b

# Enviroment
Xcode11.1
Xcodegen 2.9.0
Cocoapods 1.8.4
Carthage
Swift Package Manager 5
R.swift 5.1.0.alpha.4

**Comment by syatyo** [comment]
I noticed that this issue related with #536

**Comment by tomlokhorst** [comment]
R.swift 5.1 was just released and should fix this issue.

**Comment by syatyo** [comment]
Thanks @tomlokhorst a lot!
I could confirmed working with Xcode 11.1 and SPM👍
