### ISSUE TITLE
Change calls from `Locale.init` to explicit `Locale(identifier: String)` to avoid calling accidental overloads

### ISSUE THREAD

**Issue by damienb** [mac-cain13/R.swift#572]
Hello, 

I have a problem with this line in R.generated when i launch my app since Xcode 11 : 

fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current

I have this error : 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: Invalid top-level type in JSON write'
*** First throw call stack:

In my app i have only one language "fr".

Somebody can help me ?

Thanks

**Comment by tomlokhorst** [comment]
This specific line hasn't changed in R.swift since Xcode 11. Also, R.swift doesn't doe anything with JSON serialisation.

Are you sure this error is caused by R.swift?

**Comment by damienb** [comment]
Yes, when i changed this specific line in 

fileprivate static let applicationLocale = Locale.current

it's work

**Comment by damienb** [comment]
I have more informations : 
It's crash when i use strings with params

> static func homePageTtl(_ value1: String, preferredLanguages: [String]? = nil) -> String {
>         guard let preferredLanguages = preferredLanguages else {
>           let format = NSLocalizedString("homePageTtl", bundle: hostingBundle, comment: "")
>           return String(format: format, locale: applicationLocale, value1)
>         }
> 
>         guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
>           return "homePageTtl"
>         }
> 
>         let format = NSLocalizedString("homePageTtl", bundle: bundle, comment: "")
>         return String(format: format, locale: locale, value1)
>       }

The crash occurs at this line:

> return String(format: format, locale: applicationLocale, value1)

**Comment by damienb** [comment]
The problem is that the code does not take the good initializer of Locale in Locale.init

It seems to take Locale.init(from: Any) who expects to have a dictionary while you pass him a String. We must slightly modify the line to specify the initializer that we want:

`Locale.init(identifier: $0)`

Which give :

`fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap({Locale.init(identifier: $0)}) ?? Locale.current`

Can you check on your side and make a fix accordingly?

**Comment by tomlokhorst** [comment]
Does it actually work if you change the generated code to that?

What error are you getting? A compile time error, or a runtime crash?

Because I don't see how `Locale.init(from: Decoder)` could compile, if we give it a String.

**Comment by damienb** [comment]
Yes it's work.
It's a runtime crash.
It's not Locale.init(from: Decoder) but Locale.init(from: Any). I think it's the new default initializer in Swift 5.1 : https://github.com/apple/swift-evolution/blob/master/proposals/0242-default-values-memberwise.md

<img width="284" alt="Capture d’écran 2019-10-23 à 13 56 12" src="https://user-images.githubusercontent.com/23341379/67390374-d8a66e80-f59c-11e9-9227-05ac0cf1fa92.png">

**Comment by tomlokhorst** [comment]
I don't think its related to the memberwise initializer. That doesn't take an Any, or generates an optional initializer.

Is your Any initializer perhaps an extension from some library in your code? I'm not seeing it in documentation (or in my own autocomplete).

**Comment by damienb** [comment]
Oh yes you're right.
it comes from the SweeterSwift library which has an extension of Decodable with init?(from: Any)

Is it possible for you to add an explicit initializer to avoid this problem?

**Comment by tomlokhorst** [comment]
Yes we can change that.
As well as look through other code where we don't have explicit method signatures. To prevent other such issues for people who have libraries that include Any overloads.

**Comment by damienb** [comment]
Thank you very much !
Do you have any idea of ​​deadlines to have a new version available with this hotfix?

**Comment by damienb** [comment]
Thank you very much for your responsiveness. We look forward to the release because it is blocking each of my builds that I disable the automatic generation.
