### ISSUE TITLE
R.generated does not generate at every build since Xcode 11

### ISSUE THREAD

**Issue by damienb** [mac-cain13/R.swift#573]
Hello,

Since Xcode 11, my file R.generated it is not generated at every build. I need to delete all content in R.generated and clean my project and build to regenerate the file.

I have check the configuration and everything it's ok and it's work very well before Xcode 11.

Somebody can help me ?

Thanks

**Comment by tomlokhorst** [comment]
That's unfortunate, I haven't seen this issue in other projects using R.swift and Xcode 11.

Are you using the latest R.swift release (5.1)?
Which build system are you using? (Legacy or New)
Did you follow the instructions for the appropriate build system: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-50

**Comment by damienb** [comment]
Great ! Since Xcode 11, i use legacy build and i have not seen this line :

> If you are using the "Legacy Build System":
> 
> Add the flag --disable-input-output-files-validation and do not add input/output files to the Build Phase, See an example screenshot.

Thank you very much it's work now
