### ISSUE TITLE
Why does SPM require OSX 10.11 and not iOS?

### ISSUE THREAD

**Issue by kylebrowning** [mac-cain13/R.swift#577]
Title says it all, Package.swift is locked to Mac platform only.

**Comment by tomlokhorst** [comment]
R.swift is a command line tool that runs on macOS. It can't be run on iOS.

The runtime library that's used by R.swift does support SPM on iOS: https://github.com/mac-cain13/R.swift.Library#swift-package-manager-requires-xcode-11
