### ISSUE TITLE
Disable generation for certain groups of resources

### ISSUE THREAD

**Issue by malcommac** [mac-cain13/R.swift#578]
Is possible to avoid generation of certain group of files? I'm interested only in images and fonts but I don't know how to disable other file types.
Thanks

**Comment by tomlokhorst** [comment]
You can choose to only run certain generators by adding a flag: `--generators image,font`

So the whole call becomes something like:
```bash
"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift" --generators image,font
```

**Comment by malcommac** [comment]
thank you it works perfectly.

Did you also know how can I use R.swift with a pod library? 

Let me explain; our app is composed by several frameworks linked as local pods. 
One of them is the *UI framework and contains several xcassets and fonts.
I should run the script on that pod / podspec and produced R.generated must be linked into the pods source.
Is this a scenario supported by R.swift?

thanks.
