### ISSUE TITLE
R.color returns nil for iOS 11 when compiled from Xcode 11.

### ISSUE THREAD

**Issue by ankita-chhikara** [mac-cain13/R.swift#580]
I am using r.swift in my project. And when accessing color using R.swift, it returns nil. This fails only for the combination Xcode 11 + iOS 11. iOS 12 and above, the code works.

**Comment by mac-cain13** [comment]
What is the code R.swift generates for the color you can't load? Could you try to use that code directly in your app, does that work in Xcode 11 on iOS 11?

**Comment by tomlokhorst** [comment]
This is a bug in Xcode 11 GM 1.
Make sure to update to at least Xcode 11 GM Seed 2 (11A420a), where the issue was resolved

**Comment by ankita-chhikara** [comment]
Worked with latest xcode.
