### ISSUE TITLE
How do I implement plurals?

### ISSUE THREAD

**Issue by Ricardo1980** [mac-cain13/R.swift#582]
Hello,

In the documentation, I don't see anything about plurals.

Usually that is implemented using a .sttringdict file.
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html

How do I integrate that with R.switf? 
Thanks a lot for your ideas.

**Comment by tomlokhorst** [comment]
.stringdict files are fully supported. See https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#localized-strings

**Comment by Ricardo1980** [comment]
Oh, didn't see that.
I try that right now. Thanks a lot!
