### ISSUE TITLE
Info plist is not resolved using environment variables, this is causing errors

### ISSUE THREAD

**Issue by kumanmushi** [mac-cain13/R.swift#583]
I installed with CocoaPods.

Then i got warning `[R.swift] File could not be parsed as Info Plist from URL: /path/to/project/module_name/ $(SRCROOT)/project_name/my_path/Info.plist` on xcode 11.2.1.

However i can use R.swift methods.

# Using version
- Xcode 11.2.1
- CocoaPods:   1.8.4
- R.swift (5.1.0)
- R.swift.Library (5.1.0)

![BuildPhase](https://user-images.githubusercontent.com/21922488/68997316-55044700-08e8-11ea-9500-db09a600290d.png)

**Comment by den-zv** [comment]
I have the same issue.
Also I've specified "Info.plist File" field (under "Build Settings" -> "Packaging") relatively just as a variable `$(PATH_TO_INFO_PLIST)` that goes from `.xcconfig`.

Maybe it's possible to make an ability to turn `Info.plist` scanning phase off as a workaround.

**Comment by mac-cain13** [comment]
We're currently not using the environment variables Xcode exposes to load the info plist file, we should use these instead of looking in the Xcode config ourselves so that all variables are correctly resolved.

Example of environment vars relating to info plist:
```    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_FILE=ResourceApp/Info.plist
    export INFOPLIST_OUTPUT_FORMAT=binary
    export INFOPLIST_PATH=ResourceApp2.app/Info.plist
    export INFOPLIST_PREPROCESS=NO
    export INFOSTRINGS_PATH=ResourceApp2.app/English.lproj/InfoPlist.strings```

**Comment by tomlokhorst** [comment]
As a workaround, while this issue persists:

It’s possible to manually configure which generators are run: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Ignoring.md#only-run-specific-generators-exclude-rsomething

By not running the `info` generator, no warning should be shown.

**Comment by jaenthemaen** [comment]
Unfortunately the workaround does not work for me. With a clean build and only the image, string, font and color generators specified the issue still persists.

**Comment by ykotov2** [comment]
Indeed, with only `--generators color` specified it still outputs the following line twice on execution:
> warning: [R.swift] File could not be parsed as InfoPlist from URL: file:///.../Info.plist

**Comment by metasmile** [comment]
Was it resolved? thanks

**Comment by StevenMagdy** [comment]
Facing the same issue in Xcode 11.3

**Comment by break2k** [comment]
> Facing the same issue in Xcode 11.3

Second that.

**Comment by 949886** [comment]
> > Facing the same issue in Xcode 11.3
> 
> Second that.

Third that.

**Comment by spydercapriani** [comment]
> > > Facing the same issue in Xcode 11.3
> > 
> > 
> > Second that.
> 
> Third that.

Fourth that

**Comment by tercteberc** [comment]
> > > > Facing the same issue in Xcode 11.3
> > > 
> > > 
> > > Second that.
> > 
> > 
> > Third that.
> 
> Fourth that

 Fifth that

**Comment by roelspruit** [comment]
I submitted a PR to at least remove this warning if you are not running the plist generators. The PR was merged into this project but there hasn't been a release yet. I'll ask the maintainers if they can do that.

**Comment by firetrap** [comment]
> > > > > Facing the same issue in Xcode 11.3
> > > > 
> > > > 
> > > > Second that.
> > > 
> > > 
> > > Third that.
> > 
> > 
> > Fourth that
> 
> Fifth that

sixth that

**Comment by tomlokhorst** [comment]
This has been fixed in R.swift 5.2.0 release.

**Comment by mac-cain13** [comment]
Finally 😄

**Comment by doston0000** [comment]
still has the issue on 5.2.0 release, i was able to workaround by adding --generator types in buildphases
```
cd YourSPM
SDKROOT=macosx
swift run -c release rswift generate --generators image,string,color,file,font,nib,segue,storyboard,reuseIdentifier,entitlements,id "$SRCROOT/R.generated.swift
```
input files: `$TEMP_DIR/rswift-lastrun`
output files: `$SRCROOT/R.generated.swift`

 p.s: iam using manual installation method

**Comment by ThomasCle** [comment]
I still have this issue with 5.4.0 using SPM. @doston0000's solution with the generator parameter works as a workaround for now.

**Comment by jalone87** [comment]
Using Xcode 13.3 and R.swift installed in a BuildTools SPM package, same problem here. it is looking for 

- `Info.plist`
- `main-project.entitlements` 

inside the subfolder of the BuildTools project.
And throws a warning 

    [R.swift] File could not be parsed as InfoPlist from URL: file:///Users/xxx/project_name/BuildTools/target_name/Info.plist
    [R.swift] File could not be parsed as InfoPlist from URL: file:///Users/xxx/project_name/BuildTools/target_name/project_name.entitlements
