### ISSUE TITLE
Duplicate Variable Names with entitlements, unable to ignore

### ISSUE THREAD

**Issue by kunalverma25** [mac-cain13/R.swift#584]
R.Swift creating duplicate names for entitlements -
```
applinks:ABC.com
applinks:*.ABC.com
```

```
static let applinksABCCom = infoPlistString(path: ["com.apple.developer.associated-domains"], key: "applinks:*.ABC.com") ?? "applinks:*.ABC.com"
static let applinksABCCom = infoPlistString(path: ["com.apple.developer.associated-domains"], key: "applinks:ABC.com") ?? "applinks:ABC.com"
```

Tried adding .entitlements file to .rswiftignore. but that also doesn't work.

.rswiftignore file -

**/*. entitlements

**Comment by tomlokhorst** [comment]
This appears to be a bug in the duplicate name detection. Thanks for reporting it!

You can work around this issue by manually configuring the generators R.swift uses (and excluding the one for the entitlements file).

Add the following option to `rswift`: `--generators string,image,font`

These are all possible options:
```
  case image
  case string
  case color
  case file
  case font
  case nib
  case segue
  case storyboard
  case reuseIdentifier
  case entitlements
  case info
  case id
```

Select the ones you need (maybe everyone minus entitlements).

**Comment by sreeram780** [comment]
Hi 
Where should i add this line Add the following option to rswift: --generators string,image,font

**Comment by mac-cain13** [comment]
In the Build Phase for R.swift add `--generators string,image,font` at the end: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Images/BuildPhaseExample.png

**Comment by sreeram780** [comment]
Thank you for your response

Thanks&Regards,
T.Sreenivasula Reddy,
MOB: +91 9703889458,
SKYPE: sreenivasulareddy780.

**Comment by sreenivas-wal** [comment]
> In the Build Phase for R.swift add `--generators string,image,font` at the end: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Images/BuildPhaseExample.png

please give me one screenshot  after adding this  --generators string,image,font`.  I'm unable to do that
