### ISSUE TITLE
How can I use raw png/jpg from images folder unlike xcasset?

### ISSUE THREAD

**Issue by hissain** [mac-cain13/R.swift#592]
How can I use raw png/jpg from resource folder unlike xcasset?

Is there any way to make R.Swift generate for all images in my images folder?

**Comment by tomlokhorst** [comment]
R.swift will generate static resources for all images, both in xcassets and image files that are part of your target.

See the documentation: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#images
