### ISSUE TITLE
RSwift Not working on custom strings added in Localizable Strings file

### ISSUE THREAD

**Issue by Abhishek9634** [mac-cain13/R.swift#594]
I have a login and Keyboard Toolbar with done button.

The strings that are associated directly with storyboard works fine on change language. But not the programmatically.

I have added in Localizable String file (Dutch)

/* Keyboard Done Title */
"DONE.text" = "Klaar";

/* CANCEL */
"CANCEL.text" = "Annuleer";

/* OK */
"OK.text" = "Oke";

/* Class = "UIButton"; normalTitle = "Inloggen"; ObjectID = "zcB-rQ-yoP"; */
"zcB-rQ-yoP.normalTitle" = "Inloggen";

/* INVALID EMAIL ALERT MESSAGE */
"EAM.text" = "Ongeldig e-mailadres";

But on launch i got below.

## DONE BUTTON
![IMG_3157](https://user-images.githubusercontent.com/10388287/72336053-01df2280-36e6-11ea-8e73-0355a5cff4dd.jpeg)

##Alert
![IMG_3158](https://user-images.githubusercontent.com/10388287/72336055-0277b900-36e6-11ea-90fa-6146da5425e3.jpeg)

// PROJECT SETTINGS
<img width="1066" alt="Screenshot 2020-01-14 at 4 07 21 PM" src="https://user-images.githubusercontent.com/10388287/72337119-00165e80-36e8-11ea-9940-26a376f2ef86.png">

## Code

R.string.login.okText()
R.string.login.eamText()
R.string.login.doneText()
R.string.login.zcBRQYoPNormalTitle()

Let me know what's wrong in above ??

@mac-cain13 @tomlokhorst  : Need you help :|

**Comment by tomlokhorst** [comment]
Does this work if you don't use R.swift, but instead use `NSLocalizedString` natively?

**Comment by Abhishek9634** [comment]
@tomlokhorst : I tried like this

>  let ss = NSLocalizedString("DONE.text", comment: "XXXXX")
>         print(ss)

Output: **DONE.text**

Anything i am missing ??

**Comment by tomlokhorst** [comment]
If your strings are in a different file, you need to specify that file name in the call to NSLocalizedString.

For example, if your strings are in `login.strings`, use: `NSLocalizedString("MyString", tableName: "login", comment: "XXX")`

However in general; if it also doesn't work without R.swift, it's not an issue with R.swift itself, but something unrelated.

**Comment by evgenijkrivelev17** [comment]
I have almost the same problems. But for works when I use NSLocalizedString, but when I build  project, after I don't see new strings, colors and images. It's like generated old version of rswift..What I'm missing?
