### ISSUE TITLE
Argument type '() -> R' does not conform to expected type 'ResultProtocol'

### ISSUE THREAD

**Issue by rafsouzap** [mac-cain13/R.swift#597]
After upgrading to version 5.1.0, this error started to appear at the time of compilation:

<img width="1070" alt="Screen Shot 2020-01-22 at 13 43 23" src="https://user-images.githubusercontent.com/2496520/72914271-345bd180-3d1d-11ea-90b3-e894fff494f2.png">

Does anyone have any idea what may be happening?

**Comment by essamMohamedFahmi** [comment]
Have u solved it?

**Comment by ryuheimat** [comment]
I have same issue, Have you solve it?

**Comment by norkholis** [comment]
i have same issue, anyone can help?

**Comment by aryasurya21** [comment]
i solved this by updating my Result version to 5.0.0

**Comment by mazharhameed25** [comment]
i have the same issue? did anyone reslove it?
