### ISSUE TITLE
Module 'Rswift' was not compiled with library evolution support; using it means binary compatibility for 'X' can't be guaranteed

### ISSUE THREAD

**Issue by tumata** [mac-cain13/R.swift#598]
Is this something to be worried about when using RSwift in a library ? Are there plans to fix this ?

https://www.donnywals.com/what-is-module-stability-in-swift-and-why-should-you-care/

**Comment by mac-cain13** [comment]
This is not something to be worried by, the library is source code you directly compile/include in your project. So it will never be incompatible with your project.
