### ISSUE TITLE
R.generated.swift compile error : Cannot convert value of type '[NSObject : AnyObject]?' to expected argument type '[UINib.OptionsKey : Any]?'

### ISSUE THREAD

**Issue by Derass239** [mac-cain13/R.swift#602]
Hi,

### Using 
    Xcode 11.3.1
    Swift : 4.2
    Carthage : github "mac-cain13/R.swift.Library" "v5.1.0"

I've got this error : 

> Cannot convert value of type '[NSObject : AnyObject]?' to expected argument type '[UINib.OptionsKey : Any]?'

In this code :

```
struct _R: Rswift.Validatable {
  static func validate() throws {
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _SplashScreenViewController.validate()
    }

    struct _SplashScreenViewController: Rswift.NibResourceType, Rswift.Validatable {
          let bundle = R.hostingBundle
          let name = "SplashScreenViewController"
      
          func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
            return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
          }
   
          fileprivate init() {}
        }
```

How can i fix this error ?

**Comment by tomlokhorst** [comment]
Make sure you are using the latest version of rswift executable from the latest R.swift release.
It seems your R.generated.swift file was generated by an earlier release (used for Swift 4).

See also: https://github.com/mac-cain13/R.swift/issues/474

If you have any further issues, do let us know!
