### ISSUE TITLE
Incorrect detection of format strings in URLs leads to compilation error

### ISSUE THREAD

**Issue by booiiing** [mac-cain13/R.swift#603]
If a string contains a URL with encoded characters (e.g. `%C3%B6` == ö), it is incorrectly represented as a format string. This leads to a follow-up error, where `valueN` may be of type `Character` or `Double`, both of which do not conform to `CVarArg`. Eventually, the Swift compiler will complain about this in the generated call to the `String(format:, locale:, value1, value2, ...)` initializer.

**Comment by svyatoslav-zubrin** [comment]
same here

**Comment by tomlokhorst** [comment]
Interesting, I hadn't considered encoded characters in strings files.

I would suggest using the original character itself in the strings file, so as not to confuse R.swift. Make sure to store the file in a proper text encoding, preferably UTF-8.

If you need the string to have precentage encoded characters, you can do that in Swift:
```swift
let someString = R.string.generic.someString()
let encodedString = someString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
```
