### ISSUE TITLE
Mint installation not possible - Could not resolve host: mac-cain13

### ISSUE THREAD

**Issue by PatrickDotStar** [mac-cain13/R.swift#604]
When trying to install R.swift over Mint it gives me following error
```
Klone nach 'mac-cain13_R.swift' ...
fatal: konnte nicht auf 'https://mac-cain13/R.swift/' zugreifen: Could not resolve host: mac-cain13
🌱  Encountered error during "git clone --depth 1 -b 5.1.0 https://mac-cain13/R.swift mac-cain13_R.swift"
🌱  Couldn't clone https://mac-cain13/R.swift 5.1.0
```
I have added `mac-cain13/R.swift` to the Mintfile and run `mint bootstrap` as described in the installation paragraph.
Looks like `https://mac-cain13/R.swift/` is not accessible.

**Comment by mac-cain13** [comment]
Are other Mint dependencies working? If so, what does you Mintfile look like? 

Seems like Mint is not understanding it should connect to Github, so probably something is wrong in the Mintfile.

**Comment by PatrickDotStar** [comment]
I have one other dependency in the Mintfile and for that installing works

**Comment by FromAtom** [comment]
@PatrickDotStar 

Are you write like this?

```Mintfile
mac-cain13/R.swift@5.1.0
```

If so, adding a "v" might fix it.

```Mintfile
mac-cain13/R.swift@v5.1.0
```

**Comment by PatrickDotStar** [comment]
@FromAtom Your solution worked but I also tried it again without providing any version and suddenly it works now. Will close the issue.
