### ISSUE TITLE
Localized string not working - Xcode 11, Swift 5

### ISSUE THREAD

**Issue by Dnathan33** [mac-cain13/R.swift#614]
I created a new project with Xcode 11 and Swift 5 and Localizable string is not working at all.

**Comment by tarjamorgado** [comment]
Hi, it's working on my end, using Swift 5.1.3 with Xcode 11.3.1, in a brand new project. Can you elaborate on your issue? What's not working exactly?

Cheers

**Comment by Dnathan33** [comment]
Hey, thanks for reaching out.

So I have a Localizable.strings in my Xcode project which has been added to targets and compiles just fine as well. However, R.swift is not picking it up. I had no problem with this prior to swift 5.
So basically I don't have the string option - R.strings

Can you please list the steps you took?

**Comment by tarjamorgado** [comment]
Hi,

When you say "added to target", is it as in the "Target Membership" checkbox is selected when you select the Localizable.strings file?

Also, did you make sure you have Run Script before "compile sources" and after the "Check Pods Manifest"?

If rswift is being called, where is your R.generated being written to? Are you sure it's in the folder you expect it to be? 

Did you drag it into your Xcode project? And if yes, double check that it's not writing an R.generated.swift file somewhere else in your project.

The steps I took are pretty much outlined in the README file (using cocoa pods).

If you still can't figure it out, consider creating a brand new project just to follow the steps in the README file for the R.swift installation, something will click I'm sure. 

Cheers

**Comment by tomlokhorst** [comment]
@Dnathan33 Thanks for using R.swift. Hopefully the steps above have fixed your issue. If not, let us know!

@tarjamorgado Thank you for your helpful comments!
