### ISSUE TITLE
Using Rswift with multiple bundles

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [mac-cain13/R.swift#615]
Hi,

Thanks for this great library. We are using multiple bundles in our project and I want to load an image from another bundle.

Can't access it by R.image.** because **Rswift** is not generate resources from different bundle.

How can I achieve this? There are same issues and I can work on it if you can direct, I can help about that feature.

Thanks.

**Comment by ibrahimyilmaz7** [comment]
I solved my problem by adding `generate --accessLevel public` to my scriptshell.

**Comment by mag2007** [comment]
But what about classes/xib's/storyboards, that may be private/internal? I am getting this error with the accessLevel public
`Property cannot be declared public because its type uses an internal type`

**Comment by ibrahimyilmaz7** [comment]
What's to point to use an internal/private class through bundles? It isn't possible unrelated to R.swift.

**Comment by mag2007** [comment]
Well, Rswift generates a lot of stuff. And when this happens with your setting, then there are many errors, that may be fixed by declaring that "real" classes public. So i would say, it is related to R.swift and the way it generates things.
