### ISSUE TITLE
Issue with R.generated.swift file after compiling

### ISSUE THREAD

**Issue by eitguide** [mac-cain13/R.swift#616]
After install with the lastest R.swift into project and setup Run Script  input files and ouputs file as well. I compile my project to get R.generated.swift file.

But when I add it to project and  make runt xcode got a following error.
<img width="1022" alt="Screen Shot 2020-03-24 at 16 01 02" src="https://user-images.githubusercontent.com/19884637/77407893-779ff280-6de9-11ea-89c1-0322125d74ee.png">

I used swift5 and xcode 11.3.1 to build project.

**Comment by tomlokhorst** [comment]
I suspect you have "ViewController" set as custom class Module in your storyboard. Make that field empty and the generated file should work again.

<img width="286" alt="image" src="https://raw.githubusercontent.com/mac-cain13/R.swift/master/Documentation/Images/ExplicitCustomModule.png">


See also: https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file
