### ISSUE TITLE
Can I change name of the struct `R`?

### ISSUE THREAD

**Issue by Demircivi** [mac-cain13/R.swift#618]
Is there any way to change the name of the autogenerated struct?

I have 3 subprojects in my workspace and I want to build seperate R files for each of them. See the photo below:
![image](https://user-images.githubusercontent.com/22484255/77535215-4982e700-6eab-11ea-89e4-7c7fc5959a88.png)

As far as I see the struct name is [hardly coded](https://github.com/mac-cain13/R.swift/blob/master/Sources/RswiftCore/Generators/AggregatedStructGenerator.swift#L20), any suggestions?

By the way my idea is building seperate R files for each project like:
* _R_(for Bingo)
* _UIR_(for BingoUI)
* _SharedR_(for BingoShared)

**Comment by tarjamorgado** [comment]
If you have 3 `R.generated.swift` files, each under its own module, you should then be able to access each as `Bingo.R.`, `BingoUI.R` and `BingoShared.R`.

If that's too verbose, you could create a typealias for each:
```
public typealias SharedR = BingoShared.R
public typealias UIR = BingoUI.R
```

**Comment by tomlokhorst** [comment]
As mentioned, you can import and use the R structs from each library separately.

See: https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#can-i-use-rswift-in-a-library
