### ISSUE TITLE
validate() fails on system images in nibs

### ISSUE THREAD

**Issue by brockboland** [mac-cain13/R.swift#619]
I admit that I haven't had time to really dig into this, but I discovered today that `R.validate()` is throwing an error for a nib that's using one of the new system-provided images:
```
if UIKit.UIImage(named: "chevron.right", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'chevron.right' is used in nib 'BorderedOptionView', but couldn't be loaded.") }
```

It looks like these validation methods might also need to also try to load the image using [init(systemName:)](https://developer.apple.com/documentation/uikit/uiimage/3294233-init).

**Comment by tomlokhorst** [comment]
This is a bug in our parser. 

A "normal" image is something like this in .storyboard:
`<imageView image="User@white.png">`

A system image is something like this:
`<imageView image="chevron.right" catalog="system" >`

We should parse this correctly, and then generate the call to the systemName initializer.

**Comment by tomlokhorst** [comment]
This might be a related issue: https://github.com/mac-cain13/R.swift/issues/471
