### ISSUE TITLE
Incorrect "filename or extension could not be parsed from URL" warning on strings file parsing error

### ISSUE THREAD

**Issue by SpacyRicochet** [mac-cain13/R.swift#620]
I encountered the following R.swift warning on R.swift 5.1.0 with Xcode 11.3.1;

> [R.swift] Filename and/or extension could not be parsed from URL: file:///path/to/project/Source/nl.lproj/Localizable.strings

However, the file existed and `cat /path/to/project/Source/nl.lproj/Localizable.strings` printed the contents just fine.

However, after fixing an actual syntax error in the strings file, the warning went away;

> ```"some_key": "Some text";```
> instead of:
> ```"some_key" = "SomeText";```

It looks like this specific failure to parse the strings file results in an incorrect warning message.

**Comment by tomlokhorst** [comment]
Thanks, I've fixed the message.
