### ISSUE TITLE
Failure to build when using Google Ads

### ISSUE THREAD

**Issue by BoscoDomingo** [mac-cain13/R.swift#624]
I'm working on an app where we make use of Google Ads, and when trying to integrate R.swift, build fails with error "Use of undeclared type 'GADUnifiedNativeAdView'", which comes from one of our other pods (Google-Mobile-Ads-SDK), and it is a view referenced in a .xib file and exists. Clicking the arrow in the 'Custom Class' section redirects me to it, and its functionality was flawless before using R.swift, so I doubt there's any issues there.

![image](https://user-images.githubusercontent.com/46006784/79120455-3c169980-7d93-11ea-9e9e-79e68149e32e.png)
![image](https://user-images.githubusercontent.com/46006784/79120506-581a3b00-7d93-11ea-8cc1-63880262e1ac.png)
![image](https://user-images.githubusercontent.com/46006784/79120844-2eaddf00-7d94-11ea-975f-fc0707487253.png)
![image](https://user-images.githubusercontent.com/46006784/79120851-32d9fc80-7d94-11ea-9f32-76e99c2c5cc2.png)

I'm not the most expert Swift developer out there, nor do I know the ins and outs of Xcode, so this issue may be a product of my own incompetence. Regardless, any help is appreciated!

**Comment by javigines** [comment]
Take a look into this: 
https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file

I think is your problem because your Module field in the xib is empty.

**Comment by tomlokhorst** [comment]
@BoscoDomingo I think @javigines answered your question. If not, let us know!

**Comment by BoscoDomingo** [comment]
> @BoscoDomingo I think @javigines answered your question. If not, let us know!

Yes he did, it is fixed!
