### ISSUE TITLE
warning: [R.swift] Skipping 7 strings in 'Localizable' (Base) because symbol '_hours' would be generated for all of these keys: 2_hours, 3_hours

### ISSUE THREAD

**Issue by c0diq** [mac-cain13/R.swift#629]
When strings keys start with a number like
```
"2_hours" = "2 hours";
"3_hours" = "3 hours";
"4_hours" = "4 hours";
"4_hours" = "4 hours";\
"5_hours" = "5 hours";\
"6_hours" = "6 hours";\
"7_hours" = "7 hours";
"8_hours" = "8 hours";
```
The following error is displayed
```
warning: [R.swift] Skipping 7 strings in 'Localizable' (Base) because symbol '_hours' would be generated 
```
R.swift is sanitizing the keys by removing the number since it is not allowed to have a Swift property starting with a digit. A solution would be to spell out the number instead of removing it so

`2_hours` would become `two_hours`

**Comment by tomlokhorst** [comment]
Hello @c0diq,

Thank you for contributing to R.swift, I appreciate your work in creating this PR and your enthusiasm for this issue.

I would like to point out that your previous [issue](https://github.com/mac-cain13/R.swift/issues/626) and [PR](https://github.com/mac-cain13/R.swift/pull/627) were closed earlier today.

You have duplicated them both and opened a new issue and PR with identical content. This is not needed.
You can continue a discussion in a closed issue. It is not needed to create a new one, if the old one is needed again, it can be reopened.

Again, thank you for contributing.
