### ISSUE TITLE
[Xcode 7] [Swift 2] 'Printable' has been renamed to 'CustomStringConvertible'

### ISSUE THREAD

**Issue by jobbogamer** [mac-cain13/R.swift#65]
Attempting to use R.swift in a project which has been converted to Swift 2 in Xcode 7 beta 5 results in a build error in `R.generated.swift` which says `'Printable' has been renamed to 'CustomStringConvertible'`.

The offending code is:

```
struct ReuseIdentifier<T>: Printable {
  let identifier: String
  
  var description: String { return identifier }
}
```

**Comment by jobbogamer** [comment]
Just noticed that Swift 2 is supported on the development branch. My bad!

**Comment by youngzhu** [comment]
Good to know.
