### ISSUE TITLE
Anti-virus software has removed "rswift" and caused  "rswift: No such file or directory"

### ISSUE THREAD

**Issue by undoroid** [mac-cain13/R.swift#650]
I don't think it's a problem with R.swift but I create this issue because I thought there might be others who are struggling with the same problem.

I suddenly stopped being able to build from 5/24/2020.
```
Pods/R.swift/rswift: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
The cause was that Avast's update recognized rswift as Bundlore adware and removed it.

**Comment by mac-cain13** [comment]
That's weird, could you report the binary you using to Avast as a false positive? You can do this using their webform: https://www.avast.com/false-positive-file-form.php

Please upload the exact version of R.swift you're using to them. I hope that will help prevent this in the future, not much we can do indeed. :)
