### ISSUE TITLE
Whats wrong

### ISSUE THREAD

**Issue by simpleLiYu** [mac-cain13/R.swift#651]
![image](https://user-images.githubusercontent.com/20043672/83123469-8798c300-a107-11ea-8058-937f2d761551.png)

**Comment by mbernson** [comment]
Hi,

Could you explain what it is you are trying to do? I can't make it up from just the screenshot.

**Comment by simpleLiYu** [comment]
Can i speak Chinese？

**Comment by mbernson** [comment]
Unfortunately I don't speak Chinese. You could try Google Translate or get a friend to help you translate.
