### ISSUE TITLE
R.generated.swift - Foundation.Locale

### ISSUE THREAD

**Issue by TaoNhan** [mac-cain13/R.swift#652]
Due to a conflict with a 3rd party framework I have no control over, `Locale` does not point to Foundation.Locale, but rather to the declared class in that fw.

So I have this compiling issue :

![Screen Shot 2020-05-28 at 8 58 26 AM](https://user-images.githubusercontent.com/10198092/83144895-fe12d200-a0c1-11ea-8fa0-3a9f24ea9363.png)

which i can fix like this 

![Screen Shot 2020-05-28 at 9 00 40 AM](https://user-images.githubusercontent.com/10198092/83144938-0834d080-a0c2-11ea-89a8-44c7e4f70042.png)

but because this is autogenerated code, my change gets erased.
Is it possible to adjust so that this autogenerated code explicitely declares Foundation.Locale insteaad of Locale ?

**Comment by mac-cain13** [comment]
If this is in a 3rd party framework and the framework is not imported in the generated file it should not give a conflict. If you declare a `Locale` class in the module the generated file is in it will give this error, I would strongly advice not to shadow Foundation classes in your own code.

Are you sure this is from a class in a 3rd party module and not declared in your own codebase?

We could create a flag that makes it possible to make `Foundation` explicit, but this is the first time I hear this is a problem in quite some years. So I'm not very eager to add such a feature.

**Comment by TaoNhan** [comment]
Hi,
Thank you for keeping me honest, you are right this 3rd party framework is actually provided to me as a set of files that I directly have to include in the project, and thus generating class conflicts.
I have been fighting to have them namespacing their classes to avoid class collisions, especially when they are choosing such common names, but always got some pushback from them due to other considerations I wont go into here.
I understand your position though and would like to thank you for your help whether you end up adding that flag or not.
If there is anything I can do to help getting this implemented let me know, with a few pointers maybe i could even do it for you.

**Comment by mac-cain13** [comment]
Let's not add a flag for these kind of things, since it's such and edge case. (Also that other developers should namespace generic named classes better I think.)

I would suggest using a build stap that find/replaces instances of `Locale` as a workaround for your case.

**Comment by Nielssg** [comment]
I was also experiencing this issue, I am using Apollo GraphQL which includes generating classes for queries. The GraphQL backend has an entity called `Locale`, which basically brought me to this issue to find out what the problem is. I have manually renamed every class in the generated code, but I was wondering if there has been any change for this particular issue in recent years? I could use find/replace in a build step to replace it, though I suspect others might have the exact same issue as it will possibly be more prevalent for people to have a generated `Locale` class when using GraphQL.
