### ISSUE TITLE
Cannot invoke 'register' with an argument list of type '(_R.nib._HomeCell)'

### ISSUE THREAD

**Issue by hrscy** [mac-cain13/R.swift#654]
![image](https://user-images.githubusercontent.com/16634163/83651171-c937db00-a5eb-11ea-9ad6-030e1c196c73.png)

**Comment by tomlokhorst** [comment]
Make sure you have the identifier set in the Attribute inspector of your cell.

Example:
<img width="275" alt="Reuse Identifier" src="https://user-images.githubusercontent.com/75655/83653026-9544c180-a5bb-11ea-8c1e-251f73f7187d.png">

If you're unsure why something with R.swift isn't working, you can first try to get it to work without R.swift, before switching to the R.swift API.

**Comment by hrscy** [comment]
@tomlokhorst Thank you!
