### ISSUE TITLE
Retrieve a localized string without parameters substitution

### ISSUE THREAD

**Issue by jalone87** [mac-cain13/R.swift#656]
Hello, I would like to know if there is any way to get the value of a localized string with parameters **without** the parameters substitution (eg: returning "Today i ate %@ icescreems").

<hr/>

_**Reasons:** One of the few reasons is I am developing a functionality involving attributed strings, and i would like to feed them directly a Rswift StringResource from the generated localizable strings or an analogue solution.
My goal is to add attributes to the parameters, for this i need the ranges of the placeholers for these_

**Comment by mac-cain13** [comment]
Currently R.swift doesn't have an API that does this. How would you fetch the localized strings without parameters substitution just using Apples Foundation APIs? If there is an API from Apple for it we could make R.swift support that. I'm not aware of such an API, but also never looked into it.

Note that I would probably just chop up the localized string in part 1, 2, 3 etc and apply attributes like bold and italic to the parts as a workaround.

**Comment by jalone87** [comment]
Yes, i guessed it wasn't provided at all, since the way to do it directly is very much not clean, but i tried to ask anyway in case i wasn't aware of something.
 
As for the hint, that is sadly not optimal for localization, since not all languages split sentences in the same way, but i will workaround this in other ways, no problem, would have just been cleaner if there was an API. 
Thank you anyway.

**Comment by tomlokhorst** [comment]
You can use the plain old NSLocalizedString to get the localized string without substitutions:

```swift
NSLocalizedString(R.string.localizable.welcomeWithName.key,
  tableName: R.string.localizable.welcomeWithName.tableName,
  bundle: R.string.localizable.welcomeWithName.bundle,
  value: "default value",
  comment: "no comment")
```

**Comment by jalone87** [comment]
> You can use the plain old NSLocalizedString to get the localized string without substitutions:
> 
> ```swift
> NSLocalizedString(R.string.localizable.welcomeWithName.key,
>        tableName: R.string.localizable.welcomeWithName.tableName,
>           bundle: R.string.localizable.welcomeWithName.bundle,
>            value: "default value",
>          comment: "no comment")
> ```

Ah, this is actually a very valid solution! I didn't think about it, thank you!
