### ISSUE TITLE
Xcode 12 deployment target warning

### ISSUE THREAD

**Issue by samrayner** [mac-cain13/R.swift#657]
Nothing serious but Xcode 12 gives the following buildtime warning:

>The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Probably safe to bump it to 9.0 just to silence the warning?

**Comment by alexruperez** [comment]
+1

**Comment by tomlokhorst** [comment]
This should be fixed by https://github.com/mac-cain13/R.swift/pull/674

**Comment by alexruperez** [comment]
Even with SPM integration?

**Comment by tomlokhorst** [comment]
Right, the SPM version should be fixed by the 5.3.0 release of R.swift.Library.
(We're working that release right now)

**Comment by alexruperez** [comment]
Awesome, thanks @tomlokhorst 🙌
