### ISSUE TITLE
Xcode 12 AppClip errors

### ISSUE THREAD

**Issue by ismailbozk** [mac-cain13/R.swift#658]
Hi 

I am working on AppClip integration for my project on Xcode 12 Beta.

However I am not able to get it working for my project.
I followed the advices from this issue https://github.com/mac-cain13/R.swift/issues/560#issuecomment-535132095
In my appclip target generated R.appclip.generated.swift file has my main target as a dependency
```
import MainTarget
```

This line gives ` No such module` error.

As a second approach when I try to share the same R.generated.swift file from both targets, I get `Multiple commands produce R.generated.swift` (I added the same run script phase to both targets.)
Could you please advise?

R.swift pod version 5.2.2

Thank you

**Comment by tomlokhorst** [comment]
See the other issue. 

For each target generate a separate R.generated.swift file, at different locations.
