### ISSUE TITLE
project.pbxproj double quotes diff whenever pod install

### ISSUE THREAD

**Issue by jinuman** [mac-cain13/R.swift#659]
I installed with CocoaPods which is recommended.  
And face with some issue that whenever I execute `pod install`, diff occurs in `project.pbxproj` ouputPaths.
And if I remain double quotes in outputPaths, then whenever `project.pbxproj` changed, outputPaths diff occurs as you can see above.

* Does anyone troubleshoot this issue?

**Comment by tomlokhorst** [comment]
I think this is an issue with CocoaPods. `pod install` will incorrectly add quotes around that string.

But Xcode itself won't add quotes. So when you initially added the output path, no quotes were added, and when you edit the project in some way, the quotes will be removed again.

In short, I don't think this is related to R.swift.

**Comment by jinuman** [comment]
@tomlokhorst But as I said above if I remove quotes, then whenever I execute `pod install`, diff occurs in project.pbxproj outputPaths. I don't think this is a R.swift issue as well. Because my other projects is working just fine with same build phase.  

Can you give me any hints for your reference?

**Comment by jinuman** [comment]
Sorry for closing this issue.
