### ISSUE TITLE
Is there a way for mute warnings about missing translations?

### ISSUE THREAD

**Issue by Igor-Poltavtsev** [mac-cain13/R.swift#660]
Is there a way for mute warnings like: 
```
warning: [R.swift] Strings file 'Localizable' (pt-BR) is missing translations for keys: 'some keys'?
```

**Comment by rhenz** [comment]
Same problem. Anyone?

**Comment by scaio** [comment]
@mantovanirian Adding missing keys is not exactly a fix here.  It should be possible to mute missing key warnings as there is a natural delay between a string being introduced and its localization being available for all languages. Especially for projects that support a lot of locales!

There have been similar issues in the past that have asked for this exact functionality. See https://github.com/mac-cain13/R.swift/issues/496

That said there is some long running work going on in https://github.com/mac-cain13/R.swift/issues/136 that would eventually allow for this. My understanding is that its not a priority for the maintainers at the moment though.

I for one would second prioritizing this as I like to run a 0 warnings project and there is very little I can do about translations as a developer. Having the warnings is still great for checking production builds but makes for a lot of false positives during active development.

Just my 2 cents.

Best,

Caio

**Comment by mac-cain13** [comment]
It's not very easy to create this and I also think the warning is correct. You as a developer should be aware the translation is missing, so it won't ship accidentally in a release for example.

0 warnings in a project is nice, but silencing a warning that is there and is correct is not the way to go in my opinion. So this is not something R.swift will support unless there is a use case for not always having all translations present that we haven't considered yet.

**Comment by Igor-Poltavtsev** [comment]
@mac-cain13 we use automated translation system, so we don't need to do this manually. The issue is in warnings, that we have while translation is in progress. But we have a decision to keep our project free of warnings. Is it possible to do something?

**Comment by kustra** [comment]
For anyone finding this later, here's a workaround. Instead of using

    "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"

use this:

    set -o pipefail
    "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift" | (grep -v "warning: \\[R.swift\\] Strings file '[^']*' ([a-zA-Z0-9_]*) is missing translations for keys" || true)
