### ISSUE TITLE
R.swift loading assets in a resource bundle

### ISSUE THREAD

**Issue by kylelol** [mac-cain13/R.swift#662]
I use a resource bundle for a framework I am working on so that it can be linked statically. 
In order to load the assets from the resource bundle, the way R.swift loads the bundle using `Bundle(for: R.Class.self)` does not work. 
Is there a way to make R.swift work with resource bundles?

**Comment by tomlokhorst** [comment]
It's currently not possible to use resource bundles with R.swift

We are tracking this issue here: #186
