### ISSUE TITLE
R.swift files are going missing or are corrupt

### ISSUE THREAD

**Issue by ann-and-art** [mac-cain13/R.swift#664]
In the past few weeks some of the R.swift.Library files are going missing or are corrupt, almost every time I create a new branch or checkout a previous one. Just today I created from a perfectly functioning and healthy master a new branch. But this new branch has corrupt files in the R.swift.Library.
Any idea how that could happen? Unfortunately right now I have no idea what causes the problem and how to avoid it. I'm working with the new MacOS Big Sur and also sometimes using Xcode Beta 12. But the problem is not just limited to Xcode Beta 12. R.swift is installed as a pod.

**Comment by mac-cain13** [comment]
Sorry to hear this. Not sure what's the cause of this, maybe this is a Big Sur issue, but I have no machine to check this currently. We'll investigate more if this happens on the release version of Big Sur.
