### ISSUE TITLE
UIImages are optional, which makes me to use force unwrap

### ISSUE THREAD

**Issue by andrey-sergeenko-appcraft** [mac-cain13/R.swift#665]
Hi, I use R.swift, and it saves me a lot of time, thank you!
But I have a question:
What is the motivation behind using "UIImage?" instead of "UIImage"?
In my code, having UIImage as optional mostly does not make any sense, because many models imply the fact, that there IS some image.
I am trying to avoid using force unwraps.
Looking forward to discuss this topic, thanks!

**Comment by mohwaili** [comment]
+1
Same applies for UIColors, what is the point of making it optional?

**Comment by shinwan2** [comment]
For UIImage, I found these existing discussions: https://github.com/mac-cain13/R.swift/issues/160, https://github.com/mac-cain13/R.swift/issues/109, https://github.com/mac-cain13/R.swift/issues/61.

**Comment by mac-cain13** [comment]
This is a design choice for now. It is the most debated design decision also, so it might some day be reconsidered if we do a big refactor. But for now we'll leave it as is.

**Comment by ashleymills** [comment]
I'm having this issue with UIColor generation.

I'd really like to use R for colours alongside the strings I'm already using - but it will require me to add (literally) hundreds of force unwraps throughout the app, which is obviously a non-starter.

Could this be handled by passing a flag to generate non-optionals?

**Comment by mbernson** [comment]
Hi,

> Could this be handled by passing a flag to generate non-optionals?

We've considered this, but would like to keep the core of R.swift simple. In my opinion, R.swift should not be generating code that can potentially crash (but doesn't indicate it). The generated code calls `UIColor.init(named:)` which may return nil. 

To prevent spreading lots of force unwrapped optionals and have shorthand access, we usually create an extension on UIColor like so:

```
public extension UIColor {
  static var primaryBackground: UIColor { R.color.primaryBackground()! }
  static var secondaryBackground: UIColor { R.color.secondaryBackground()! }
  // etcetera...
}
```

**Comment by ashleymills** [comment]
Hi @mbernson  - thanks for the quick response, and I understand where you're coming from. 

In our project we have an `rswift generate` as the first build phase, so we're guaranteed that all colour assets will be available at run time. We already have an extension on UIColor as you suggest, just wrapping `UIColor(named:)` instead of the `R.color.…`. We were hoping that R would allow us lose that but unfortunately not, so I guess it's not the right fit for our project. It's brilliant for Strings though!

Again, thanks for your response.

**Comment by kornerr** [comment]
R.swift misses forced unwrapping
