### ISSUE TITLE
LocalizedString key containing newline generates (some) invalid code

### ISSUE THREAD

**Issue by vadimvitvickiy** [mac-cain13/R.swift#666]
Latest version where R.generated were compiling was 5.1.0.alpha.4
<img width="763" alt="Screenshot 2020-09-21 at 13 00 23" src="https://user-images.githubusercontent.com/5019512/93746232-38beee00-fc0e-11ea-8ebe-9f65f4fb5dd6.png">

**Comment by tomlokhorst** [comment]
Hi, thanks for creating this issue. Can you elaborate on why you've closed this?

Did you fix the issue? If so, how?
In case other people run into the same issue in the future.

**Comment by vadimvitvickiy** [comment]
Hi, sorry for not providing explanation on this.
I have closed issue cause I understood the reason was about `\n` in `key` of localised string, which is kinda wrong in my opinion.

**Comment by tomlokhorst** [comment]
Thanks for letting us know the issue!

I agree it's a bit weird to have a newline in the key.
But still, R.swift should escape the key here and not generate invalid code. I'll file this as a bug in R.swift.
