### ISSUE TITLE
How to change language at runtime?

### ISSUE THREAD

**Issue by kent2508** [mac-cain13/R.swift#667]
Could I change language using "R.string.localizable.xxx" at runtime?
Or could I change the hostingBundle to reupdate language for app at runtime?

**Comment by tomlokhorst** [comment]
You can pass your own list of preferred languages to each string function.

For example, to get French: `R.string.localizable.welcome(preferredLanguages: ["fr"])`

**Comment by kent2508** [comment]
> You can pass your own list of preferred languages to each string function.
> 
> For example, to get French: `R.string.localizable.welcome(preferredLanguages: ["fr"])`

But if I wrote thousands code lines "R.string.localizable.xxx" without (preferredLanguages: ["xx"]), how can I replace them automatically?

**Comment by tomlokhorst** [comment]
There's is no feature in R.swift to automatically change preferredLanguages.

**Comment by kent2508** [comment]
> There's is no feature in R.swift to automatically change preferredLanguages.

So, how can I using preferredLanguages with format strings? Add preferredLanguages as second param?

**Comment by tomlokhorst** [comment]
Yes, preferredLanguages is always the last parameter to the generated function.
