### ISSUE TITLE
R.swift.Library Carthage build failed without error

### ISSUE THREAD

**Issue by norbdev** [mac-cain13/R.swift#669]
Xcode 12.0.1, Carthage 0.36.0

`carthage update R.swift.Library --platform iOS`

> *** Building scheme "Rswift-iOS" in R.swift.Library.xcodeproj
> Build Failed
> 	Task failed with exit code 1:

In the log file I can't find any error, If I open the project and build it with Xcode the build is success.

**Comment by piv199** [comment]
This is kinda Carthage-xCode error
https://stackoverflow.com/questions/63946945/bringing-ios-frameworks-through-carthage-in-xcode-12-0

**Comment by norbdev** [comment]
I use the workaround and many framework can build with it, but the R.swift.Library can't.
https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

**Comment by mac-cain13** [comment]
I'm not sure how to fix this Carthage <-> Xcode issue, I'm open to a solution/PR if someone knows what the fix should be.

**Comment by norbdev** [comment]
With Xcode 12.0.1 and the latest workaround (https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) the build was success
