### ISSUE TITLE
registerNibForHeaderFooterView<T: NibResource where T: Reusable, T.T: UIView> call error

### ISSUE THREAD

**Issue by 441088327** [mac-cain13/R.swift#67]
registerNibForHeaderFooterView<T: NibResource where T: Reusable, T.T: UITableViewHeaderFooterView>  is right。
please

**Comment by mac-cain13** [comment]
Thanks for using R.swift. Do you have an example what code is giving you an error? I don't get a call error over here right now so an example would be very helpful! :)

**Comment by 441088327** [comment]
Error like this 
![image](https://cloud.githubusercontent.com/assets/1632740/9265936/014a36f6-426d-11e5-930d-4d71f097d682.png)

this is my 
error view class like this 
![image](https://cloud.githubusercontent.com/assets/1632740/9265941/1b968758-426d-11e5-9850-fa3ae32c3d68.png)

**Comment by mac-cain13** [comment]
Thank you for writing a blog.

Does your `DNContactSectionView` have a reuse identifier set in the nib? You must set the reuse identifier to be able to register the nib. Maybe this is the problem?

**Comment by mac-cain13** [comment]
I'll close this one, feel free to comment if you still need help!

**Comment by kylebshr** [comment]
I'm running into the same issue; and I believe that #144 addresses this as well? Just wondering if there's a way to do it that I'm not seeing.
