### ISSUE TITLE
Run the script manually and not as a build phase?

### ISSUE THREAD

**Issue by O-labib** [mac-cain13/R.swift#670]
Is there a way to update the R.generated by running a script manually when there is a need, instead of building the whole app ?

**Comment by mac-cain13** [comment]
No this is not possible, R.swift depends on many variables Xcode provides during build. Locations of files, what files are used in the project and what not. In theory you can provide all these variables yourselves, but in practice you never want to do this and it is error prone. So I would strongly recommend to just build the project. 

Note that after R.swift has been run you can cancel the build if you want, you do not have to wait for all files to compile.
