### ISSUE TITLE
There is an error when I run 'pod repo push' in my cococopods library

### ISSUE THREAD

**Issue by lmqleo** [mac-cain13/R.swift#672]
Sorry For My Poor Engilsh, I will try to explain my problem

> MacOS: 10.15.7
> iOS: 13.5.1

I add R.swift to my library by this: 
![image](https://user-images.githubusercontent.com/23546890/95853851-a16e3600-0d88-11eb-8d9d-0a570e5dd55f.png)

and I add Resource.swift to my Xcode project:
![image](https://user-images.githubusercontent.com/23546890/95853969-d084a780-0d88-11eb-89ea-a753bf4f5f14.png)

Here is my podspec:
![image](https://user-images.githubusercontent.com/23546890/95855299-bc41aa00-0d8a-11eb-9c33-6aae3f8a822e.png)

when I build my project or run `pod lib lint`, it's successful. 
But when I run `pod spec push`, there is an error showing.
![image](https://user-images.githubusercontent.com/23546890/95854731-e8a8f680-0d89-11eb-8521-503fa95cb07b.png)

How can i fix it？

**Comment by mac-cain13** [comment]
`pod repo push` is for library maintainers to publish a new version. You should never have to use this as user of R.swift, just follow the readme for instructions.
