### ISSUE TITLE
R.swift.clr is missing

### ISSUE THREAD

**Issue by GautierLouis** [mac-cain13/R.swift#676]
Hello,
First of all, I'm new to iOS development. There is many things I don't understand and I'm not sure that my issue is a real bug or a misunderstood. 

Config : 
Swift 4.2, Xcode 12.1, Legacy Build System, minimum iOS Deployment 11
R.swift was installed manually and R.swift.Library was installed from carthage in v4.2 

To fit ours need, I must upgrade R.swift.Library to v5 (to use `preferredLanguages` on localized strings)

What I've done :
Removed R.swift script and install the new version using `brew install rswift`. Works great
Upgrading R.swift.Library using carthage using `carthage update R.swift.Library --platform iOS`. Working great
Change the run scrip in Build phases by `rswift generate --disable-input-output-files-validation "somepath/R.generated.swift"` (just following the [migration page](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md)).

The script was created, but Swift compiler found many errors. Apparently `R.clr.ios.red()` does no exist. This is where I'm stuck.

I can't figured why R.clr is not generated. Is it deprecated ? if yes, witch method am I supposed to use ?

Is there a version where I can use `preferredLanguages` on localized strings AND use `R.clr.someColor` ?
 
Thanks,

Louis

**Comment by mac-cain13** [comment]
I'm sorry, but CLR support was deprecated in version 4 and removed in version 5. Xcode asset catalogs are the way to go if you want to reference colors in your project.

See also: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-40
