### ISSUE TITLE
5.3.0 Build failed via Mint

### ISSUE THREAD

**Issue by ChristianMoler** [mac-cain13/R.swift#679]
Hello!
After v5.3.0 release I have a build error. v5.2.2 work fine

🌱 Finding latest version of R.swift
🌱 Cloning R.swift v5.3.0
🌱 Resolving package
/private/var/folders/3h/ylg_wsg14jvdhqprq7sbwsth0000gn/T/mint/github.com_mac-cain13_R.swift: error: manifest parse error(s):
<unknown>:0: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX'
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.15'
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve R.swift v5.3.0 with SPM

**Comment by venturafonso** [comment]
Getting this issue as well

**Comment by ABTGarcia** [comment]
Same here, in my case is when I execute a Run Script Phase the the line "mint run R.swift rswift generate --accessLevel public --generators image,string,color,font "$SRCROOT/R.generated.swift"".

**Comment by venturafonso** [comment]
Found the cause, the library version was mis matched with the main rswift project, make sure they are both running 5.3.0

**Comment by ABTGarcia** [comment]
Wow thank you very much! Now it works, you saved my day!

**Comment by zac** [comment]
I'm getting this again. It might be back now that there is a 5.3.1 released for R.swift and only a 5.3.0 for R.swift.Library. /cc @tomlokhorst

**Comment by tomlokhorst** [comment]
I'm unsure about this, as I don't use mint.
But I think I did something wrong with the 5.3.1 release, because it's missing assets.

For now I suggest pinning to the 5.3.0 release, while I'm working on a 5.3.2.

**Comment by tomlokhorst** [comment]
I've recreated 5.3.1, all assets should now be available with that release.
