### ISSUE TITLE
R.swift regenerate every time I build the app

### ISSUE THREAD

**Issue by remlostime** [mac-cain13/R.swift#682]
I found every time R.swift will regenerate the file when I build the app. But even I didn't change any resource it will do it. Sometimes it just swipe some lines but the generated file is actually the same. That's super annoying for the git system. Is there a way to avoid regenerate the file if nothing changes? Or is there a way to let R.swift keep generate the file at the same sequence?

**Comment by tomlokhorst** [comment]
There was a bug in 5.3.0 causing inconsistent sorting.

As of 5.3.1, the generated file should again be consistent, with all lines in same order every time. 

Can you check if updating to 5.3.1 fixes your issue?

**Comment by remlostime** [comment]
I think it's mainly cased by this validation code sequence - https://github.com/mac-cain13/R.swift/blob/master/Sources/RswiftCore/Generators/ValidatedStructGenerator.swift#L19

![image](https://user-images.githubusercontent.com/3702498/102121520-f239f380-3df8-11eb-96c2-525b8418e295.png)

**Comment by remlostime** [comment]
Let me try the latest version. Thanks @tomlokhorst !
