### ISSUE TITLE
Generating multiple R.generated.swift files in multiple targets

### ISSUE THREAD

**Issue by janbjelicic** [mac-cain13/R.swift#684]
Hi,

I'm using R.swift in my library (framework) for my localized strings and I wanted to start using R.swift in my main target for other resources like images, colors and other files that I would be generating from there. 

The issue I'm encountering is when I generate a R.swift.generated file in my main target (and include it in the project) it overrides the R.swift.generated file from my framework and I'm getting build errors in places where I'm using R.swift for localizations in my main target saying that 
Type `R` has no member `string`
Type `R` has no member `localization`

My question would be is it possible to somehow generate a file that has a `Resources` struct instead of `R` struct so that the compiler can distinguish between the two files?

Maybe as a help, this type of thing is possible with SwiftGen, I know this since I'm transferring the resource handling from SwiftGen to R.swift :)

**Comment by RustamKhisamov** [comment]
Did you find solution? Maybe change a name R.generated in the second target?

**Comment by janbjelicic** [comment]
No I haven't, tried changing the file name but it didn't help. The issue isn't the file name but the generation itself and the class and struct names that are generated. Since it is not possible to change those the problem stays.

**Comment by RustamKhisamov** [comment]
Yeah, I mean struct name

**Comment by RustamKhisamov** [comment]
For me it works if I do this:
Create new file and add only this

`
import struct SubWorkspace.R

typealias SubWorkspaceR = SubWorkspace.R
`

**Comment by tomlokhorst** [comment]
As mentioned, the supported method is to use the fully qualified name from the library.

```swift
import MyLibrary

...

MyLibrary.R.string.settings.title()
```
