### ISSUE TITLE
Not supporting images in Assets.xcassets

### ISSUE THREAD

**Issue by bimsoe** [mac-cain13/R.swift#69]
Images I placed inside Assets.xcassets are not getting strong-typed. 

Everything else seems to work file - storyboards/view-controllers/xibs etc.
I have integrated R.swift using pod in my project.

Using Swift 1.2
Xcode 6.4

**Comment by mac-cain13** [comment]
Thanks for using R.swift!

The images in your `Assets.xcassets` should be under `R.image.theNameOfTheImage`, could you check if they are there? You also could open the `R.generated.swift` file and search of the name of an image in the assets folder, can you find one of them?

Please let me know what your findings are!

**Comment by bimsoe** [comment]
![screen shot 2015-08-19 at 1 56 38 pm](https://cloud.githubusercontent.com/assets/8776860/9351832/277a41fc-467a-11e5-9d1f-af11b5db1597.png)

I did check the R.generated.swift but   
struct image {    }
is empty.
![screen shot 2015-08-19 at 1 58 06 pm](https://cloud.githubusercontent.com/assets/8776860/9351851/5a22a464-467a-11e5-851f-91703bd1e8ea.png)

**Comment by mac-cain13** [comment]
That's quite strange! What is the location on disk of the xcassets folder? Is it in the folder R.swift is scanning on disk?

**Comment by bimsoe** [comment]
Ah! That was the issue. I had given 'Resources' folder path for R.swift but by default xassets is created at project directory-level. Moving it to Resources folder fixed the issue. Thanks
Damn! I feel so stupid right now.

One quick question though. Is it possible to provide multiple paths to R.swift or may be recursive path?

**Comment by mac-cain13** [comment]
Happens to the best of us! A future version of R.swift will look into your project file to avoid this kind of issue.

And yes, you can just add an extra folder as argument, but R.swift will generate a seperate `R.generated.swift` file for each argument so I don't know if that would be a solution for you. Probably the  to be implemented "project file"-approach will fix your issue in a more structural way.

**Comment by bitomule** [comment]
I can't make RSwift recognize images inside xcassets. Moved to resources folder but still not present. It only find those images as file resources, not images :(
