### ISSUE TITLE
x86_64+arm64 fat binaries

### ISSUE THREAD

**Issue by vincentisambart** [mac-cain13/R.swift#691]
The binaries provided are currently x86_64 only.
Thanks to Rosetta, that works without any problem on M1 Macs, but it would be nice to have fat binaries supporting both arm64 and x86_64.

**Comment by tomlokhorst** [comment]
Yes, this is a good thing to do!

I'm not quite sure how to do it however... 🙂

**Comment by tomlokhorst** [comment]
I'm trying to create a fat binary, using the following steps:

```
swift build -v -c release -Xswiftc "-target" -Xswiftc "arm64-apple-macos11"
mv .build/release/rswift .build/release/rswift-arm64
swift build -v -c release -Xswiftc "-target" -Xswiftc "x86_64-apple-macos11"
mv .build/release/rswift .build/release/rswift-x86_64
lipo -create .build/release/rswift-arm64 .build/release/rswift-x86_64 -output .build/release/rswift
```

(From the [workflow](https://github.com/mac-cain13/R.swift/blob/architectures/.github/workflows/release.yml#L36-L42))

However, for some reason, this didn't produce a fat binary in the release: https://github.com/mac-cain13/R.swift/releases/tag/v5.4.1-alpha.3

**Comment by vincentisambart** [comment]
If you're using SPM and a recent version of Xcode it seems you don't even need to manually call lipo: https://liamnichols.eu/2020/08/01/building-swift-packages-as-a-universal-binary.html

**Comment by tomlokhorst** [comment]
Oh great, thanks!

I thought I had tried that already, and it didn't work. But apparently I did something wrong, because now it does work.

This is the new alpha release: https://github.com/mac-cain13/R.swift/releases/tag/v5.4.1-alpha.5

**Comment by murentsev** [comment]
> The binaries provided are currently x86_64 only.
> Thanks to Rosetta, that works without any problem on M1 Macs, but it would be nice to have fat binaries supporting both arm64 and x86_64.

Hey! Help please, I was able to install the pod, but it does not work in the project. Please tell us in more detail what needs to be done to make it work on the m1 chip?

**Comment by mac-cain13** [comment]
The binary should just work as long as you follow the instructions in the [Readme](https://github.com/mac-cain13/R.swift#installation).

What do you mean by "but it does not work in the project"? Do you have an error? Is there a reproduction path? Did you follow the instructions in the Readme?

**Comment by murentsev** [comment]
> The binary should just work as long as you follow the instructions in the [Readme](https://github.com/mac-cain13/R.swift#installation).
> 
> What do you mean by "but it does not work in the project"? Do you have an error? Is there a reproduction path? Did you follow the instructions in the Readme?

I'm sorry. my problem had nothing to do with this pod. in any case, thanks for your prompt reply and your job!))

**Comment by alwold** [comment]
Does anyone have a status update on this issue? I'm seeing crashes running the `rswift` command under Rosetta on an M1 Pro. I'd be happy to help move this forward if there's anything I can do.
