### ISSUE TITLE
Homebrew Rswift no such module

### ISSUE THREAD

**Issue by RustamKhisamov** [mac-cain13/R.swift#692]
Hi!
I installed Rswift by homebrew. Add script to generate R.generated.swift file.
`"rswift" generate --accessLevel public "$SRCROOT/PATH/R.generated.swift"`

but I have this issue:
<img width="1224" alt="Снимок экрана 2021-03-03 в 13 33 27" src="https://user-images.githubusercontent.com/14363621/109792889-0be31e00-7c25-11eb-8fde-e208554852eb.png">

Maybe I'm missed something. Because in Readme in Homebrew section is not another information.

**Comment by tomlokhorst** [comment]
You also need to include the [R.swift.Library](https://github.com/mac-cain13/R.swift.Library) library, that exposes the Rswift module.

**Comment by RustamKhisamov** [comment]
> You also need to include the [R.swift.Library](https://github.com/mac-cain13/R.swift.Library) library, that exposes the Rswift module.
Thanks. It'll be cool if you add it to Readme
