### ISSUE TITLE
iPadOS support?

### ISSUE THREAD

**Issue by nurbekismagulov** [mac-cain13/R.swift#697]
Hello,
I am wondering if there is a way of using R swift images on iPadOS? Our app was written with the help of your library and now we have to support iPads too. After crashing of app on iPad I looked at generated R file and saw this line:
`#if os(iOS) || os(tvOS)`

**Comment by tomlokhorst** [comment]
R.swift works on iPad.

The generated code from R.swift works the same on iPadOS as it does on iOS on iPhone. `#if op(iOS)` works for iPadOS too.

Can you post the exact error message you see?
