### ISSUE TITLE
Question about % sign in values

### ISSUE THREAD

**Issue by soconnor-florio** [mac-cain13/R.swift#699]
Consider the following Key-Value Pair:
"percent_finished" = "Completed: %d%";

on iOS, for this to display the percent sign, you need to escape the % character:
"percent_finished" = "Completed: %d%%";

Our Localization project is hosted on Phrase.com and is multi-platform.  The "percent_finished" matches the first example above, so it isn't displaying properly since moving from R.swift to SwiftGen for some of our assets.  I believe it was working when generating with R.swift.

Is R.swift adding any missing percent sign, and if so, where can I see that in the code?

Thanks

**Comment by tomlokhorst** [comment]
R.swift is not adding a percent sign or doing any modifications to strings. It uses NSLocalizedString as-is.
