### ISSUE TITLE
Strong type any files in the Resources directory

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#7]
For example; audio files in the `Resources` directory, including directory hierarchy.

![screen shot 2014-12-15 at 11 16 34](https://cloud.githubusercontent.com/assets/75655/5433883/de1c06da-844b-11e4-8a33-c30f6e63aefd.png)

**Comment by mac-cain13** [comment]
I think we shouldn't copy the hierarchy since after compilation this is lost, so duplicate filenames are not allowed and also not used by Apple's SDK right now. But it would be awesome to be able to load audio, movie and other resources with R.swift.

**Comment by mac-cain13** [comment]
Fixed by PR #88
