### ISSUE TITLE
Illegal text reloc 

### ISSUE THREAD

**Issue by varunchanni** [mac-cain13/R.swift#701]
Getting below error in Xcode 12.3 while archiving, there is no such issue when running app

illegal text reloc in '_$s6Rswift32StoryboardViewControllerResourceV10identifierACyxGSS_tcfC_plus_-4194248.island.0' to '_$s6Rswift32StoryboardViewControllerResourceV10identifierACyxGSS_tcfC' for architecture armv7

Any suggestions how to resolve it?

**Comment by tomlokhorst** [comment]
This happens when you don’t reference the R.swift.Libary library from the target you’re trying to build.
