### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by aysennmt** [mac-cain13/R.swift#702]
Hi, I have applied the CocoaPods steps. I get an error when I build.  What is the solution to this problem?

<img width="287" alt="Screen Shot 2021-05-05 at 19 38 35" src="https://user-images.githubusercontent.com/22594007/117208256-969af180-adfd-11eb-9319-5e0cf496f964.png">

Thank you

**Comment by tomlokhorst** [comment]
https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file

**Comment by aysennmt** [comment]
> https://github.com/mac-cain13/R.swift/blob/master/Documentation/QandA.md#how-to-fix-missing-imports-in-the-generated-file

Thank you, but I looked but did not understand. How do I resolve "Cannot find type x in scope" errors? May you give an example
