### ISSUE TITLE
Fallback to default / next preffered language in case of mising translation for given key

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [mac-cain13/R.swift#704]
Hi!
This library is amazing, I'm uisng it in every project i'm working on! 

Although its perfect when all translations are available, sometimes it gets bothersome when some translations are missing. 

There are cases when we want to push build to App Store, but we don't have translations yet and we don't want to block releases just because of few missing translations. 

Is there is an option, to add optional flag to generation process, to add falback behaivour? 

Its easy to implement those changes, that would add this behaviour to this libary. 
I'd love to know your opinion on that before implementing those changes.

**Comment by CaioSym** [comment]
I've actually opened a ticket AND PR for exactly this:
https://github.com/mac-cain13/R.swift/issues/563
https://github.com/mac-cain13/R.swift/pull/564

I'd love to see some progress on those :(

**Comment by tomlokhorst** [comment]
Fallback to development language is now available in version 7.0.0

**Comment by spipau** [comment]
Half a year a go we started searing for a solution to this localisation mess in iOS and tested the behaviour with v6.x. Now as we really need it, I was delighted to read that v7.x supports this out of the box! @tomlokhorst you made my day! As I use this magnificent library for years now and it's probably the first one I always add to new projects, how can I buy you a 🍺 or a ☕ ?
