### ISSUE TITLE
R.generetade.swift is missing in Private pod library, when runnning pod install

### ISSUE THREAD

**Issue by sandeeprachha** [mac-cain13/R.swift#713]
Hi team
I'm trying to add R.swift in our custom pod library which is installed in our project. I have added run script in Podspec and able to generate script, input, output files in build phases of Pods.xcodeproj and drag and drop the R.genereted.swift in Xcode Pods. But if we make any changes in pod and installs again in our project, then R.generated,swift is missing from Xcode. 
Requesting you to how to resolve this issue, to keep R.generated.swift always even after pod install.

**Comment by XiMuYouZi** [comment]
> Hi team
> I'm trying to add R.swift in our custom pod library which is installed in our project. I have added run script in Podspec and able to generate script, input, output files in build phases of Pods.xcodeproj and drag and drop the R.genereted.swift in Xcode Pods. But if we make any changes in pod and installs again in our project, then R.generated,swift is missing from Xcode.
> Requesting you to how to resolve this issue, to keep R.generated.swift always even after pod install.

I am also in this matter，How can I added run script in Podspec and able to generate script, input, output files in build phases of Pods.xcodeproj ？Could you provide the script，thx

**Comment by sandeeprachha** [comment]
@XiMuYouZi 
 s.dependency 'R.swift'
  s.script_phases = [{
       :name => 'R',
       :script => '"$PODS_ROOT/R.swift/rswift" generate --accessLevel public "$SRCROOT/PodlibraryName/R.generated.swift"',
       :execution_position => :before_compile,
       :input_files => ["$TEMP_DIR/rswift-lastrun"],
       :output_files => ["$SRCROOT/PodlibraryName/R.generated.swift"]
    }]

**Comment by rakuyoMo** [comment]
> @sandeeprachha @XiMuYouZi
> 
> Change the path of your output file to your Pod Library Source directory. Then when you run pod install it will be always there.
> 
> ```
>   s.script_phases = [{
>     :name => 'R',
>     :script => '"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/../<PodLibraryName>/Classes/R.generated.swift"',
>     :execution_position => :before_compile,
>     :input_files => ["$TEMP_DIR/rswift-lastrun"],
>     :output_files => ["$SRCROOT/../<PodLibraryName>/Classes/R.generated.swift"]
>   }]
> ```

So how do I add the R.generated.swift file to the project?

**Comment by udbhateja** [comment]
> > @sandeeprachha @XiMuYouZi
> > Change the path of your output file to your Pod Library Source directory. Then when you run pod install it will be always there.
> > ```
> >   s.script_phases = [{
> >     :name => 'R',
> >     :script => '"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/../<PodLibraryName>/Classes/R.generated.swift"',
> >     :execution_position => :before_compile,
> >     :input_files => ["$TEMP_DIR/rswift-lastrun"],
> >     :output_files => ["$SRCROOT/../<PodLibraryName>/Classes/R.generated.swift"]
> >   }]
> > ```
> 
> So how do I add the R.generated.swift file to the project?

@rakuyoMo R.generated.swift file is automatically created. Also the above script takes care of moving the file to the desired location. No need to do these things manually.

PS: If you are unable to see the R file, try 'pod install' again and it will be there.

**Comment by rakuyoMo** [comment]
> R.generated.swift

I have added this script to my `podspec` file and when I execute the `pod lib lint` command, it prompts me that I cannot find the `R` structure. 

Should I add the path to `R.generated.swift` to the `source_files` parameter? If so, is there any advantage to this way of adding scripts to the podspec file compared to directly using the `R.generated.swift` file generated when compiling the project?

**Comment by udbhateja** [comment]
Have you added 'R' to dependencies as s.dependency = 'R'
If not, add this dependency.

> Should I add the path to R.generated.swift to the source_files parameter? If so, is there any advantage to this way of adding scripts to the podspec file compared to directly using the R.generated.swift file generated when compiling the project

Manually this won't work. Every time 'pod install' is run.Developer would have to manually copy-paste the file.

**Comment by therohansanap** [comment]
I am facing same problem as @rakuyoMo has described. Initially, R.generated.swift is not present at the time of running `pod install`, hence it is never gets added to the list of source files that are part of my development pod. The phase script from podspec file is executed after pod install, hence, even if it generates the required file and places it at the right place, it is never part of compilation. It only becomes part of compilation after second pod install (if the file was generated previously). This is a problem at CI phase.

**Comment by udbhateja** [comment]
@therohansanap Right! Initially a `pod install` is required to generate the **R.generated.swift** file. Second one to add it to the bundle as mentioned in the script.
Maybe some tweaks to script that copies the file after `pod install` is performed can help.

**Comment by therohansanap** [comment]
For anyone who want to fix this for every new clone (should build at first go), I fixed this via a workaround:

1. Add the phase script mentioned above to podspec file of MyFramework.

2. Add a lane in Fastfile (use can use a bash script instead of fastlane lane):
```
lane :build_my_framework do
    cocoapods(podfile: "path/to/MyFramework/Podfile")
    build_app(
      workspace: "path/to/MyFramework/MyFramework.xcworkspace",
      configuration: "Debug",
      scheme: "MyFramework",
      clean: true,
      skip_archive: true,
      skip_codesigning: true,
      silent: true
    )
end
```

3. Add a `pre-install` hook to Podfile
```
pre_install do |installer|
  exists = File.exists?('path/to/MyFramework/Resources/Generated/MyFramework.R.generated.swift')
  if exists != true
    system("bundle exec fastlane ios build_my_framework")
  end
end
```

I would have considered using `prepare_command` inside podspec file, but it does not work if the pod is integrated via `:path` directive.

**Comment by udbhateja** [comment]
@therohansanap Thanks for this workaround. Any idea for developers not using fastlane or any other CI tool?

**Comment by therohansanap** [comment]
@udbhateja fastlane was just a convenience choice for building framework project. You can use a custom shell script here instead of fastlane.
