### ISSUE TITLE
Cannot archive a project

### ISSUE THREAD

**Issue by onl1ner** [mac-cain13/R.swift#718]
Hello! We came across a problem that does not allow us to archive our project. The problem is that the archiving process cannot be ended because of an error: *"Cannot find 'R' in scope"*, but when we build our project error disappears.

Specs: 
- Xcode 12.5.1
- R.swift 5.4.0

`R.swift` is added **manually** and here is our `Run Script`(before `Compile Source`):

![image](https://user-images.githubusercontent.com/45308586/133104495-6e01d39e-8cf8-439f-bc23-879786f1fbbd.png)

**Comment by tomlokhorst** [comment]
I've not seen this for Xcode 12 before.
Are you sure you're not running Xcode 13 and encountering [this issue](https://github.com/mac-cain13/R.swift/issues/719)?

**Comment by onl1ner** [comment]
We are on Xcode 12.5.1 and did not update our Xcode version yet
