### ISSUE TITLE
Including R.swift into framework

### ISSUE THREAD

**Issue by pervij-raz1** [mac-cain13/R.swift#720]
Hi everyone!
I used R.swift for my project for a while. Today I transferred all the resources to the separate module (xcodeproj) and added this new module to other modules as a framework. In my Podfile I kept R.swift only for the new module, but when I build the product I'll get an error "Cannot load underlying module for Rswift". Could you help me with this?

**Comment by tomlokhorst** [comment]
You also need to include R.swift.Library project in your separate module. That projects provides the Rswift module.
