### ISSUE TITLE
Cannot generate R.generated.swift

### ISSUE THREAD

**Issue by koolfreak** [mac-cain13/R.swift#721]
Hi, i configure my project as describe in the installation guide but i cannot see the generated R.generated.swift?
I also notice that there is no executable file Pods/R.swift/rswift?

im using xcode 13

Thanks

**Comment by tomlokhorst** [comment]
Which installation steps are you following?

If you're following the [CocoaPods](https://github.com/mac-cain13/R.swift#cocoapods-recommended) steps, it should install the executable. If you don't have the executable, you also can't generate the R.generated.swift file.

**Comment by koolfreak** [comment]
yes, im using cocoapods steps. yes there is no executable. sadly i already uninstall the pod. Do you have any idea why the executable does not install on my machine?

![image](https://user-images.githubusercontent.com/1182352/135477429-59c75abb-5cdb-4708-8f8e-72520a25ea98.png)

Attached is the screenshots

Thanks

**Comment by tomlokhorst** [comment]
The executable isn't shown in Xcode, it exists on the file system and is visible in Finder.

**Comment by koolfreak** [comment]
thanks saw it, but still it does not generate the R.generated.swift, i cannot see it on the Finder?

**Comment by tomlokhorst** [comment]
As per the installation instructions, you need to add a build phase that will generate the file.

**Comment by koolfreak** [comment]
Already added it

![image](https://user-images.githubusercontent.com/1182352/135480733-8e6f808d-5b72-4e51-a252-dcd681223154.png)

**Comment by tomlokhorst** [comment]
The $SRCROOT/R.generated.swift file should be in the "Output Files" (see installation instructions).
And the checkbox "For install builds only" should not be checked. 

Note that there is currently an [open issue](https://github.com/mac-cain13/R.swift/issues/719) about a bug in Xcode 13 where it will sometimes give a build error. But everything should work correctly in Xcode 12.
