### ISSUE TITLE
Home can i specify the resource file, read resource faild

### ISSUE THREAD

**Issue by BTCherryKing** [mac-cain13/R.swift#728]
My project structure is as follows
```
- MainApp
- HomeModule
- ProfileModule
```
MainApp does not depend on any libraries.
HomeModule and ProfileModule depend on R.swift, they have their own resource files

I want them to generate their own R.generated.swift file. R.generated.swift was successfully generated, but no resource files were read.

[Example.zip](https://github.com/mac-cain13/R.swift/files/7378193/Example.zip)

Thanks

**Comment by tomlokhorst** [comment]
This should now work correctly in Rswift 7.0.0
