### ISSUE TITLE
Custom class for UITableViewCell error

### ISSUE THREAD

**Issue by Ewg777** [mac-cain13/R.swift#73]
1. Configure Podfile
```ruby
use_frameworks!
pod 'MGSwipeTableCell'
pod 'R.swift' #swift 2.0
```
2. ![Image of Yaktocat](http://i.imgur.com/rn7mWk3.png)
3. Run
4. Got ![Image of Yaktocat](http://i.imgur.com/MzWwRoV.png)

R.swift should add "import" in the begining

**Comment by mac-cain13** [comment]
Thanks for reporting this problem, I'll look into it! Will be a harder one to solve since it's a ObjC thing that you have to import that class, but there should be a reasonable solution!

**Comment by henriquesobral** [comment]
I'm getting the same error, but I'm not using any 3rd party custom class, it's a simple subclass that I've created.

```swift
static var addNewCardCell: ReuseIdentifier<Sallute.AddNewCardCell> { return ReuseIdentifier(identifier: "AddNewCardCell") }
```
and the error returned was ```Use of undeclared type 'Sallute'```, where Sallute is my project.

**Comment by mac-cain13** [comment]
@henriquesobral `Sallute` should also be the module name the `AddNewCardCell` is defined in. Is that the case? Did you do anything special with the module name and is/was it working without R.swift?

**Comment by henriquesobral** [comment]
Yes. Sallute is the project and the module. Yes it was working without R.swift, and now it's working with R.swift after I removed the test project (SalluteTests) from **Target Membership** of ```R.generated.swift``` file

**Comment by mac-cain13** [comment]
This one is superseded by #98, we should fix the `import` problem all at once I think. That would also fix this issue.
