### ISSUE TITLE
How to clean up discarded image resources?

### ISSUE THREAD

**Issue by luoxiao** [mac-cain13/R.swift#736]
Hi,
I have used R.swift for my engineering project for three years,
Due to the long iteration of the update, many pictures in the project are not used,
How to find him out and delete it?
This function is very anxious, and it is very helpful to the app to lose weight.

Thank you very much and look forward to your reply.

**Comment by tomlokhorst** [comment]
This is not a feature of R.swift.

What you can try to look for is something called a “dead code analyzer”, that should highlight all vars in the R.image struct that are never reference from your source code. Those images you should safely be able to delete (unless you’re accessing them by name, without using R.swift).

I don’t have experience with any source code analyzers for Swift.
