### ISSUE TITLE
no member 'reuseIdentifier'

### ISSUE THREAD

**Issue by huaqixue** [mac-cain13/R.swift#737]
#### Issue

<img width="767" alt="image" src="https://user-images.githubusercontent.com/31527909/149117371-2add766f-c3f1-4eed-8bb6-d0ddde2d23c7.png">

not found the `reuseIdentifier`.

#### Code

<img width="313" alt="image" src="https://user-images.githubusercontent.com/31527909/149117518-5f13acd2-5217-47fd-8c3e-0ec50f829bb9.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/31527909/149117537-cf8f7e39-299a-40a3-b6fe-9cc81ed9d7b4.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/31527909/149117563-2c573c46-7aa3-49d4-8f44-b1b610acaad5.png">

#### Info

Hello , I missed a issue, but I don't know why it happen and how to fix it. So need your help.

As you can see, the issue is the `reuseIdentifier` not generated corrent in the  `R.generated.swift` file

<img width="807" alt="image" src="https://user-images.githubusercontent.com/31527909/149118753-c4cf229e-17c7-42cd-961a-0777f6190f58.png">

<img width="764" alt="image" src="https://user-images.githubusercontent.com/31527909/149119426-3c75aa3e-aa88-4ad7-93b9-bc7350d01632.png">

Already build, delete and regenerated， still not fix.

**Comment by tomlokhorst** [comment]
Have you set the "Identifier" attribute of the nib in the Attribute Inspector?
<img width="268" alt="Screenshot 2022-01-12 at 11 08 39" src="https://user-images.githubusercontent.com/75655/149120445-2dc25a9a-a874-4605-84d5-7658ef0d898c.png">

**Comment by huaqixue** [comment]
@tomlokhorst Yes, thank you !!! I didn't set it.
