### ISSUE TITLE
Error during compilation R.generated.swift

### ISSUE THREAD

**Issue by akonoplev** [mac-cain13/R.swift#740]
Hi, I am getting an error during compilation: 
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/26434897/153145261-42715a0b-6d17-4c77-9e2f-ae35ec5b5125.png">
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/26434897/153145280-f8f03fe5-95c5-497f-81f4-0491ecadcd14.png">

All configurations as in example

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/26434897/153145403-4f4ca0c4-e17b-400c-8cd3-253af3941f73.png">

Does anyone know what is the problem?

I found only one option - set` Build Libraries for Distribution` to  "NO", in build options of build settings
But this option is really bad

**Comment by tomlokhorst** [comment]
The error message doesn’t mention the R.generated.swift file. I don’t think this is related to R.swift.

If you think this is actually an R.swift issue, feel free to respond with more information.
