### ISSUE TITLE
R.generated.swift files  difference between uncheck Copy items if needed and check Copy items if needed？

### ISSUE THREAD

**Issue by kb100824** [mac-cain13/R.swift#746]
I have tried both ways of referencing, and the project can be archived normally. What is the difference between them please? 

![image](https://user-images.githubusercontent.com/8489350/158119025-bd3d955e-d6ae-4ddb-b4a2-033e00931521.png)

![image](https://user-images.githubusercontent.com/8489350/158119083-4630caf8-eb34-4139-88b9-fb85876d3f18.png)

**Comment by tomlokhorst** [comment]
See Apple’s documentation: https://developer.apple.com/documentation/xcode/managing-files-and-folders-in-your-xcode-project
