### ISSUE TITLE
*/Pods/R.swift/rswift: No such file or directory 0.9.0.beta.2 after pod update

### ISSUE THREAD

**Issue by Ewg777** [mac-cain13/R.swift#75]
Xcode 7 beta 6
```bash
 ~:  pod --version
0.39.0.beta.4
 ~:  pod update
...
```
Project Run Script
```bash
"$PODS_ROOT/R.swift/rswift" "$SRCROOT/Project"
```
So file rswift doesn't copy on update

**Comment by mac-cain13** [comment]
That's weird! What version of R.swift are you using?

I'll check if I can reproduce it over here!

**Comment by Ewg777** [comment]
The latest from develop branch 0.9.0.beta.2 
```swift 
pod 'R.swift', :git => 'https://github.com/mac-cain13/R.swift.git', :branch => 'develop'
```

**Comment by mac-cain13** [comment]
Could you try `pod 'R.swift', '~> 0.9.0.beta.2'`?

**Comment by Ewg777** [comment]
Thanks. It works. Seems like a pod bug

**Comment by mac-cain13** [comment]
Yeah, pods for R.swift are a bit of a hack, only tagged versions have the binary. If you just reference a commit there is no zip with a binary available, so that won't work.

**Comment by Ewg777** [comment]
Please add this to README
