### ISSUE TITLE
Could not find module 'Commander' for target 'i386-apple-ios-simulator'.

### ISSUE THREAD

**Issue by Mahmoud-Aziz** [mac-cain13/R.swift#756]
I'm trying to add R.swift to a Package.swift as a dependency but I get this error 

`Could not find module 'Commander' for target 'i386-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/username/Library/Developer/Xcode/DerivedData/PackageName-azhdnwsmgeorxgeyngdkifsjmhvt/Build/Products/Debug-iphonesimulator/Commander.swiftmodule
`

![Screen Shot 2022-08-13 at 2 02 01 AM](https://user-images.githubusercontent.com/69410556/184458360-f2bd3ef7-2153-4df2-a99f-e65cacc016e0.png)

Any ideas on how to solve this?

Thanks,

**Comment by paulosilva8** [comment]
What was the solution for this? Or did it just go away for you? I am having this problem

**Comment by Mahmoud-Aziz** [comment]
> What was the solution for this? Or did it just go away for you? I am having this problem

It just went away, I couldn't figure out what was happening.

**Comment by KirylBelasheuski** [comment]
I have the same problem. XCode 13.4.1, macOS 12.6

**Comment by mbernson** [comment]
Do you perhaps have a binary-only dependency (for example a cocoapod) which is not compatible with the arm64 simulator? That's caused this issue for me in the past.

**Comment by KirylBelasheuski** [comment]
I've used SPM
