### ISSUE TITLE
Feature request: An option to convert snake case to camel case?

### ISSUE THREAD

**Issue by shinichy** [mac-cain13/R.swift#757]
Currently `welcome.with_name` localization key generates `welcomeWith_name` function. That's a weird name. I'd like to introduce an option to generate `welcomeWithName` function instead.

**Comment by tomlokhorst** [comment]
Rswift does not have options to modify the generated code. 
If you require more control over the code that is generated, take a look at https://github.com/SwiftGen/SwiftGen
