### ISSUE TITLE
Does this package increase the binary size of my app?

### ISSUE THREAD

**Issue by satishVekariya** [mac-cain13/R.swift#762]
Does this package increase the binary size of my app?
*I'm not considering generated files in app size calculation

**Comment by tomlokhorst** [comment]
To use R.swift generated code, you need to include the [R.swift.Library](https://github.com/mac-cain13/R.swift.Library) package at runtime. This is a small Swift library with some code.

Importantly, you don't need to include the rswift binary inside your app. The binary code generator is only required during development.

**Comment by satishVekariya** [comment]
I think it would be good to add this in FAQ
