### ISSUE TITLE
⚠️ Mint build error "invalid manifest" 7.0.0-alpha.2

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#764]
If you're using Mint with R.swift and you're getting an error something like:

"Failed to resolve R.swift v7.0.0-alpha.2 with SPM"

This is a pre-release, it's not meant to be used in production.

Change your mint command hardcode the latest stable release:

`mint run mac-cain13/R.swift@v6.1.0 rswift generate`

**Note the `v` in the tag name `v6.1.0`**

**Comment by abin0992** [comment]
We are facing the same issue since since last 2 hours.

**Comment by ykws** [comment]
I has the other error, fixes by this change, thanks.

`No such module 'RswiftResources'`

<img width="918" alt="Screen Shot 2022-11-26 at 19 43 58" src="https://user-images.githubusercontent.com/5770480/204084852-0aea7c67-69fb-47c5-a62b-97194069ce3c.png">

**Comment by tomlokhorst** [comment]
You're using a generated file created by [the pre-release version 7](https://github.com/mac-cain13/R.swift/pull/766)
If you're not actually testing the alpha version, hardcode version `v6.1.0`.

**Comment by ykws** [comment]
Yes, but not intentionally, it's clear by `v6.1.0`, thanks.

**Comment by ykws** [comment]
🎉 Released [v7](https://github.com/mac-cain13/R.swift/releases/tag/7.0.0), [Migration Guide](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md).
