### ISSUE TITLE
Install R.Swift Manually in SwiftUI  Issue

### ISSUE THREAD

**Issue by BakrIOS91** [mac-cain13/R.swift#765]
Dear am Using R.Swift v6.1.0  Manually and I did all steps and I face this issue any idea why its happning

![Screenshot 2022-11-06 at 8 57 13 PM](https://user-images.githubusercontent.com/34647255/200189774-44761e4a-f249-4ef6-af36-066695e61e42.png)

![Screenshot 2022-11-06 at 9 00 04 PM](https://user-images.githubusercontent.com/34647255/200189817-e2449f08-46e3-4526-8a7a-a4a119b71309.png)
3a5ac.png)

![Screenshot 2022-11-06 at 8 56 41 PM](https://user-images.githubusercontent.com/34647255/200189783-b2bc0b45-c349-4faf-ac8b-99c61ff1aa0c.png)

![Screenshot 2022-11-06 at 8 57 01 PM](https://user-images.githubusercontent.com/34647255/200189842-5e9d59da-fe49-4be1-9cf1-db6c2de0ac69.png)

**Comment by tomlokhorst** [comment]
It appears you're downloading the source code zip file, but trying to run it as an executable.
If you extract the executable from the rswift-v6.1.0.zip file, and place that in the same location, it should work.
