### ISSUE TITLE
R.swift 7 and typealias

### ISSUE THREAD

**Issue by VestaCute** [mac-cain13/R.swift#769]
R.Swift 7.0.1

I used to create typealias so I wouldn't have to write R.String every time, but now it doesn't work

Does anyone have a solution to this problem?

<img width="1080" alt="Снимок экрана 2022-11-29 в 18 18 37" src="https://user-images.githubusercontent.com/46375820/204584385-1d1d9d9f-3b20-4e17-9552-7dc03ead7b04.png">

**Comment by tomlokhorst** [comment]
The generated code has changed from version 6 to version 7.

There is no longer an `R` type. Instead there's now an `_R` type, and `R` is an instance of that.

However, you should be able to use value constants to get the same effect:

```
let L10n = R.string.localizable
let Image = R.image 
```

**Comment by tomlokhorst** [comment]
If you have any further issues, feel free to reply.
