### ISSUE TITLE
Can't validate build tool plug-in when running CI/CD

### ISSUE THREAD

**Issue by gitIkerKristian** [mac-cain13/R.swift#774]
I have issue with R.swift 7.0.1 when I try to use SPM on Bitrise, I have no idea how to validate RswfitGenerateInternalResources so my builds keep failing...

Do you guys have some suggestion what to do?

**Comment by tomlokhorst** [comment]
Xcode requires the user the clik “Trust” before running the plugin (you may have seen the UI pop up).

On bitrise, you can pass `-skipPackagePluginValidation` to xcodebuild to skip the validation. Obviously, this is a security risk, but if you check the plugins before uploading to bitrise, it should be fine.

See also this discussion on the Swift forums: https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305

If you use Fastlane; add it to xcargs to build_app:

```
build_app(
  ...
  xcargs: "-skipPackagePluginValidation"
  ...
)
```

**Comment by gitIkerKristian** [comment]
Thank you, this solved my issue.
