### ISSUE TITLE
Xcode Cloud build fails with 'Build input file cannot be found' error

### ISSUE THREAD

**Issue by ffizzik** [mac-cain13/R.swift#776]
I'm using R.swift v 6.0.0
Once I'm trying to run Xcode Cloud build - it fails with `Build input file cannot be found` for my share extension. Here is my script for the main application target: 
<img width="777" alt="Screenshot 2022-12-01 at 17 59 54" src="https://user-images.githubusercontent.com/2472739/205101564-ab95d3de-b1e5-4397-af2c-1477e36af330.png">
I'm getting this error:
<img width="682" alt="Screenshot 2022-12-01 at 18 10 44" src="https://user-images.githubusercontent.com/2472739/205102880-e14def4d-93bb-412e-b62c-63ee3b091211.png">

**Comment by tomlokhorst** [comment]
From the error message it appears your project includes the file `Rext.generated.swift`
But your script shows the name `R.generated.swift`. That won't work.


Look in your project for the file Rext.generated.swift, remove that, and add the correct file.
See: https://github.com/mac-cain13/R.swift/tree/v6.0.0#installation

**Comment by tomlokhorst** [comment]
Closing this issue, but feel free to reply if there's still a problem.

**Comment by ffizzik** [comment]
@tomlokhorst thanks for your help. The issue was not related to the R.Swift
