### ISSUE TITLE
7.x: usage in typealias

### ISSUE THREAD

**Issue by eran247** [mac-cain13/R.swift#778]
Hi, this morning I tried migrating R.Swift to 7.x
In my projects, I mostly use R.swift with the following typaliases:
```
typealias L = R.string.localizable
typealias I = R.image
typealias C = R.color
typealias F = R.font
```

But unfortunately, these are not working anymore, the error is: `Cannot find type 'R' in scope.`
I suspect this is because R.generated file is no longer part of the sources. 

Is there a way around this, maybe by modifying the buildtool? Or will I be forced to find-replace all usages of the type aliases?

**Comment by tomlokhorst** [comment]
In version 7, `R` is no longer a type, but a value instance of type `_R`

You should be able to use variables instead:
```
let L = R.string.localizable
let I = R.image
let C = R.color
let F = R.font
```

**Comment by eran247** [comment]
Wow, that was fast, and way easier than expected.
Thanks Tom!
