### ISSUE TITLE
R.swift v7.0 doesn't support Nib's secondview

### ISSUE THREAD

**Issue by jhpassion0621** [mac-cain13/R.swift#779]
This was my code until v6.1
`R.nib.XXX.secondView(owner: self)`

But I am getting error after upgrading to v7.0, How can I fix this issue?

**Comment by tomlokhorst** [comment]
Thanks for your report.

This is a breaking change introduced in version 7, compared to version 6.
There is currently no longer support for second to twentieth views, only firstView remains.

This should have been noted in the migration guide, I will update that.

The only workaround right now is to manually access the second view:

`let secondView = R.nib.XXX.instantiate(withOwner: nil)[1] as? SecondView`
