### ISSUE TITLE
Invalid LocaleReference .language(en)

### ISSUE THREAD

**Issue by KKirsten** [mac-cain13/R.swift#780]
I updated to Swift 7.2.0 and added Rswift as a Xcode Plugin. Code generation seems to work however the generated code does not compile. 

Xcode complains: `Cannot find 'en' in scope` in the following line:

`var appIntentVocabularyPlist: RswiftResources.FileResource { .init(name: "AppIntentVocabulary", pathExtension: "plist", bundle: bundle, locale: .language(en)) }`

It seems like `.language(en)` should be `.language("en")` instead.

My guess is that LocaleReference+Generator.swift line 18 should be:
`return ".language(\"\(string)\")"` instead of `return ".language(\(string))"`

AppIntentVocabulary is a localized file without a Base Localization. Adding Base Localization to the file does not fix the issue for me since the generated code still contains `.language(en)` instead of `.base`

**Comment by tomlokhorst** [comment]
Thanks for the report, and for finding the exact location in the code that's the problem!

I've fixed this in the 7.2.1 release.

**Comment by KKirsten** [comment]
Thanks for the quick fix. Works now fine.
