### ISSUE TITLE
languageCode deprecation in iOS 16

### ISSUE THREAD

**Issue by SAleksiev** [mac-cain13/R.swift#785]
Since I updated the min. deployment target to iOS 16, it looks like the compiler warns me that the language code is now changed to language.languageCode.identifier.

Do you plan to include this new change in some of your next releases?

**Comment by tomlokhorst** [comment]
Hmm... I understand the warning, but I can't seem to reproduce it.

How do you include the library in your app so that you see this warning?

**Comment by tomlokhorst** [comment]
I've been able to reproduce the warning by using CocoaPods instead of SPM.

This issue will be fixed in the next version.

**Comment by tomlokhorst** [comment]
Fixed in 7.2.4
