### ISSUE TITLE
Mac Catalyst support broken in 7.x

### ISSUE THREAD

**Issue by kiritokatklian** [mac-cain13/R.swift#786]
After updating to 7.2.3 from 6.1.0, R.swift is giving errors when building with a Mac Catalyst target. Adding `&& !targetEnvironment(macCatalyst)` to line 87 seems to fix the issue.

<img width="1492" alt="Screen Shot 2022-12-11 at 02 45 02" src="https://user-images.githubusercontent.com/6556281/206882663-0ca7b69d-fa0c-4536-adb7-7c62a03614f1.png">

**Comment by tomlokhorst** [comment]
Thanks for reporting this, as well as for the solution!

This will be fixed in the next version.

**Comment by tomlokhorst** [comment]
Fixed in 7.2.4
