### ISSUE TITLE
It is not import AppKit in macOS App project

### ISSUE THREAD

**Issue by Mx-Iris** [mac-cain13/R.swift#788]
![CleanShot 2022-12-11 at 18 14 51@2x](https://user-images.githubusercontent.com/61279231/206897934-faf50c8b-f7c1-4a52-98b2-d9a0ef077bb8.png)

**Comment by tomlokhorst** [comment]
Thanks for the report!

This will be fixed in the next version.

**Comment by tomlokhorst** [comment]
Fixed in 7.2.4
