### ISSUE TITLE
No such module 'RswiftResources' error in R.generated

### ISSUE THREAD

**Issue by andre-ripple** [mac-cain13/R.swift#794]
The error appears after the Xcode generate the file **R.generated** 

I'm using Xcode 14.1

What I already tried:
- delete derivate data
- use Xcode 14.2
- reset package caches
- update to latest package versions

<img src="https://user-images.githubusercontent.com/119427762/208898808-c02f5163-55d7-48a7-bc92-df2606b8a781.png" width="800" />

**Comment by tomlokhorst** [comment]
Did you add the RswiftLibrary framework to your target?

> Select your target, on the tab "General", in the section "Frameworks, Libraries, and Embeded Content", click "+" and add RswiftLibrary

**Comment by andre-ripple** [comment]
Ok...
Actually the project is using a fork of R.swift, [that fork](https://github.com/apptekstudios/R.swift.Library) (from [that thread](https://github.com/mac-cain13/R.swift/issues/600)) was being used because it supports SwiftUI.
My theory: as we are installing Rswift with brew, and now the version installed by brew (7.2.4) is not compatible with the fork.
Do you think that it's possible that scenario?
If so, could you enable installing the version 6.0.0 by homebrew? I don't now if it's possible, but if so that would be perfect because the team can continue working in the new features and plaining the migration to the original Rswift package.
Sth like 'brew install rswift@6.0.0' ...

**Comment by tomlokhorst** [comment]
Right, you can't use the version 6 library with version 7 executable.
The new R.swift 7 has support for SwiftUI.

If you want to continue using R.swift 6, you'll need to install the excutable via homebrew. I'm not sure how that works exactly, but from some quick searching online, it appears to be possible. 

You can also use one of the [other installation methods](https://github.com/mac-cain13/R.swift/tree/v6.1.0#installation) or download the [release directly](https://github.com/mac-cain13/R.swift/releases/tag/v6.0.0).

**Comment by andre-ripple** [comment]
Sure, there is a manually methods described there, thanks!!
After using the version 6.0.0, by the manually method, I could validate that the problem was with the conflict between the fork and the current Rswift version.
Thanks Tom!
