### ISSUE TITLE
Protocols do not allow generic parameters; use associated types instead

### ISSUE THREAD

**Issue by absolutvodka8888** [mac-cain13/R.swift#795]
public protocol ReuseIdentifierContainer<Reusable> {
    associatedtype Reusable
    var identifier: String { get }
}

**Comment by tomlokhorst** [comment]
R.swift 7 requires the latest Swift version that ships with Xcode 14.

If you're using an older version, you can continue to use version 6: https://github.com/mac-cain13/R.swift/tree/v6.1.0

**Comment by absolutvodka8888** [comment]
Problem solved using R.Swift version 6.0.0
