### ISSUE TITLE
Can I change file position of R.generated.swift with SPM integration?

### ISSUE THREAD

**Issue by shnmxvi** [mac-cain13/R.swift#797]
Hi, Can I change file position of R.generated.swift with SPM integration? (integration In project settings)

**Comment by tomlokhorst** [comment]
When using the build tool plugins `RswiftGenerateInternalResources` or `RswiftGeneratePublicResources` the generated file will always be placed in DerivedData.

When using the manual command plugin `RswiftGenerateResourcesCommand`, you can provided the location of the generated file manually.
