### ISSUE TITLE
Github actions CI is broken after migrating to 7.x

### ISSUE THREAD

**Issue by abin0992** [mac-cain13/R.swift#798]
Env:
macOS Monterey 12.6 
Github Actions Virtual machine
Xcode 14.2 
R.swift 7.2.4 (SPM install)

The error log is as follows
```
sandbox-exec: execvp() of '//Users/runner/Library/Developer/Xcode/DerivedData/RSwiftCI-ebevhdqipdqdlhcxuuhqrvdkfehb/Build/Products/Debug/rswift' failed: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
I was using version 6.x in the project before and it was installed using `mint`, everything was working as expected in CI also. Today I migrated to version 7.4.2 using SPM, the project builds locally but fails on CI. 

I have created a public repository to reproduce the issue and share logs
Link to the above CI run - https://github.com/abin0992/RSwiftCI/actions/runs/3848557429/jobs/6556494563 

[Xcode build command is ](https://github.com/abin0992/RSwiftCI/blob/2f9cc460ba06bd119f62f67c0f13da59a00aa656/.github/workflows/verify-build.yml#L25)
`xcodebuild -project 'RSwiftCI.xcodeproj' -scheme 'RSwiftCI' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro' -UseNewBuildSystem=YES -skipPackagePluginValidation`

Everything works as expected when I build locally using the same command.

 Kindly let me know if I am missing something in Xcode build command or configuring CI environment.

**Comment by idan-tap** [comment]
I am facing the same issue. I migrated from Cocoapods to SPM as recommended.

it appears that for me the Embed Pods script is failing:

`The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/macminim1/Library/Developer/Xcode/DerivedData/{APP_NAME}-ennntifcuypymngtklvrruaeiksc/Build/Intermediates.noindex/ArchiveIntermediates/{APP_NAME}/IntermediateBuildFilesPath/{APP_NAME}.build/Release-iphoneos/{APP_NAME}.build/Script-025E446398AAA17385604178.sh (in target '{APP_NAME}' from project '{APP_NAME}')`

**Comment by tomlokhorst** [comment]
I haven't had time to look into this in detail, but taking a quick look at the RswiftCI sample project:

When run locally (with empty DerivedData) this fails for me as well, with the same error.
Removing the flag `-sdk iphonesimulator` makes it build correctly locally.

The final executable is still build for iPhone, presumably because of the specified destination.

**Comment by abin0992** [comment]
Thanks @tomlokhorst for the response. Removing the flag `-sdk iphonesimulator` makes it build correctly in CI virtual machine.

**Comment by nharbo** [comment]
That's just not really a solution. I'm in a situation where I need to run my project locally to run some automated UI test, meaning I need the simulator to be triggered. So I need the `-sdk iphonesimulator` parameter.
