### ISSUE TITLE
RSwift 7.2.4 not showing errors

### ISSUE THREAD

**Issue by Faktorealchik** [mac-cain13/R.swift#799]
After I upgraded RSwift from 6 to 7 version, sometimes after compiling code I've got "build failure", but there are no errors. While it was on Rswift 6, everything was okay. 
I didn't upgrade any other libraries, so the issue is here, for sure. 
I am using SPM

After cleaning project and rebuilding it again shows errors. But sometime later the same things repeats. It causes a lot of rebuilding project

Do anyone else faced this issue? Did anyone solve it?

**Comment by Faktorealchik** [comment]
???????

**Comment by Faktorealchik** [comment]
@tomlokhorst do you know why???/

**Comment by tomlokhorst** [comment]
I’ve seen the same behavior on other projects that don’t include Rswift. I think this is an Xcode bug. On 15 Jan 2023, at 07:40, Aleksandr Nesterov ***@***.***> wrote:﻿
@tomlokhorst do you know why???/

**Comment by Faktorealchik** [comment]
> I’ve seen the same behavior on other projects that don’t include Rswift. I think this is an Xcode bug.

It didn't happen for me before I upgraded from R 5.0 

I downgrade from 7 to 5, and there is no issue like that, so from my perspective its because of R 
I tried it on 3 different projects, which was working as expected before

**Comment by tomlokhorst** [comment]
How are you integrating R.swift 7? Using SPM or CocoaPods or manually?

I'm having the same issues with other SPM packages, maybe that's the commonality.

**Comment by Faktorealchik** [comment]
yes, it is SPM

**Comment by tomlokhorst** [comment]
Yes, a reproducible example in an empty project would be very useful!

**Comment by tylerjames** [comment]
I've been having this happen lately with Xcode too but I don't know that R.swift is to blame.

Sometimes when this happens you can go to the Report Navigator which is the last tab in the left panel in Xcode. If you click there you can see a list of the most recent builds and clicking on the most recent one with errors should show you what the errors were.

**Comment by Faktorealchik** [comment]
Hey guys, 

It's been a while, but I still have the same issue
But right now its 'internal inconsistency error'
I fixed it by migrating from Plugin to manual install, so its 100% for me was R.swift, by the way its same issue for guys who are using Swiftgen with plugin. Its a plugin failture
