### ISSUE TITLE
No watchOS in CocoaPods

### ISSUE THREAD

**Issue by Knochenmann** [mac-cain13/R.swift#800]
Dear Developers,

recently I encountered a problem with the updating framework via CocoaPods from v6.1.0 to v7.2.4 because of the error in Terminal: 

[!] The platform of the target `MyTarget` (watchOS 7) is not compatible with `R.swift (7.2.4)`, which does not support `watchOS`.

In this target (dynamic library) I have only WatchOS as a supported destination.
Any solution? I can't find any problem on my side...

**Comment by tomlokhorst** [comment]
R.swift indeed doesn't support watchOS on CocoaPods.

Whenever I try to add it to the podspec, I run into a validation error when trying to push to trunk.
This appears to be similar to [this issue](https://github.com/CocoaPods/CocoaPods/issues/8283), but I don't have any tests in the podspec. 

If there's anyone who knows how to workaround this CocoaPods error, I'd love to know!

See detailed error message below:

```
[!] Found podspec `R.swift.podspec`
Adding spec repo `trunk` with CDN `[https://cdn.cocoapods.org/`](https://cdn.cocoapods.org/%60)
Updating spec repo `trunk`
Validating podspec
 -> R.swift
 -> R.swift (7.2.5)
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | xcodebuild:  note: Building targets in dependency order
    - NOTE  | xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'R.swift' from project 'Pods')
    - NOTE  | xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'App' from project 'App')
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - ERROR | [watchOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [watchOS] xcodebuild:  xcodebuild: error: Unable to find a destination matching the provided destination specifier:

[!] The spec did not pass validation, due to 1 error.
Error: Process completed with exit code 1.
```

**Comment by tomlokhorst** [comment]
CocoaPods have fixed the bug. 

R.swift now supports watchOS again, as of 7.3.0
