### ISSUE TITLE
Conflict between Cocoapods and SPM plugins

### ISSUE THREAD

**Issue by paulosilva8** [mac-cain13/R.swift#802]
We are migrating from Cocoapods to SPM and right now we are facing a blocker after migrating RSwift to SPM. Cocoapods is still needed for some deprecated libraries that we are studying how to get rid of but ```pod install``` will conflict and complain about the RSwiftGenerateInternalResources plugins.
The error is very clear when running ```pod install```:

`### Error
RuntimeError - Expected target or target_proxy, from which to fetch a uuid for target ''.Find and clear the PBXTargetDependency entry with uuid '2C2C601C297FF71A00CB600B' in your .xcodeproj.
`
This entry belongs to the plugin phase of one of our app targets. Any ideas on how to make cocoapods skip this analysis and move on with the installation of pods? Is anyone facing this same issue?

**Comment by paulosilva8** [comment]
For those who may run into this issue, you need to update the xcodeproj gem to the latest version (1.22.0)

**Comment by Ded77** [comment]
It fix my issue, thank you @paulosilva8!
