### ISSUE TITLE
Modularized app. Can I use R.swift in a package?

### ISSUE THREAD

**Issue by f-gonzalez** [mac-cain13/R.swift#808]
I want to modularize an app into several modules (like networking, shared ui components, resources, etc). 
If  I create a package with my Assets catalog and localized file, will R work in that package ? what it would take for it to work?
Thanks!

**Comment by baveku** [comment]
Yes, you can. I create a Package File Container to share all Assets to all SubPackages, It works perfectly

**Comment by tomlokhorst** [comment]
In general, yes this is possible to use Rswift across multiple targets of packages.

If you have some specific use case that is not working, please create a separate issues for that.
