### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by carlossless** [mac-cain13/R.swift#81]
Currently the generated `R.Swift` has a struct that implements `Printable`:
```swift
struct ReuseIdentifier<T>: Printable {
  let identifier: String
  
  var description: String { return identifier }
}
```

`Printable` has been replaced with `CustomStringConvertible` with the introduction of Swift 2. Perhaps we could have a argument to pass a version of swift to generate the file for?

**Comment by carlossless** [comment]
Nevermind. I already noticed that this is supported. Sorry!

**Comment by mac-cain13** [comment]
No problem! Thanks for using R.swift. :)
