### ISSUE TITLE
Cannot gitignore R.generated.swift

### ISSUE THREAD

**Issue by sdiik** [mac-cain13/R.swift#810]
I cannot ignore `R.generated.swift`, location R.generated.swift in `Name Project/Resources/R.generated.swift`
and I finished add *.generated.swift in .gitignore

when I git status :
`modified:   Name Project/Resources/R.generated.swift`

please help me 🙏🏼

**Comment by tomlokhorst** [comment]
If you see the file as modified in git, it means it is already being tracked by git.

First remove the file from git, then commit. Afterwards the ignored file shouldn't show up anymore.
