### ISSUE TITLE
Localised strings with arguments are improperly formatted due to missing locale

### ISSUE THREAD

**Issue by glaurent** [mac-cain13/R.swift#812]
It seems in version 7.2.4, strings like "this is an integer %d" will no longer be formatted properly because String(format:) is passed a nil locale. The fix is that at this line

https://github.com/mac-cain13/R.swift/blob/62a6b011b2f8f986f3c4665d801739849e814bae/Sources/RswiftResources/Integrations/StringResource%2BIntegrations.swift#L17

you should have

`self = String(format: format, locale: overrideLocale ?? Locale.current, arguments: arguments)`

**Comment by tomlokhorst** [comment]
I see that this is indeed the case.

I'll have to investigate this further to see if this is a new issue that started with the 7.0 refactor, or if this has always been the way R.swift behaves.

**Comment by glaurent** [comment]
It's not there in 6.x (I discovered it when upgrading from 6.x to current version).

**Comment by paul-lavoine** [comment]
Any news on that topic ?

**Comment by nicolasgoutaland** [comment]
Any update on that @tomlokhorst ? Is it a confirmed issue ?

**Comment by tomlokhorst** [comment]
This is fixed in 7.4.0
