### ISSUE TITLE
RswiftModifyXcodePackages doesn't change anything

### ISSUE THREAD

**Issue by jhpassion0621** [mac-cain13/R.swift#813]
My xCode is 14.2 and I added R.swift 7.2.4. I added RswiftGenerateInternalResources and ran RswiftModifyXcodePackage. My expected was to show "Allow Change Package" dialog as your youtube video but I couldn't see anything. What was issue?

**Comment by tomlokhorst** [comment]
Can you explain a bit more?

Is there an issue with running R.swift?
Are you able to access the generated R resources?

**Comment by jhpassion0621** [comment]
As following your tutorial video, once execute RswiftModifyXcodePackage command, plugin icon should be changed which means plugin added correctly. But it doesn't on my xCode. I tried on several projects and I got same result.
![Uploading Screenshot 2023-03-06 at 9.53.27 AM.png…]()

**Comment by tomlokhorst** [comment]
That's really strange. Are you sure your project or correct target is selected when running RswiftModifyXcodePackage?

As a workaround, you can manually edit the project.pbxproj file to do the thing the command would have done.

Find the lines that look like this:
```
E25F907729B69449002F57B6 /* RswiftGenerateInternalResources */ = {
    isa = XCSwiftPackageProductDependency;
    package = E2054F48298BC4C300347AE8 /* XCRemoteSwiftPackageReference "R" */;
    productName = "plugin:RswiftGenerateInternalResources";
};
```
And remove the package line. After the package line has been removed and the file is saved, the icon should change in Xcode and the Plugin should run when building.

<img width="641" alt="CleanShot 2023-03-06 at 22 37 51@2x" src="https://user-images.githubusercontent.com/75655/223237631-84a21fce-cf11-4d55-a795-bab9570a4a5c.png">

**Comment by jhpassion0621** [comment]
@tomlokhorst Thanks for your workaround. It works for me. And about RswiftModifyXcodePackage running, yes I selected correct target. The problem is when I select a target, I can't see commit change dialog like your tutorial.

**Comment by N0t2Day** [comment]
Hey. I also have problem but a little different. I tried solution above and this didn't work for me.
<img width="257" alt="Screenshot 2023-04-11 at 00 21 15" src="https://user-images.githubusercontent.com/23290834/231001317-ed44f784-ca13-4a7e-8fa6-6712f1c6300a.png">
<img width="580" alt="Screenshot 2023-04-11 at 00 21 27" src="https://user-images.githubusercontent.com/23290834/231001355-2c52dbd2-9d48-46a1-8708-ffb72e7cc246.png">

**Comment by EricAtomic** [comment]
#813 didn't work for me. The generator looks validated but I still got `Cannot find 'R' in scope` errors everywhere.
![image](https://user-images.githubusercontent.com/89362858/231303373-21a6ee49-c09d-42c4-8ec7-67d2a139025d.png)
![image](https://user-images.githubusercontent.com/89362858/231303441-8749b87e-67cd-4ec9-8c91-77f33f151e3c.png)

**Comment by jhpassion0621** [comment]
@EricAtomic I think it's compiler error. Even though I can see above error on my xCode, I can build my app successfully.
