### ISSUE TITLE
Increases App Clip size by 1Mb in Xcode 14

### ISSUE THREAD

**Issue by abe-union** [mac-cain13/R.swift#814]
Unfortunately Apple only provides 10 Mb of uncompressed size for the App clip if its not set to iOS 16. When updating the library to upgrade to Xcode 14, the app clip sizes jump up by 1Mb.

**Comment by mac-cain13** [comment]
This isn't something we will focus on right now. If you figure out what gives the biggest increase in size and have concrete pointers to fixes we might be able to improve this. But we won't spend time on measuring this ourselves right now.
