### ISSUE TITLE
.rswiftignore does not work correctly with Swift Package

### ISSUE THREAD

**Issue by manicmaniac** [mac-cain13/R.swift#819]
R.swift cannot find .rswiftignore for a project that isn't made by xcodeproj but Package.swift.

It is because that `SOURCE_ROOT` environment variable doesn't exist when a project is build with Package.swift and currently the source code references `./SOURCE_ROOT` literally.

https://github.com/mac-cain13/R.swift/blob/7.3.0/Sources/rswift/App.swift#L91

**Comment by tomlokhorst** [comment]
Thanks for the PR, this will be released in the next version.
