### ISSUE TITLE
[iOS 9] Add support for ApplicationShortcuts

### ISSUE THREAD

**Issue by bre7** [mac-cain13/R.swift#82]
Static shortcut items must be defined in Info.plist with the following keys under the **UIApplicationShortcutItems** array:

| Key | Description |
| --- | --- |
| `UIApplicationShortcutItemType` (required) | A required string delivered to your app when the user invokes the corresponding quick action. Your app can use this string to classify quick actions into types, and then to disambiguate among action types it receives. You don’t need to register your quick action types. |
| UIApplicationShortcutItemTitle (required) | A string displayed to the user on the Home screen as the name of the quick action. If the title fits on one line, the system displays it as a single line quick action item. If the title is too long for one line and you have not specified a UIApplicationShortcutItemSubtitle string, the system displays the title on two lines. You can, optionally, internationalize a quick action title by employing your app’s InfoPlist.strings file. For guidance on how to do this, read Localizing Property List Values. |
| UIApplicationShortcutItemSubtitle | An optional string that is displayed to the user on the Home screen, immediately below the corresponding title string. If you specify a subtitle for a quick action, the system displays the quick action title on a single line (perhaps just a portion of the title, followed by ellipsis character), no matter how long the title is. You can, optionally, internationalize a quick action subtitle by employing your app’s InfoPlist.strings file. For guidance on how to do this, read Localizing Property List Values. |
| UIApplicationShortcutItemIconType | An optional string specifying the type of an icon from the system-provided library; see the UIApplicationShortcutIconType enumeration in UIApplicationShortcutIcon Class Reference. The icon is displayed in the set of quick actions for your app, along with the quick action's title, on the Home screen. |
| UIApplicationShortcutItemIconFile | An optional string specifying an icon image to use from the app’s bundle, or the name of an image in an asset catalog. The icon is displayed before quick action title on the Home screen. Icons should be square, single color, and 35x35 points, as shown in these template files and as described in iOS Human Interface Guidelines. **If you specify this key, the system ignores the `UIApplicationShortcutItemIconType` key.** |
| UIApplicationShortcutItemUserInfo | An optional, app-defined dictionary. One use for this dictionary is to provide app version information, as described in the “App Launch and App Update Considerations for Quick Actions” section of the overview in UIApplicationShortcutItem Class Reference. |

More info:
- [Example](http://www.stringcode.co.uk/add-ios-9s-quick-actions-shortcut-support-in-15-minutes-right-now/)
- [Documentation](https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/3DTouchAPIs.html#//apple_ref/doc/uid/TP40016543-CH4-SW1) (Under **Home Screen Quick Actions**)

**Comment by mac-cain13** [comment]
This is absolutely something we should support! It's on the list. :)

I propose:
- Create `R.applicationShortcut.nameOfShortcut` which should basically be the `UIApplicationShortcutItemType` that you can compare against the given string when the shortcut is used
- If the `UIApplicationShortcutItemUserInfo` is defined in the plist we could type this too, for example by using something like `R.applicationShortcut.nameOfShortcut.userInfo.nameOfKey`, should give this a bit more thought but I think that could be nice.
- Optionally: we could make it a struct (that you still can compare with a string) that contains the extra information like titles and icons. 

The last point could be useful in some cases, but I consider it a bonus.

**Comment by tomlokhorst** [comment]
This is superseded by the more generic issue #414
