### ISSUE TITLE
Build with xcodebuild fails

### ISSUE THREAD

**Issue by crash481** [mac-cain13/R.swift#825]
Trying to build with xcodebuild, but there is error 
```
sandbox-exec: execvp() of '//var/root/Library/Developer/Xcode/DerivedData/ProjectName-dtxgzeditjjpxresibwuhlxcqlly/Build/Products/Debug/rswift' failed: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

Path above not exists, like there is no folder /var/root/Library/Developer/
How can we fix it?

**Comment by MasterCna** [comment]
I've faced the same problem, couldn't fix it in anyway!

**Comment by mhdbitar-bit** [comment]
I have same problem.

**Comment by JRJian** [comment]
I've faced the same problem

**Comment by JRJian** [comment]
In Project APPNAME/ios/App/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh 
replaced source="$(readlink "${source}")" 
with 
source="$(readlink -f "${source}")"
