### ISSUE TITLE
Ability to set PreferredLanguages globally

### ISSUE THREAD

**Issue by crash481** [mac-cain13/R.swift#826]
There is many Issues created before and closed and resolved with R.swift 7.0 update

But I still do not see method how to set it globally without to write in every line of code "R.string(preferredLanguages: ....) "
It is better to set it on one place

Can you please show how to do it, and in all places I can use R.string.localizable.myString() without setting preferredLanguages in every place

**Comment by liamnichols** [comment]
You can't change the existing `R.string` but you could just declare a new computed property to make things more convenient for yourself:

```swift
extension _R {
  var english: string { .string(preferredLanguages: ["en"]) } 
}
```

Usage:

```swift
R.english.localizable.myString()
```
