### ISSUE TITLE
Can't run SwiftUI preview when have Rswift in UIKit project

### ISSUE THREAD

**Issue by anhlq-supp** [mac-cain13/R.swift#831]
I have UIKit project using Rswift through SPM. When we try to migrate some UI components to SwiftUI, Xcode can't show the preview. Does anyone have a workaround or idea about this?
- Xcode 14.2
- Rswift 7.3.2
- Here the log when I run diagnostics:
```SchemeBuildError: Failed to build the scheme "MyPorject"

cannot find 'R' in scope
    button.setImage(UIImage(named: R.image.iconChevron.name), for: .normal) ...
    ```

**Comment by cdescours-amaris** [comment]
That would be useful :)

**Comment by oleksandryolkin** [comment]
Have you found a solution for this issue?

**Comment by oleksandryolkin** [comment]
I had the same issue using SPM. Added R.swift manually and all works

**Comment by anhlq-supp** [comment]
> I had the same issue using SPM. Added R.swift manually and all works

How can you manually add the R.swift file?

**Comment by oleksandryolkin** [comment]
> > I had the same issue using SPM. Added R.swift manually and all works
> 
> How can you manually add the R.swift file?

https://github.com/mac-cain13/R.swift#manually

**Comment by anhlq-ios** [comment]
@oleksandryolkin I got this error when manually add the library. Any idea?
`R.generated.swift:7:8: No such module 'RswiftResources'`

**Comment by anhlq-supp** [comment]
Manually add library and follow migration guide [here](https://github.com/mac-cain13/R.swift/blob/main/Documentation/Migration.md) solve my problem
