### ISSUE TITLE
ColorResource conflicts with new API in Xcode 15

### ISSUE THREAD

**Issue by arkichek** [mac-cain13/R.swift#832]
I can't build a project due to duplicate symbols caused by the new API https://developer.apple.com/documentation/developertoolssupport/colorresource

**Comment by tomlokhorst** [comment]
The generated code in R.swift always uses fully qualified names and should always use the prefix “RswiftResources”. 

In my own project I only had a single error where I had in my code:
`let myImage: ImageResource = R.image.myImage`

Changing it to this, fixed my issue:
`let myImage: RswiftResources.ImageResource = R.image.myImage`

What code are you seeing that is causing an error?

**Comment by arkichek** [comment]
It was an attempt to build with an old library version
