### ISSUE TITLE
How to integrate R.swift in private libraries?

### ISSUE THREAD

**Issue by RisingSSR** [mac-cain13/R.swift#833]
## pod lib create

when I create a private libraries, I need to use the R.swift framework for some views.

## *.podspec

```ruby
Pod::Spec.new do |s|
  # ... simple things
  s.subspec 'Views' do |views|
      views.source_files = '*.swift'
      views.resources = "*.xcassets"
      views.dependency 'R.swift'
  end
```

> To reduce coupling, I used .subspec

## add Run Script

Because there will be two projects in the private library, the second project is called Pod.

Pod -> [My Target] -> Build Phases

1. New Run Script Phase
2. "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/../SomeFile/Classes/R.generated.swift"
3. add Output Files

## What's the question?

How to integrate R.swift in private libraries?

Cause I have Error:

```
error: Build input file cannot be found: '/Users/usr/Documents/SomeFile/Classes/R.generated.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'Pods-SomeFile_Example' from project 'Pods')
```

**Comment by jinaiyuanbaojie** [comment]
https://github.com/mac-cain13/R.swift/issues/713

take a look
