### ISSUE TITLE
Bad CPU type in executable when build on xcode 15 beta

### ISSUE THREAD

**Issue by smashkins** [mac-cain13/R.swift#834]
While building a project with Xcode 15 beta on MacOS Sonoma Apple Silicon that includes the R.swift pod and the script
```sh
#!/bin/sh
"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/iMamma/Common/Resources/Generated/Production/R.generated.swift" --generators image,string,file,color,font,storyboard,nib
```
the compiler returns the following warning. What might be the reason for this?

> Bad CPU type in executable

**Comment by alessiolapenna** [comment]
I second this.

**Comment by kuldar-daniel** [comment]
I had the same issue. It turned out that the version of the dependency used was too old and only supported x86_64 architecture for the rswift binary and therefore it would fail to run on Apple Silicon Macs.
