### ISSUE TITLE
Why R.swift states that it supports OS X when it actually just generates [Color | Image | etc.] resources?

### ISSUE THREAD

**Issue by ostaptyv** [mac-cain13/R.swift#835]

**Comment by tomlokhorst** [comment]
Because those are types that exist on macOS.

If you have a specific feature request for additional integrations, please create a specific issue, or a PR.

**Comment by ostaptyv** [comment]
Sorry for not writing a detailed issue — I should've expanded on the topic, really. What I was trying to say is that on macOS you don't have these neat methods which the codegen makes on iOS. I have to write my own extension on `ColorResource`, for example, to be able to use the R.swift as on iOS
Here I've attached a sample project which demonstrates the issue. The code is in `ViewController.swift`:

[TestRSwiftCodegen.zip](https://github.com/mac-cain13/R.swift/files/12388274/TestRSwiftCodegen.zip)
