### ISSUE TITLE
Compatibility with and/or exclusion from SwiftLint rules

### ISSUE THREAD

**Issue by deemoney-rupendra** [mac-cain13/R.swift#836]
I have few SwiftLint rules defined in my project which conflicts with RSwift generated variables.
I used `.swiftlint.yml` to exclude `R.generated.swift` before, but now it seems `R.generated.swift` is not generated in Rswift 7.0 (Ref: https://github.com/mac-cain13/R.swift/blob/main/Documentation/Migration.md).
My query is, how can I exclude RSwift related definitions and variables from SwiftLint for Rswift 7.*?

**Comment by mac-cain13** [comment]
R.generated.swift now only exists in the derived data folder, just like Apples generated code. So I think SwiftLint will ignore this by default!
