### ISSUE TITLE
It is possible only run specific generators for SPM Package?

### ISSUE THREAD

**Issue by ViacheslavGerasimenok** [mac-cain13/R.swift#844]

**Comment by bingosoft** [comment]
+1, have faced with the compilation problem of unneeded `uiApplicationShortcutItems`, want to disable this generators somehow in `.rswiftignore` but have no idea how. Previously in build phase we could explicitly say which generators we want to use

**Comment by mac-cain13** [comment]
It's currently not, we're tracking this feature request in #860.
