### ISSUE TITLE
Doesn't render fonts in R.generated file

### ISSUE THREAD

**Issue by Rylaa** [mac-cain13/R.swift#845]
I have defined the fonts in info.plist but it doesn't add them to r.generated.

**Comment by mac-cain13** [comment]
Do the fonts work when you try to use them without R.swift, but with the standard Apple provided APIs?

**Comment by Rylaa** [comment]
yes it works fine

**Comment by mac-cain13** [comment]
That is interesting. Could you provide a bit more information about the setup; 

- What is the code to use the font without R.swift that does work? 
- What font file do you use? What is the specific font?
- Is it included in the target or not?
- Do other items for the same target show up in the generated file?

**Comment by synecdochenoire** [comment]
I have the same problem.
1. `static let jetBrainsBold = UIFont(name: "JetBrainsMono-Bold", size: 26)`
2. JetBrainsMono-Bold.ttf downloaded from Google Fonts
3. It is included in the target and added to Info.plist
4. Yes, there was no problem with adding strings, colors and images
