### ISSUE TITLE
Issue when trying to install the library

### ISSUE THREAD

**Issue by kiddden** [mac-cain13/R.swift#847]
Hello!

Trying to install the library by following the installation guide in the README, there it states:
> Right-click on your project, click RswiftModifyXcodePackages, click Run, click Allow Command to Change Files.

However, when clicking on the project, there is no such option as RswiftModifyXcodePackages(find the screenshot below).

Please advise, how to proceed with the installation.

Xcode version 14.3
![](https://i.imgur.com/J2pkdi0.png)

**Comment by olegbraginontarget** [comment]
I see the same too. Had to download Xcode 15 beta to see that menu item. But it still doesn't help. I'm still not able to build the project.

**Comment by tomlokhorst** [comment]
This is a bug in Xcode 14.3, it has been fixed in 14.3.1.

See: https://github.com/mac-cain13/R.swift/issues/822
