### ISSUE TITLE
Cannot find 'R' in scope in test

### ISSUE THREAD

**Issue by codercoderme** [mac-cain13/R.swift#849]
<img width="1101" alt="Screenshot 2023-09-09 at 3 26 44 PM" src="https://github.com/mac-cain13/R.swift/assets/29246210/a5c556b4-4d85-4ff6-8701-6c5e9c254953">

**Comment by tomlokhorst** [comment]
Can you elaborate on your setup?
Which Xcode version? Which project are you trying to build? Are you using the latest R.swift version?

I can run ResourceAppTests from ResourceApp.xcworkspace with no issues (after bumping the minimum iOS version to 12).

**Comment by ykws** [comment]
me too in my project Tests. (not yet try to run ResourceAppTests.)
However Build and Test Succeeded.
Remain a highlight red message "Cannot find 'R' in scope" on Xcode.

- R.swift 7.5.0
- Xcode 15.2

**Comment by ykws** [comment]
The another my project fixed, not reproduce...has no error messages.

@codercoderme Does the issue still reproduce on your end?
