### ISSUE TITLE
[Xcode 15] Accessing protocol public variables leads to 'fileprivate' protection level error in extensions

### ISSUE THREAD

**Issue by maximebianchi** [mac-cain13/R.swift#851]
XCode version: 15_RC
Rswift Version: 6 using pod / 7 using SPM

Subject:
Extension of ImageResource no more compiling with error: 'fileprivate' protection level while struct implements a public protocol.

![Capture d’écran 2023-09-14 à 10 21 38](https://github.com/mac-cain13/R.swift/assets/24541867/1f1bb4e6-857f-491e-af2b-c4471ae0fb58)

**Comment by tomlokhorst** [comment]
This is conflicting with the new ImageResource type generated by Xcode 15.

If you change your code to explicitly refer to Rswift, it could work correctly.

Something like this:
```swift
import RswiftResources

extension RswiftResources.ImageResource {
  // …
}
```

**Comment by dev-pac** [comment]
Ho, thanks, I didn't know about this new feature of xcode 15
