### ISSUE TITLE
Add 7.5.0 to CocoaPods

### ISSUE THREAD

**Issue by erikmartens** [mac-cain13/R.swift#853]
Hi, the CocoaPods Spec still references version `7.3.2`. Is there a reason why the latest release was not manifested via an updated Pod Spec?

**Comment by mushyoom** [comment]
@mac-cain13  @tomlokhorst 
Hi, I was wondering if there are any plans to add version 7.4.0 or newer of your library to CocoaPods ?
We are currently encountering a bug in our application that requires an upgrade to version 7.4.0 or later to be resolved.
(Our application relies on CocoaPods for integrating libraries.)

Could you please let us know if there is a timeline for this update? Any information or assistance you could provide would be greatly appreciated:)

**Comment by mac-cain13** [comment]
Deployment to Cocoapods indeed gave some errors releasing the latest versions. If you can switch to SPM, please do, but we will look into deploying to Cocoapods also.

**Comment by tomlokhorst** [comment]
7.6.0 has been released to CocoaPods
