### ISSUE TITLE
When I tried to achieve, I encountered this error. "not loaded: @rpath/RswiftResources.framework/Versions/A/RswiftResources"

### ISSUE THREAD

**Issue by Rylaa** [mac-cain13/R.swift#856]
xcode version: Xcode 15

Rswift
<img width="855" alt="Screenshot 2023-10-01 at 18 03 39" src="https://github.com/mac-cain13/R.swift/assets/33103001/954c82d2-d4bd-45b1-bace-5dd8aacded1a">

SPM
<img width="148" alt="Screenshot 2023-10-01 at 18 02 08" src="https://github.com/mac-cain13/R.swift/assets/33103001/7305aaa4-577c-4a72-a46d-eb741dd2f103">

Run build tools

<img width="489" alt="Screenshot 2023-10-01 at 18 02 36" src="https://github.com/mac-cain13/R.swift/assets/33103001/f7bdaac4-389e-4b20-a190-336ba53cfa7c">

Error

<img width="597" alt="Screenshot 2023-10-01 at 18 02 58" src="https://github.com/mac-cain13/R.swift/assets/33103001/c5cacb03-3875-4c53-841e-9f0c50587fc0">

How can i resolve this problem?

**Comment by Rylaa** [comment]
@tomlokhorst can you help me with this?

**Comment by kylechandev** [comment]
Does anyone know how to solve this problem?

**Comment by martijnvdwal** [comment]
@Rylaa / @kylechandev 

I think this might solve your issue:

Go to your target settings, select general, and scroll down to **"Frameworks, Libraries, and Embedded Content"** and remove `rswift`, `RswiftLibrary` is the only one you want.

Before Xcode 15, Xcode would ask which libraries to import, but with Xcode 15 it adds all the available libraries by default, so you'll have to do this every time after you add this package to your project.

**Comment by a-kushniarou** [comment]
Thanks @martijnvdwal that helped me

**Comment by dimic-milos** [comment]
If you are still encountering this issue, make sure "Other Linker Flags" under "Build Settings" does NOT contain **RSwiftResources**. We switched from pods to SPM, and could be a leftover. Pain to find

**Comment by eslammoemen** [comment]
@martijnvdwal  you're a life saver !! ♥️

**Comment by kujtimsaliu** [comment]
> [@Rylaa](https://github.com/Rylaa) / [@kylechandev](https://github.com/kylechandev)
> 
> I think this might solve your issue:
> 
> Go to your target settings, select general, and scroll down to **"Frameworks, Libraries, and Embedded Content"** and remove `rswift`, `RswiftLibrary` is the only one you want.
> 
> Before Xcode 15, Xcode would ask which libraries to import, but with Xcode 15 it adds all the available libraries by default, so you'll have to do this every time after you add this package to your project.

@martijnvdwal thanks. that fixed my issue <3
