### ISSUE TITLE
Unable to build using XCode Cloud

### ISSUE THREAD

**Issue by sweetfa** [mac-cain13/R.swift#862]
Hi all,

Am using XCode Cloud to generate an application using R.swift 7.4.0.

The error I am receiving is 
Error: You don’t have permission to save the file “R.generated.swift” in the folder “Resources”.

I have tried things like creating a top level Resources folder, using shell script to ci_post_clone.sh to create the folder, all to no avail.

I am using XCode 15, which does not have the options against the Run Build Tool Plugins items.

Initially I was getting _“RswiftGenerateInternalResources” is disabled_

I overcame this by adding a ci_post_clone script to my build with the contents:
`defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES`

When looking at the plugin to generate internal resources, the Resources folder is only added to the path when used as an XCode Build Tool plugin.

So, what I am struggling with, is this an issue with XCode cloud environment, or what the plugin is generating in this environment?

**Comment by neobeppe** [comment]
Same here

**Comment by neobeppe** [comment]
I also tried to add to ci_post_clone script this command:
`defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES`
And set `ENABLE_USER_SCRIPT_SANDBOXING = NO` 
But nothing changed, I always get the same error

**Comment by shohrabcc** [comment]
i am using, App center and having same issue while using SPM. modify permission issue

**Comment by omerkantar** [comment]
Hello 🖖

I added `defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES` code on _ci_post_clone.sh_ file but xcode cloud build and archive were failed with _`Command exited with non-zero exit-code: 65`_ error.

New error log:
`Run command: 'xcodebuild build -scheme {scheme} -project /Volumes/workspace/repository/xxxx.xcodeproj -destination generic/platform=iOS -derivedDataPath /Volumes/workspace/DerivedData -resultBundleVersion 3 -resultBundlePath /Volumes/workspace/resultbundle.xcresult -resultStreamPath /Volumes/workspace/tmp/resultBundleStream592e544a-683a-46b0-822a-f75bccb80f18.json -IDEPostProgressNotifications=YES CODE_SIGN_IDENTITY=- AD_HOC_CODE_SIGNING_ALLOWED=YES COMPILER_INDEX_STORE_ENABLE=NO -hideShellScriptEnvironment'
`
Does anyone know how to fix it?

**Comment by hiragram** [comment]
any updates?

**Comment by piotrtobolski** [comment]
I am having the same issue with this entry in the log:
```
Error: You don’t have permission to save the file “R.generated.swift” in the folder “Resources”.
```

where in Xcode Cloud UI it shows only:
```
Command exited with non-zero exit-code: 65
```

There is PR #879 that is supposed to fix this issue. Can it be merged?
