### ISSUE TITLE
[Xcode-15] Multiple commands produce fail

### ISSUE THREAD

**Issue by romanenkoio** [mac-cain13/R.swift#863]
Multiple commands produce '/Users/i.romanenko/Library/Developer/Xcode/DerivedData/BSB-Mobile-gopohlcxmrgqtndtowscxqyljieu/Build/Intermediates.noindex/BSB-Mobile.build/Debug-iphonesimulator/BSB-Mobile.build/Objects-normal/arm64/R.generated.stringsdata'

I'm try build project on Xcode 15. In 14.3.1 still worked.
This situation reproduced in new clean project too
Please, anyone, help.

**Comment by erizoo** [comment]
I can't help you. Sorry man. I have same problem.

**Comment by nkavian** [comment]
This happened when I upgrade from the Podfile to the SPM. Try updating your podfile and execute `pod install` to clean things up.

**Comment by realityworks** [comment]
Still a problem. Reverting to R.swift 6. Which does not support Strict Concurrency.

**Comment by mac-cain13** [comment]
Just added R.swift 7.5.0 to a fresh Xcode 16 project. Except that Folder references aren't supported (you must convert it to groups) everything does work out of the box.

If something is broken please do describe the steps from Create new project until you get the error so we can investigate it!
