### ISSUE TITLE
[feature request] Add support for JSON xcode projects

### ISSUE THREAD

**Issue by mrmacete** [mac-cain13/R.swift#866]
It's possible to convert any Xcode project to JSON like this:

`plutil -convert json project.pbxproj`

Xcode happily ingests that format too, but when you do so, `rswift` will fail to parse it.

**Comment by mac-cain13** [comment]
Thank you for your suggestion. However since Xcode won't write out a JSON projectfile by itself does by itself we won't support this for now.
