### ISSUE TITLE
I can't make a build using the RswiftModifyXcodePackages plugin

### ISSUE THREAD

**Issue by DmitriySportsRu** [mac-cain13/R.swift#867]
I used P.swift in my project via cocoapods, everything worked fine. Now I need to use spm.

1. I added the library via spm
<img width="668" alt="Снимок экрана 2023-11-15 в 21 40 07" src="https://github.com/mac-cain13/R.swift/assets/145356538/1f74f160-f099-4a91-aec4-c6c0af506c15">

2. Added rswift and RswiftLibrary products
<img width="652" alt="Снимок экрана 2023-11-15 в 21 40 46" src="https://github.com/mac-cain13/R.swift/assets/145356538/93f64655-fc2d-45ec-aa7d-09f2d8a0c145">

3. Added RswiftGenerateInternalResources to plugins in Build Phases
<img width="455" alt="Снимок экрана 2023-11-15 в 21 41 09" src="https://github.com/mac-cain13/R.swift/assets/145356538/e7ba8193-80a0-4053-a2b7-6b174f44e8f8">

4. Launched the RswiftModifyXcodePackages plugin.
<img width="303" alt="Снимок экрана 2023-11-15 в 21 42 05" src="https://github.com/mac-cain13/R.swift/assets/145356538/cb3f73d3-dc35-45a6-9a9e-870abb45e3a6">

5. After this I start building the project and I get an error

****/Library/Developer/Xcode/DerivedData/Sports-fztfcfietwkstjenyuffwoiganzy/SourcePackages/checkouts/R.swift/Sources/RswiftParsers/ProjectResources.swift:10:8 Could not find module 'RswiftResources' for target 'x86_64-apple-macos'; found: arm64-apple-macos, at: ****/Library/Developer/Xcode/DerivedData/Sports-fztfcfietwkstjenyuffwoiganzy/Build/Products/Debug/RswiftResources.swiftmodule

<img width="1063" alt="Снимок экрана 2023-11-15 в 21 31 32" src="https://github.com/mac-cain13/R.swift/assets/145356538/13fb5161-836a-4607-8b70-c527ae4d6339">

Version: 7.4.0

What am I doing wrong?

**Comment by iznv** [comment]
Try Clean Build Folder. I used to get same error but managed to get rid of it after clean.

**Comment by maqiqing** [comment]
Hey, have you solved this problem?  I have also encountered this problem

**Comment by tomlokhorst** [comment]
I'm not sure why this error is showing up, but do you actually need this step?
It seems in the latest Xcode versions, R.swift works without this step.
