### ISSUE TITLE
Create validation methods for fonts

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#87]
Font validation would check if you have correctly configured your plist, else the font won't load.

**Comment by tomlokhorst** [comment]
There could be a runtime check to see if the file exists. 
Obviously it should be there. But if `rswift` is run manually (not as a build step), the generated file could be outdated, or something.

**Comment by mac-cain13** [comment]
True, but I feel that we especially should validate things that need configuration from the developer and/or super easily break. Like images, renamed classes referenced in storyboard or font files that are not included in the plist. So I think we should start out with those. :)
