### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by Angus-chang** [mac-cain13/R.swift#872]
Following definition of "third-party SDKs" that as mentioned in the WWDC23. and according to [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files), I think this library may also require a Privacy Manifest for the upcoming app review in Spring 2024.

Do you have any plans to add a Privacy Manifest or to have a claim that this library actually does not need a Privacy Manifest?

Thank you very much!

**Comment by tomlokhorst** [comment]
I've look through Apple's documentation, but I don't see mention of any of the APIs that are used by the Rswift library.
So I don't think a Privacy Manifest is needed?

If anyone knows more about this, please let us known.

**Comment by aiKrice** [comment]
I confirm this is not mandatory for R.Swift. This issue can be closed
