### ISSUE TITLE
Formatting only part of a string using R.string.localizable

### ISSUE THREAD

**Issue by nicobelo91** [mac-cain13/R.swift#876]
Let's say I have the following text in the `Localizable.swift` file:
`"name" = "My name is %@";`
I'd like to make the part where the name would go bold, so that it would read something like "My name is **Mark**" whenever I use `R.string.localizable.name("Mark")`.
Is there a way to do that using R.swift?

**Comment by tomlokhorst** [comment]
R.swift has no special support for formatting.

But you can use the existing APIs like `AttributedString`.

For example:
```
// Localizeable.strings
"name" = "My name is **%@**";
```

```swift
// ContentView.swift
if let attributedString = try? AttributedString(markdown: R.string.localizable.name("Mark")) {
    Text(attributedString)
}
```
