### ISSUE TITLE
Classes from other CocoaPods are not available

### ISSUE THREAD

**Issue by kylebshr** [mac-cain13/R.swift#89]
Hello, 

I'm attempting to use FXForms in conjunction with R.swift, and there's a UIViewController subclass `FXFormViewController` that I need to use in my storyboard. However, because R.generated.swift doesn't import FXForms, it can't compile because `FXFormViewController` is an undeclared type. 

Hopefully there's a simple workaround for this. Thanks!

**Comment by kylebshr** [comment]
I'm feeling a little foolish now — I typed `FXFormViewController` when I needed to use my own view controller subclass, and that subclass works fine in R.swift. This is a non-issue.

**Comment by mac-cain13** [comment]
Np, glad it's working for you! Thanks for using R.swift. :)
