### ISSUE TITLE
Accessibility identifiers

### ISSUE THREAD

**Issue by artsimonyan23** [mac-cain13/R.swift#893]
Can't disable id warnings. The generator is "--generators image,string,color,file,font,nib,storyboard,reuseIdentifier,info,data", but I receive warnings about accessibility identifiers. 

"Skipping 3 accessibility identifiers in ProductTCellView because symbol 'efA94cF63001ccfbb2' would be generated for all of these accessibility identifiers: 03188920-0635-11ef-a94c-f63001ccfbb2, 03188952-0635-11ef-a94c-f63001ccfbb2, 03188970-0635-11ef-a94c-f63001ccfbb2"

**Comment by mac-cain13** [comment]
I think the warning is correct right? Those IDs are set and duplicates so R.swift warns you so you are not confused about why they don't show up.

You can customize the accessibility IDs in interface builder UI here:
![CleanShot 2024-09-19 at 10 27 19@2x](https://github.com/user-attachments/assets/8740be2c-e89c-4c0e-9c39-eb67bceef9a5)
