### ISSUE TITLE
Jenkins  error: “RswiftGenerateInternalResources” must be enabled before it can be used

### ISSUE THREAD

**Issue by kathiravan-raju** [mac-cain13/R.swift#895]
I have Integrated the R.swift framework via spm in my project. And then enabled the RswiftGenerateInternalResources in xcode while building the application in Xcode.
**Followed below steps while integrating R.swift in my project.**
In Project Settings, on the tab "Package Dependencies", click "+" and add github.com/mac-cain13/R.swift
Select your target, on the tab "General", in the section "Frameworks, Libraries, and Embeded Content", click "+" and add RswiftLibrary
Select your target, on the tab "Build Phases", in the section "Run Build Tool Plug-ins", click "+" and add RswiftGenerateInternalResources
Build your project, now the R struct should be available in your code, use auto-complete to explore all static references

It working fine when I run the application locally in my Xcode but the Jenkins build failed with the below error message
**error: “RswiftGenerateInternalResources” must be enabled before it can be used**
<img width="1033" alt="Screenshot 2024-05-10 at 2 26 17 PM" src="https://github.com/mac-cain13/R.swift/assets/137410728/75abb6c8-2a38-4120-9230-d1315a84f238">

Please assist me in resolving this issue.
Thanks

**Comment by kathiravan-raju** [comment]
Hi,
Could somebody please take a look into the above issue?
Thanks in advance

**Comment by SaravanakumarNatarajan2931** [comment]
I too facing this issue, @tomlokhorst any idea about this issue to fix?

**Comment by tomlokhorst** [comment]
I’m not familiar with Jenkins, but I suspect you need to disable plugin validation, like with Xcode Cloud. See: https://github.com/mac-cain13/R.swift?tab=readme-ov-file#when-running-on-xcode-cloudOn 17 May 2024, at 18:07, SaravanakumarNatarajan2931 ***@***.***> wrote:﻿
I too facing this issue, @tomlokhorst any idea about this issue to fix?

**Comment by SaravanakumarNatarajan2931** [comment]
ok @tomlokhorst let me try that things.

**Comment by mac-cain13** [comment]
@julien481516 would need some additional info to help here. The instruction I the Readme is for Xcode cloud to disable plugin validation.

What CI are you using? What exactly did you do when "switching IDESkipPackagePluginFingerprintValidation to YES in my ci file"?

Please note it's not a magic variable or anything you need to set. You need to set `IDESkipPackagePluginFingerprintValidatation` to `YES` in the Xcode user defaults. So on any CI make sure to run this command before invoking the Xcode build:

`defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES`

**Comment by clopex** [comment]
@mac-cain13  this does not work for xcode cloud

**Comment by whoisronak** [comment]
R.swift on Xcode Cloud or any other CI

On your CI server you can't explicitly allow the build plugin to run, so you need to disable plugin validation to be able to build without user interaction:

Run a script on your CI that runs: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES before Xcode starts building.
On Xcode Cloud you can add a [custom build script](https://developer.apple.com/documentation/xcode/writing-custom-build-scripts) in ci_scripts/ci_post_clone.sh with this line that Xcode will run.
