### ISSUE TITLE
Don't create functions on Xcode 15.3

### ISSUE THREAD

**Issue by Yaozitao0322** [mac-cain13/R.swift#901]
R.generated have source functions on old Xcode. but not methods in new project.
next is old project.
![image](https://github.com/user-attachments/assets/8e011690-a06c-4c85-9ef7-e911a941b061)

next id new project.
![image](https://github.com/user-attachments/assets/415d6954-3ef8-46a3-b3f2-3cdb530f316e)
![image](https://github.com/user-attachments/assets/564191aa-77d3-429e-ac2b-d6b912ee28aa)

**Comment by tomlokhorst** [comment]
Yes, the generated code has changed between R.swift 6 and R.swift 7.

But the way you use that code hasn’t changed.

You can still call `R.image.home_top_background()` on the ImageResource.
It implements `callAsFunction` and will return an optional UIImage.
