### ISSUE TITLE
Let 'R' is not concurrency-safe because non-'Sendable' type '_R' may have shared mutable state

### ISSUE THREAD

**Issue by jeannustre** [mac-cain13/R.swift#902]
Hi,

We're getting a build error in R.generated.swift line 10 : 

> Let 'R' is not concurrency-safe because non-'Sendable' type '_R' may have shared mutable state

This happens on Xcode 16 Beta 4 (Swift 6), using either R.swift 7.5.0 or 7.5.1-alpha.3.

**Comment by Lumisilk** [comment]
Just in case, for now you can workaround it by add this:
```swift
extension _R: @unchecked Sendable {}
```

**Comment by tomlokhorst** [comment]
Fixed in release 7.6.0

**Comment by jaltreuter** [comment]
In case anyone else is running into this issue even after updating, I'll note that this is fixed for me (I'm using 7.7.0) but I had to delete the contents of each of my `R.generated.swift` files in order to force re-generation of these files.  Must be some kind of caching issue?
