### ISSUE TITLE
When using R.image the tintColor property of UIView does not work, version 7.5.0

### ISSUE THREAD

**Issue by Olexantor** [mac-cain13/R.swift#908]
I would like to get clarification from you. Do I understand correctly that previously you had the “withRenderingMode(_:)” method built into the library itself and therefore the image resources were recolored by assigning a color through the tintColor property, but in the new version of the library this method is not called by default for image resources?

**Comment by tomlokhorst** [comment]
No, R.swift never had withRenderingMode built-in.
This is a method on UIImage that you can call on an image returned from R.swift

**Comment by Olexantor** [comment]
Thank you for an answer!
