### ISSUE TITLE
--onelineforeach ignore is not working

### ISSUE THREAD

**Issue by bauyrzhanabdi** [mac-cain13/R.swift#909]
My .swiftformat file contains this

> # format options
> --onelineforeach ignore
> # rules
> -enable isEmpty

This is the original code
```
let letters: [String] = ["h", "e", "l", "l", "o"]
letters.forEach { letter in
   print(letter)
}
```

After I run swiftformat script, it updates the code into this
```
let letters: [String] = ["h", "e", "l", "l", "o"]
for letter in letters {
   print(letter)
}
```

Even though onelineforeach is set to ignore, the format option is not ignored.
Despite this, its default state is set to convert and not to ignore as it was stated in documentation.
So, even without explicitly setting onelineforeach to ignore, it still converts the code

**Comment by mac-cain13** [comment]
@bauyrzhanabdi seems like you wanted to report an issue to Swiftformat and not R.swift? Maybe open the issue there.

If the problem is that you try to format generated code, I think you should exclude generated code from your formatters. :)
