### ISSUE TITLE
Tuist

### ISSUE THREAD

**Issue by alessdiimperio** [mac-cain13/R.swift#911]
I'm trying to migrate over to Tuist an can't seem to get R.swift working.
The files are generated in some derived data directory complaining about RswiftResources not being available. 🤔 

Anybody using tuist and rswift together that have solved this?

(i am aware that i can fetch the rswift executable directly and use it but was somewhat hoping for a cleaner solution. any tips welcome.

**Comment by tomlokhorst** [comment]
I haven't used Tuist, but make sure to depend on RswiftLibrary in the target that you use Rswift in. 

See the steps for SPM here: https://github.com/mac-cain13/R.swift?tab=readme-ov-file#packageswift-based-spm-project

The R.swift plug-in does generate files in the derived data directory, in Xcode and SPM packages, they are compiled along with the rest of the source code. Again, I haven't used Tuist, but I assume that would work the same way there.
