### ISSUE TITLE
R.swift doesn't work with Folders in Xcode 16

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#914]
Xcode 16 default project structure uses Folders instead of Groups.
R.swift ignores Folders, which means resources in them aren't added to `R.*`.

As a workaround, you can convert Folders back into Groups, this makes it work with R.swift.
<img width="530" alt="CleanShot 2024-09-26 at 22 19 18@2x" src="https://github.com/user-attachments/assets/ec18c063-6a0a-4f59-aded-38dcf3a896a4">

Long term, R.swift should add support for scanning Folders.

**Comment by yisRookie** [comment]
I have the same problem,Xcode 16.0 Have  Error
Error: Project file at 'file:///Users/XXXX/XXXX/XXX/XX/XXX/XXXt/XXXXt.xcodeproj/' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?
The file “project.pbxproj” couldn’t be opened because you don’t have permission to view it.

**Comment by nicolasvergoz** [comment]
I just finished converting a huge project to folders, only to find out that RSwift is not compatible as is 😫

You have to set `--input-type input-files --intput-files <path-to-file-1> --intput-files <path-to-file-2>` for each files you need to be processed.

Here is what I did :

```sh
"$SRCROOT/scripts/rswift" generate \
  --input-type input-files \
  --input-files $SRCROOT/Ressources/Assets.xcassets \
  $(find $SRCROOT/Ressources/Fonts -name '*.ttf' -exec echo --input-files {} \;) \
  $(find $SRCROOT/Ressources/Fonts -name '*.otf' -exec echo --input-files {} \;) \
  $(find $SRCROOT/Ressources/Strings -name '*.strings' -exec echo --input-files {} \;) \
  $(find $SRCROOT/Ressources/Strings -name '*.stringsdict' -exec echo --input-files {} \;) \
  $(find $SRCROOT/Ressources/Files -name '*.json' -exec echo --input-files {} \;) \
  $(find $SRCROOT/ -name '*.storyboard' -exec echo --input-files {} \;) \
  $(find $SRCROOT/ -name '*.xib' -exec echo --input-files {} \;) \
  --target YOUR_TARGET \
  "$SRCROOT/R.generated.swift"
```

I don't know if target is necessary though

**Comment by tomlokhorst** [comment]
Indeed `--input-type input-files` is the version used for SPM plugins. That works by providing individual files, like you did here with the find commands.

The default mode for Xcode build tool plug-ins is `--input-type xcodeproj`, which scans the Xcode project file for resources.  That version doesn't handle folder references yet. 

Your solution is a good workaround in the meantime. The target isn't needed.

**Comment by anatoliykant** [comment]
As far as I understand, this problem was fixed in the latest version of swiftlint?! 
At least this error disappeared for me.

**Comment by fthdgn** [comment]
I opened an PR about this error.
https://github.com/mac-cain13/R.swift/pull/920

Also I needed to update XcodeEdit project.
https://github.com/tomlokhorst/XcodeEdit/pull/48
