### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by RizwanaDesai** [mac-cain13/R.swift#915]
We’re currently adding visionOS support to an existing project, and the lack of R.swift integration for visionOS is creating a lot of additional manual work in managing resources.

Are there any timelines or ongoing discussions around this?

Alternatively, if there’s a workaround or any suggestions for an alternative solution, that would be greatly appreciated.

**Comment by tomlokhorst** [comment]
R.swift should work for visionOS. I haven't used it in practice, but the basic "Hello World" setup works.

Is there anything in specific that isn't working correctly?
