### ISSUE TITLE
No R.swift file after migration

### ISSUE THREAD

**Issue by clopex** [mac-cain13/R.swift#926]
I follow your video for migration from 6 to 7 version, from CocaPods to SPM and after all steps build does not run successfully and I can not see file 'R.swift' in my project. Any idea how to solve this?

Thanks

**Comment by tomlokhorst** [comment]
With the modern Build Tool Plug-in, the generated output file R.generated.swift no longer is located in your project directory, but instead in Derived Data.

Whenever you build your project, the file is first generated, and the rest of your code can refer to the generated code.

Are you seeing an error? What error are you seeing when building after migration?

**Comment by clopex** [comment]
A lot of errors referencing to R.swift:

![Screenshot 2024-11-30 at 12 59 08](https://github.com/user-attachments/assets/05b08c6b-b08f-4855-97cd-b7e61ce51f2a)
![Screenshot 2024-11-30 at 12 59 13](https://github.com/user-attachments/assets/cbd3775d-eadd-41f1-90e6-2dac6aa16afa)

**Comment by tomlokhorst** [comment]
Make sure to do a clean build. And check the build log to see if the build step actually ran. If the R.swift build step doesn't run, the rest of your code also won't compile.

**Comment by clopex** [comment]
Hm for some reason after couple of times clean and build I manage to build successfully. Thanks
