### ISSUE TITLE
Missing "import AVKit" when using AVPlayerViewController in storyboard

### ISSUE THREAD

**Issue by alexanderjrobinson** [mac-cain13/R.swift#98]
If a storyboard includes the AVPlayerViewController the R.generated.swift file fails to compile because AVKit is not imported. AVPlayerViewController is a standard component in the Object Library.

This is likely to be an issue with the GLKit View Controller as well as custom view controllers from third party libraries.

Ideally R.swift could interrogate the types of the view controllers in the storyboard and add the necessary import statements. Or perhaps provide an option to override/extend the import statements via a config file or parameters in the run script.

**Comment by mac-cain13** [comment]
Thanks for reporting this, I think R.swift should detect Apple frameworks as much as possible and import them for you.

Imports needed for other libraries should indeed be extendable in some way.

**Comment by LeeroyDing** [comment]
Is there a workaround so far?

**Comment by mac-cain13** [comment]
No not really, I should take some time and fix this. I have some time this week, I'll look into it in the coming days. :)

Are you using an `AV*` class or a custom class?

**Comment by tomlokhorst** [comment]
As a workaround:

You could create a subclass of the AVPlayerViewController in your own project and use that in the Storyboard. That subclass shouldn't require an import in the `R.generated.swift` file.

**Comment by mac-cain13** [comment]
R.swift 1.0.0 beta 2 will import all modules that are not the product module. That should fix this issue. Beta 2 will be out soon, it's on the 1.0.0 branch already

**Comment by LeeroyDing** [comment]
I'm experiencing this issue, with `SKView` this time. It's part of SpriteKit.

**Comment by mac-cain13** [comment]
Thanks for reporting.

What version of r.swift are you using? 1.0 and higher should correctly import your view.

Could you maybe paste the lines using SKView in the generated file here to give me some context? And maybe provide some info about where the SKView is in your storyboard or xib?

That would make reproducing it easier!

**Comment by LeeroyDing** [comment]
Here's a demo of how it breaks:

https://github.com/LeeroyDing/RSwiftDemo/commits/master

What I did was adding a nib with a `SKView` inside, the last commit was changing the default `UIView` into a `SKView`.

**Comment by mac-cain13** [comment]
Cool, I'll check it out tomorrow! :)

**Comment by mac-cain13** [comment]
@LeeroyDing I've checked out your example project. I think that the most clean solution is to set the module field (right below the class field where you put in `SKView`) to `SpriteKit` this will make R.swift correctly import the class. Seems that Apple does this implicitly if you use the xib. :(

The alternative is that R.swift maintains a list of Apple classes and maps them to the correct module, but I'm afraid that will become a hassle to maintain. Maybe adding that you should explicitly state the module in the xib or storyboard is enough for now.

Hope stating the module to the xib will fix your issue!
